//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: android/libcore/luni/src/main/java/java/util/concurrent/BrokenBarrierException.java
//

#ifndef _JavaUtilConcurrentBrokenBarrierException_H_
#define _JavaUtilConcurrentBrokenBarrierException_H_

#include "J2ObjC_header.h"
#include "java/lang/Exception.h"

#define JavaUtilConcurrentBrokenBarrierException_serialVersionUID 7117394618823254244LL

@interface JavaUtilConcurrentBrokenBarrierException : JavaLangException {
}

- (instancetype)init;

- (instancetype)initWithNSString:(NSString *)message;

@end

J2OBJC_EMPTY_STATIC_INIT(JavaUtilConcurrentBrokenBarrierException)

CF_EXTERN_C_BEGIN

J2OBJC_STATIC_FIELD_GETTER(JavaUtilConcurrentBrokenBarrierException, serialVersionUID, jlong)
CF_EXTERN_C_END

J2OBJC_TYPE_LITERAL_HEADER(JavaUtilConcurrentBrokenBarrierException)

#endif // _JavaUtilConcurrentBrokenBarrierException_H_
