//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: android/libcore/luni/src/main/java/java/util/concurrent/ConcurrentMap.java
//

#ifndef _JavaUtilConcurrentConcurrentMap_H_
#define _JavaUtilConcurrentConcurrentMap_H_

#include "J2ObjC_header.h"
#include "java/util/Map.h"

@protocol JavaUtilConcurrentConcurrentMap < JavaUtilMap, NSObject, JavaObject >
- (id)putIfAbsentWithId:(id)key
                 withId:(id)value;

- (jboolean)removeWithId:(id)key
                  withId:(id)value;

- (jboolean)replaceWithId:(id)key
                   withId:(id)oldValue
                   withId:(id)newValue;

- (id)replaceWithId:(id)key
             withId:(id)value;

@end

J2OBJC_EMPTY_STATIC_INIT(JavaUtilConcurrentConcurrentMap)

J2OBJC_TYPE_LITERAL_HEADER(JavaUtilConcurrentConcurrentMap)

#endif // _JavaUtilConcurrentConcurrentMap_H_
