//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: android/libcore/luni/src/main/java/java/io/CharConversionException.java
//

#ifndef _JavaIoCharConversionException_H_
#define _JavaIoCharConversionException_H_

#include "J2ObjC_header.h"
#include "java/io/IOException.h"

#define JavaIoCharConversionException_serialVersionUID -8680016352018427031LL

@interface JavaIoCharConversionException : JavaIoIOException {
}

- (instancetype)init;

- (instancetype)initWithNSString:(NSString *)detailMessage;

@end

J2OBJC_EMPTY_STATIC_INIT(JavaIoCharConversionException)

CF_EXTERN_C_BEGIN

J2OBJC_STATIC_FIELD_GETTER(JavaIoCharConversionException, serialVersionUID, jlong)
CF_EXTERN_C_END

J2OBJC_TYPE_LITERAL_HEADER(JavaIoCharConversionException)

#endif // _JavaIoCharConversionException_H_
