//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: android/libcore/luni/src/main/java/java/io/Closeable.java
//
//  Created by tball on 7/15/13.
//

#ifndef _JavaIoCloseable_H_
#define _JavaIoCloseable_H_

#import "JreEmulation.h"
#include "java/lang/AutoCloseable.h"

@protocol JavaIoCloseable < JavaLangAutoCloseable, NSObject, JavaObject >
- (void)close;
@end

#endif // _JavaIoCloseable_H_
