//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: android/libcore/luni/src/main/java/java/io/SequenceInputStream.java
//

#ifndef _JavaIoSequenceInputStream_H_
#define _JavaIoSequenceInputStream_H_

@class IOSByteArray;
@protocol JavaUtilEnumeration;

#include "J2ObjC_header.h"
#include "java/io/InputStream.h"

@interface JavaIoSequenceInputStream : JavaIoInputStream {
}

- (instancetype)initWithJavaIoInputStream:(JavaIoInputStream *)s1
                    withJavaIoInputStream:(JavaIoInputStream *)s2;

- (instancetype)initWithJavaUtilEnumeration:(id<JavaUtilEnumeration>)e;

- (jint)available;

- (void)close;

- (jint)read;

- (jint)readWithByteArray:(IOSByteArray *)buffer
                  withInt:(jint)offset
                  withInt:(jint)count;

@end

J2OBJC_EMPTY_STATIC_INIT(JavaIoSequenceInputStream)

CF_EXTERN_C_BEGIN
CF_EXTERN_C_END

J2OBJC_TYPE_LITERAL_HEADER(JavaIoSequenceInputStream)

#endif // _JavaIoSequenceInputStream_H_
