//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: apache_harmony/classlib/modules/luni/src/main/java/java/io/SyncFailedException.java
//
//  Created by tball on 7/15/13.
//

#ifndef _JavaIoSyncFailedException_H_
#define _JavaIoSyncFailedException_H_

#import "JreEmulation.h"
#include "java/io/IOException.h"

#define JavaIoSyncFailedException_serialVersionUID -2353342684412443330

@interface JavaIoSyncFailedException : JavaIoIOException {
}

- (id)initWithNSString:(NSString *)detailMessage;
@end

#endif // _JavaIoSyncFailedException_H_
