//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: /Users/krasnocka/Downloads/j2objc-master/testing/mockito/build_result/java/org/mockito/exceptions/verification/SmartNullPointerException.java
//

#ifndef _OrgMockitoExceptionsVerificationSmartNullPointerException_H_
#define _OrgMockitoExceptionsVerificationSmartNullPointerException_H_

#include "J2ObjC_header.h"
#include "org/mockito/exceptions/base/MockitoException.h"

#define OrgMockitoExceptionsVerificationSmartNullPointerException_serialVersionUID 1LL

@interface OrgMockitoExceptionsVerificationSmartNullPointerException : OrgMockitoExceptionsBaseMockitoException {
}

- (instancetype)initWithNSString:(NSString *)message;

@end

J2OBJC_EMPTY_STATIC_INIT(OrgMockitoExceptionsVerificationSmartNullPointerException)

CF_EXTERN_C_BEGIN

J2OBJC_STATIC_FIELD_GETTER(OrgMockitoExceptionsVerificationSmartNullPointerException, serialVersionUID, jlong)
CF_EXTERN_C_END

J2OBJC_TYPE_LITERAL_HEADER(OrgMockitoExceptionsVerificationSmartNullPointerException)

#endif // _OrgMockitoExceptionsVerificationSmartNullPointerException_H_
