//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: android/frameworks/base/core/java/android/test/suitebuilder/annotation/MediumTest.java
//

#ifndef _AndroidTestSuitebuilderAnnotationMediumTest_H_
#define _AndroidTestSuitebuilderAnnotationMediumTest_H_

#include "J2ObjC_header.h"
#include "java/lang/annotation/Annotation.h"

@protocol AndroidTestSuitebuilderAnnotationMediumTest < JavaLangAnnotationAnnotation >

@end

@interface AndroidTestSuitebuilderAnnotationMediumTest : NSObject < AndroidTestSuitebuilderAnnotationMediumTest >

@end

J2OBJC_EMPTY_STATIC_INIT(AndroidTestSuitebuilderAnnotationMediumTest)

J2OBJC_TYPE_LITERAL_HEADER(AndroidTestSuitebuilderAnnotationMediumTest)

#endif // _AndroidTestSuitebuilderAnnotationMediumTest_H_
