//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: android/libcore/luni/src/main/java/java/nio/channels/NonWritableChannelException.java
//

#ifndef _JavaNioChannelsNonWritableChannelException_H_
#define _JavaNioChannelsNonWritableChannelException_H_

#include "J2ObjC_header.h"
#include "java/lang/IllegalStateException.h"

#define JavaNioChannelsNonWritableChannelException_serialVersionUID -7071230488279011621LL

@interface JavaNioChannelsNonWritableChannelException : JavaLangIllegalStateException {
}

- (instancetype)init;

@end

J2OBJC_EMPTY_STATIC_INIT(JavaNioChannelsNonWritableChannelException)

CF_EXTERN_C_BEGIN

J2OBJC_STATIC_FIELD_GETTER(JavaNioChannelsNonWritableChannelException, serialVersionUID, jlong)
CF_EXTERN_C_END

J2OBJC_TYPE_LITERAL_HEADER(JavaNioChannelsNonWritableChannelException)

#endif // _JavaNioChannelsNonWritableChannelException_H_
