//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: /Users/krasnocka/Downloads/j2objc-master/guava/sources/com/google/common/hash/Hasher.java
//

#include "J2ObjC_header.h"

#if !ComGoogleCommonHashHasher_RESTRICT
#define ComGoogleCommonHashHasher_INCLUDE_ALL 1
#endif
#undef ComGoogleCommonHashHasher_RESTRICT
#if !defined (_ComGoogleCommonHashHasher_) && (ComGoogleCommonHashHasher_INCLUDE_ALL || ComGoogleCommonHashHasher_INCLUDE)
#define _ComGoogleCommonHashHasher_

@class ComGoogleCommonHashHashCode;
@class IOSByteArray;
@class JavaNioCharsetCharset;
@protocol ComGoogleCommonHashFunnel;
@protocol JavaLangCharSequence;

#define ComGoogleCommonHashPrimitiveSink_RESTRICT 1
#define ComGoogleCommonHashPrimitiveSink_INCLUDE 1
#include "com/google/common/hash/PrimitiveSink.h"


@protocol ComGoogleCommonHashHasher < ComGoogleCommonHashPrimitiveSink, NSObject, JavaObject >
- (id<ComGoogleCommonHashHasher>)putByteWithByte:(jbyte)b;

- (id<ComGoogleCommonHashHasher>)putBytesWithByteArray:(IOSByteArray *)bytes;

- (id<ComGoogleCommonHashHasher>)putBytesWithByteArray:(IOSByteArray *)bytes
                                               withInt:(jint)off
                                               withInt:(jint)len;

- (id<ComGoogleCommonHashHasher>)putShortWithShort:(jshort)s;

- (id<ComGoogleCommonHashHasher>)putIntWithInt:(jint)i;

- (id<ComGoogleCommonHashHasher>)putLongWithLong:(jlong)l;

- (id<ComGoogleCommonHashHasher>)putFloatWithFloat:(jfloat)f;

- (id<ComGoogleCommonHashHasher>)putDoubleWithDouble:(jdouble)d;

- (id<ComGoogleCommonHashHasher>)putBooleanWithBoolean:(jboolean)b;

- (id<ComGoogleCommonHashHasher>)putCharWithChar:(jchar)c;

- (id<ComGoogleCommonHashHasher>)putStringWithJavaLangCharSequence:(id<JavaLangCharSequence>)charSequence;

- (id<ComGoogleCommonHashHasher>)putStringWithJavaLangCharSequence:(id<JavaLangCharSequence>)charSequence
                                         withJavaNioCharsetCharset:(JavaNioCharsetCharset *)charset;

- (id<ComGoogleCommonHashHasher>)putObjectWithId:(id)instance
                   withComGoogleCommonHashFunnel:(id<ComGoogleCommonHashFunnel>)funnel;

- (ComGoogleCommonHashHashCode *)hash__;

@end

J2OBJC_EMPTY_STATIC_INIT(ComGoogleCommonHashHasher)
#endif

J2OBJC_TYPE_LITERAL_HEADER(ComGoogleCommonHashHasher)
