//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: /Users/krasnocka/Downloads/j2objc-master/guava/sources/com/google/common/collect/EnumMultiset.java
//

#include "J2ObjC_header.h"

#if !ComGoogleCommonCollectEnumMultiset_RESTRICT
#define ComGoogleCommonCollectEnumMultiset_INCLUDE_ALL 1
#endif
#undef ComGoogleCommonCollectEnumMultiset_RESTRICT
#if !defined (_ComGoogleCommonCollectEnumMultiset_) && (ComGoogleCommonCollectEnumMultiset_INCLUDE_ALL || ComGoogleCommonCollectEnumMultiset_INCLUDE)
#define _ComGoogleCommonCollectEnumMultiset_

@class IOSClass;
@class JavaIoObjectInputStream;
@class JavaIoObjectOutputStream;
@protocol JavaLangIterable;

#define ComGoogleCommonCollectAbstractMapBasedMultiset_RESTRICT 1
#define ComGoogleCommonCollectAbstractMapBasedMultiset_INCLUDE 1
#include "com/google/common/collect/AbstractMapBasedMultiset.h"


#define ComGoogleCommonCollectEnumMultiset_serialVersionUID 0LL

@interface ComGoogleCommonCollectEnumMultiset : ComGoogleCommonCollectAbstractMapBasedMultiset {
}

+ (ComGoogleCommonCollectEnumMultiset *)createWithIOSClass:(IOSClass *)type;

+ (ComGoogleCommonCollectEnumMultiset *)createWithJavaLangIterable:(id<JavaLangIterable>)elements;

+ (ComGoogleCommonCollectEnumMultiset *)createWithJavaLangIterable:(id<JavaLangIterable>)elements
                                                      withIOSClass:(IOSClass *)type;


@end

J2OBJC_EMPTY_STATIC_INIT(ComGoogleCommonCollectEnumMultiset)

CF_EXTERN_C_BEGIN

FOUNDATION_EXPORT ComGoogleCommonCollectEnumMultiset *ComGoogleCommonCollectEnumMultiset_createWithIOSClass_(IOSClass *type);

FOUNDATION_EXPORT ComGoogleCommonCollectEnumMultiset *ComGoogleCommonCollectEnumMultiset_createWithJavaLangIterable_(id<JavaLangIterable> elements);

FOUNDATION_EXPORT ComGoogleCommonCollectEnumMultiset *ComGoogleCommonCollectEnumMultiset_createWithJavaLangIterable_withIOSClass_(id<JavaLangIterable> elements, IOSClass *type);

J2OBJC_STATIC_FIELD_GETTER(ComGoogleCommonCollectEnumMultiset, serialVersionUID, jlong)
CF_EXTERN_C_END
#endif

J2OBJC_TYPE_LITERAL_HEADER(ComGoogleCommonCollectEnumMultiset)
