//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: /Users/krasnocka/Downloads/j2objc-master/guava/sources/com/google/common/collect/ForwardingImmutableSet.java
//

#include "J2ObjC_header.h"

#if !ComGoogleCommonCollectForwardingImmutableSet_RESTRICT
#define ComGoogleCommonCollectForwardingImmutableSet_INCLUDE_ALL 1
#endif
#undef ComGoogleCommonCollectForwardingImmutableSet_RESTRICT
#if !defined (_ComGoogleCommonCollectForwardingImmutableSet_) && (ComGoogleCommonCollectForwardingImmutableSet_INCLUDE_ALL || ComGoogleCommonCollectForwardingImmutableSet_INCLUDE)
#define _ComGoogleCommonCollectForwardingImmutableSet_


@interface ComGoogleCommonCollectForwardingImmutableSet : NSObject {
}

@end

J2OBJC_EMPTY_STATIC_INIT(ComGoogleCommonCollectForwardingImmutableSet)

CF_EXTERN_C_BEGIN
CF_EXTERN_C_END
#endif

J2OBJC_TYPE_LITERAL_HEADER(ComGoogleCommonCollectForwardingImmutableSet)
