//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: /Users/krasnocka/Downloads/j2objc-master/guava/sources/com/google/common/collect/ImmutableMapEntrySet.java
//

#include "J2ObjC_header.h"

#if !ComGoogleCommonCollectImmutableMapEntrySet_RESTRICT
#define ComGoogleCommonCollectImmutableMapEntrySet_INCLUDE_ALL 1
#endif
#undef ComGoogleCommonCollectImmutableMapEntrySet_RESTRICT
#if !defined (_ComGoogleCommonCollectImmutableMapEntrySet_) && (ComGoogleCommonCollectImmutableMapEntrySet_INCLUDE_ALL || ComGoogleCommonCollectImmutableMapEntrySet_INCLUDE)
#define _ComGoogleCommonCollectImmutableMapEntrySet_

@class ComGoogleCommonCollectImmutableMap;

#define ComGoogleCommonCollectImmutableSet_RESTRICT 1
#define ComGoogleCommonCollectImmutableSet_INCLUDE 1
#include "com/google/common/collect/ImmutableSet.h"


@interface ComGoogleCommonCollectImmutableMapEntrySet : ComGoogleCommonCollectImmutableSet {
}

- (instancetype)init;

- (ComGoogleCommonCollectImmutableMap *)map;

- (jint)size;

- (jboolean)containsWithId:(id)object;

- (jboolean)isPartialView;

- (id)writeReplace;


@end

J2OBJC_EMPTY_STATIC_INIT(ComGoogleCommonCollectImmutableMapEntrySet)

CF_EXTERN_C_BEGIN
CF_EXTERN_C_END
#endif

J2OBJC_TYPE_LITERAL_HEADER(ComGoogleCommonCollectImmutableMapEntrySet)
#if !defined (_ComGoogleCommonCollectImmutableMapEntrySet_EntrySetSerializedForm_) && (ComGoogleCommonCollectImmutableMapEntrySet_INCLUDE_ALL || ComGoogleCommonCollectImmutableMapEntrySet_EntrySetSerializedForm_INCLUDE)
#define _ComGoogleCommonCollectImmutableMapEntrySet_EntrySetSerializedForm_

@class ComGoogleCommonCollectImmutableMap;

#define JavaIoSerializable_RESTRICT 1
#define JavaIoSerializable_INCLUDE 1
#include "java/io/Serializable.h"


#define ComGoogleCommonCollectImmutableMapEntrySet_EntrySetSerializedForm_serialVersionUID 0LL

@interface ComGoogleCommonCollectImmutableMapEntrySet_EntrySetSerializedForm : NSObject < JavaIoSerializable > {
 @public
  ComGoogleCommonCollectImmutableMap *map_;
}

- (instancetype)initWithComGoogleCommonCollectImmutableMap:(ComGoogleCommonCollectImmutableMap *)map;

- (id)readResolve;

@end

J2OBJC_EMPTY_STATIC_INIT(ComGoogleCommonCollectImmutableMapEntrySet_EntrySetSerializedForm)

J2OBJC_FIELD_SETTER(ComGoogleCommonCollectImmutableMapEntrySet_EntrySetSerializedForm, map_, ComGoogleCommonCollectImmutableMap *)

CF_EXTERN_C_BEGIN

J2OBJC_STATIC_FIELD_GETTER(ComGoogleCommonCollectImmutableMapEntrySet_EntrySetSerializedForm, serialVersionUID, jlong)
CF_EXTERN_C_END
#endif

J2OBJC_TYPE_LITERAL_HEADER(ComGoogleCommonCollectImmutableMapEntrySet_EntrySetSerializedForm)
