//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: /Users/krasnocka/Downloads/j2objc-master/guava/sources/com/google/common/collect/ImmutableSortedSetFauxverideShim.java
//

#include "J2ObjC_header.h"

#if !ComGoogleCommonCollectImmutableSortedSetFauxverideShim_RESTRICT
#define ComGoogleCommonCollectImmutableSortedSetFauxverideShim_INCLUDE_ALL 1
#endif
#undef ComGoogleCommonCollectImmutableSortedSetFauxverideShim_RESTRICT
#if !defined (_ComGoogleCommonCollectImmutableSortedSetFauxverideShim_) && (ComGoogleCommonCollectImmutableSortedSetFauxverideShim_INCLUDE_ALL || ComGoogleCommonCollectImmutableSortedSetFauxverideShim_INCLUDE)
#define _ComGoogleCommonCollectImmutableSortedSetFauxverideShim_

@class ComGoogleCommonCollectImmutableSortedSet;
@class ComGoogleCommonCollectImmutableSortedSet_Builder;
@class IOSObjectArray;

#define ComGoogleCommonCollectImmutableSet_RESTRICT 1
#define ComGoogleCommonCollectImmutableSet_INCLUDE 1
#include "com/google/common/collect/ImmutableSet.h"


@interface ComGoogleCommonCollectImmutableSortedSetFauxverideShim : ComGoogleCommonCollectImmutableSet {
}

+ (ComGoogleCommonCollectImmutableSortedSet_Builder *)builder;

+ (ComGoogleCommonCollectImmutableSortedSet *)ofWithId:(id)element;

+ (ComGoogleCommonCollectImmutableSortedSet *)ofWithId:(id)e1
                                                withId:(id)e2;

+ (ComGoogleCommonCollectImmutableSortedSet *)ofWithId:(id)e1
                                                withId:(id)e2
                                                withId:(id)e3;

+ (ComGoogleCommonCollectImmutableSortedSet *)ofWithId:(id)e1
                                                withId:(id)e2
                                                withId:(id)e3
                                                withId:(id)e4;

+ (ComGoogleCommonCollectImmutableSortedSet *)ofWithId:(id)e1
                                                withId:(id)e2
                                                withId:(id)e3
                                                withId:(id)e4
                                                withId:(id)e5;

+ (ComGoogleCommonCollectImmutableSortedSet *)ofWithId:(id)e1
                                                withId:(id)e2
                                                withId:(id)e3
                                                withId:(id)e4
                                                withId:(id)e5
                                                withId:(id)e6
                                     withNSObjectArray:(IOSObjectArray *)remaining;

+ (ComGoogleCommonCollectImmutableSortedSet *)copyOfWithNSObjectArray:(IOSObjectArray *)elements OBJC_METHOD_FAMILY_NONE;

- (instancetype)init;


@end

J2OBJC_EMPTY_STATIC_INIT(ComGoogleCommonCollectImmutableSortedSetFauxverideShim)

CF_EXTERN_C_BEGIN

FOUNDATION_EXPORT ComGoogleCommonCollectImmutableSortedSet_Builder *ComGoogleCommonCollectImmutableSortedSetFauxverideShim_builder();

FOUNDATION_EXPORT ComGoogleCommonCollectImmutableSortedSet *ComGoogleCommonCollectImmutableSortedSetFauxverideShim_ofWithId_(id element);

FOUNDATION_EXPORT ComGoogleCommonCollectImmutableSortedSet *ComGoogleCommonCollectImmutableSortedSetFauxverideShim_ofWithId_withId_(id e1, id e2);

FOUNDATION_EXPORT ComGoogleCommonCollectImmutableSortedSet *ComGoogleCommonCollectImmutableSortedSetFauxverideShim_ofWithId_withId_withId_(id e1, id e2, id e3);

FOUNDATION_EXPORT ComGoogleCommonCollectImmutableSortedSet *ComGoogleCommonCollectImmutableSortedSetFauxverideShim_ofWithId_withId_withId_withId_(id e1, id e2, id e3, id e4);

FOUNDATION_EXPORT ComGoogleCommonCollectImmutableSortedSet *ComGoogleCommonCollectImmutableSortedSetFauxverideShim_ofWithId_withId_withId_withId_withId_(id e1, id e2, id e3, id e4, id e5);

FOUNDATION_EXPORT ComGoogleCommonCollectImmutableSortedSet *ComGoogleCommonCollectImmutableSortedSetFauxverideShim_ofWithId_withId_withId_withId_withId_withId_withNSObjectArray_(id e1, id e2, id e3, id e4, id e5, id e6, IOSObjectArray *remaining);

FOUNDATION_EXPORT ComGoogleCommonCollectImmutableSortedSet *ComGoogleCommonCollectImmutableSortedSetFauxverideShim_copyOfWithNSObjectArray_(IOSObjectArray *elements);
CF_EXTERN_C_END
#endif

J2OBJC_TYPE_LITERAL_HEADER(ComGoogleCommonCollectImmutableSortedSetFauxverideShim)
