//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: /Users/krasnocka/Downloads/j2objc-master/guava/sources/com/google/common/collect/Multimaps.java
//

#include "J2ObjC_header.h"

#if !ComGoogleCommonCollectMultimaps_RESTRICT
#define ComGoogleCommonCollectMultimaps_INCLUDE_ALL 1
#endif
#undef ComGoogleCommonCollectMultimaps_RESTRICT
#if ComGoogleCommonCollectMultimaps_EntrySet_INCLUDE
#define ComGoogleCommonCollectMultimaps_Entries_INCLUDE 1
#endif
#if ComGoogleCommonCollectMultimaps_TransformedEntriesListMultimap_INCLUDE
#define ComGoogleCommonCollectMultimaps_TransformedEntriesMultimap_INCLUDE 1
#endif
#if ComGoogleCommonCollectMultimaps_UnmodifiableSortedSetMultimap_INCLUDE
#define ComGoogleCommonCollectMultimaps_UnmodifiableSetMultimap_INCLUDE 1
#endif
#if ComGoogleCommonCollectMultimaps_UnmodifiableSetMultimap_INCLUDE
#define ComGoogleCommonCollectMultimaps_UnmodifiableMultimap_INCLUDE 1
#endif
#if ComGoogleCommonCollectMultimaps_UnmodifiableListMultimap_INCLUDE
#define ComGoogleCommonCollectMultimaps_UnmodifiableMultimap_INCLUDE 1
#endif
#if !defined (_ComGoogleCommonCollectMultimaps_) && (ComGoogleCommonCollectMultimaps_INCLUDE_ALL || ComGoogleCommonCollectMultimaps_INCLUDE)
#define _ComGoogleCommonCollectMultimaps_

@class ComGoogleCommonCollectFilteredMultimap;
@class ComGoogleCommonCollectImmutableListMultimap;
@class ComGoogleCommonCollectImmutableMultimap;
@class ComGoogleCommonCollectImmutableSetMultimap;
@protocol ComGoogleCommonBaseFunction;
@protocol ComGoogleCommonBasePredicate;
@protocol ComGoogleCommonBaseSupplier;
@protocol ComGoogleCommonCollectListMultimap;
@protocol ComGoogleCommonCollectMaps_EntryTransformer;
@protocol ComGoogleCommonCollectMultimap;
@protocol ComGoogleCommonCollectSetMultimap;
@protocol ComGoogleCommonCollectSortedSetMultimap;
@protocol JavaLangIterable;
@protocol JavaUtilCollection;
@protocol JavaUtilIterator;
@protocol JavaUtilMap;
@protocol JavaUtilMap_Entry;
@protocol JavaUtilSet;


@interface ComGoogleCommonCollectMultimaps : NSObject {
}

+ (id<ComGoogleCommonCollectMultimap>)newMultimapWithJavaUtilMap:(id<JavaUtilMap>)map
                                 withComGoogleCommonBaseSupplier:(id<ComGoogleCommonBaseSupplier>)factory OBJC_METHOD_FAMILY_NONE;

+ (id<ComGoogleCommonCollectListMultimap>)newListMultimapWithJavaUtilMap:(id<JavaUtilMap>)map
                                         withComGoogleCommonBaseSupplier:(id<ComGoogleCommonBaseSupplier>)factory OBJC_METHOD_FAMILY_NONE;

+ (id<ComGoogleCommonCollectSetMultimap>)newSetMultimapWithJavaUtilMap:(id<JavaUtilMap>)map
                                       withComGoogleCommonBaseSupplier:(id<ComGoogleCommonBaseSupplier>)factory OBJC_METHOD_FAMILY_NONE;

+ (id<ComGoogleCommonCollectSortedSetMultimap>)newSortedSetMultimapWithJavaUtilMap:(id<JavaUtilMap>)map
                                                   withComGoogleCommonBaseSupplier:(id<ComGoogleCommonBaseSupplier>)factory OBJC_METHOD_FAMILY_NONE;

+ (id)invertFromWithComGoogleCommonCollectMultimap:(id<ComGoogleCommonCollectMultimap>)source
                withComGoogleCommonCollectMultimap:(id<ComGoogleCommonCollectMultimap>)dest;

+ (id<ComGoogleCommonCollectMultimap>)synchronizedMultimapWithComGoogleCommonCollectMultimap:(id<ComGoogleCommonCollectMultimap>)multimap;

+ (id<ComGoogleCommonCollectMultimap>)unmodifiableMultimapWithComGoogleCommonCollectMultimap:(id<ComGoogleCommonCollectMultimap>)delegate;

+ (id<ComGoogleCommonCollectMultimap>)unmodifiableMultimapWithComGoogleCommonCollectImmutableMultimap:(ComGoogleCommonCollectImmutableMultimap *)delegate;

+ (id<ComGoogleCommonCollectSetMultimap>)synchronizedSetMultimapWithComGoogleCommonCollectSetMultimap:(id<ComGoogleCommonCollectSetMultimap>)multimap;

+ (id<ComGoogleCommonCollectSetMultimap>)unmodifiableSetMultimapWithComGoogleCommonCollectSetMultimap:(id<ComGoogleCommonCollectSetMultimap>)delegate;

+ (id<ComGoogleCommonCollectSetMultimap>)unmodifiableSetMultimapWithComGoogleCommonCollectImmutableSetMultimap:(ComGoogleCommonCollectImmutableSetMultimap *)delegate;

+ (id<ComGoogleCommonCollectSortedSetMultimap>)synchronizedSortedSetMultimapWithComGoogleCommonCollectSortedSetMultimap:(id<ComGoogleCommonCollectSortedSetMultimap>)multimap;

+ (id<ComGoogleCommonCollectSortedSetMultimap>)unmodifiableSortedSetMultimapWithComGoogleCommonCollectSortedSetMultimap:(id<ComGoogleCommonCollectSortedSetMultimap>)delegate;

+ (id<ComGoogleCommonCollectListMultimap>)synchronizedListMultimapWithComGoogleCommonCollectListMultimap:(id<ComGoogleCommonCollectListMultimap>)multimap;

+ (id<ComGoogleCommonCollectListMultimap>)unmodifiableListMultimapWithComGoogleCommonCollectListMultimap:(id<ComGoogleCommonCollectListMultimap>)delegate;

+ (id<ComGoogleCommonCollectListMultimap>)unmodifiableListMultimapWithComGoogleCommonCollectImmutableListMultimap:(ComGoogleCommonCollectImmutableListMultimap *)delegate;

+ (id<ComGoogleCommonCollectSetMultimap>)forMapWithJavaUtilMap:(id<JavaUtilMap>)map;

+ (id<ComGoogleCommonCollectMultimap>)transformValuesWithComGoogleCommonCollectMultimap:(id<ComGoogleCommonCollectMultimap>)fromMultimap
                                                        withComGoogleCommonBaseFunction:(id<ComGoogleCommonBaseFunction>)function;

+ (id<ComGoogleCommonCollectMultimap>)transformEntriesWithComGoogleCommonCollectMultimap:(id<ComGoogleCommonCollectMultimap>)fromMap
                                         withComGoogleCommonCollectMaps_EntryTransformer:(id<ComGoogleCommonCollectMaps_EntryTransformer>)transformer;

+ (id<ComGoogleCommonCollectListMultimap>)transformValuesWithComGoogleCommonCollectListMultimap:(id<ComGoogleCommonCollectListMultimap>)fromMultimap
                                                                withComGoogleCommonBaseFunction:(id<ComGoogleCommonBaseFunction>)function;

+ (id<ComGoogleCommonCollectListMultimap>)transformEntriesWithComGoogleCommonCollectListMultimap:(id<ComGoogleCommonCollectListMultimap>)fromMap
                                                 withComGoogleCommonCollectMaps_EntryTransformer:(id<ComGoogleCommonCollectMaps_EntryTransformer>)transformer;

+ (ComGoogleCommonCollectImmutableListMultimap *)indexWithJavaLangIterable:(id<JavaLangIterable>)values
                                           withComGoogleCommonBaseFunction:(id<ComGoogleCommonBaseFunction>)keyFunction;

+ (ComGoogleCommonCollectImmutableListMultimap *)indexWithJavaUtilIterator:(id<JavaUtilIterator>)values
                                           withComGoogleCommonBaseFunction:(id<ComGoogleCommonBaseFunction>)keyFunction;

+ (id<ComGoogleCommonCollectMultimap>)filterKeysWithComGoogleCommonCollectMultimap:(id<ComGoogleCommonCollectMultimap>)unfiltered
                                                  withComGoogleCommonBasePredicate:(id<ComGoogleCommonBasePredicate>)keyPredicate;

+ (id<ComGoogleCommonCollectMultimap>)filterValuesWithComGoogleCommonCollectMultimap:(id<ComGoogleCommonCollectMultimap>)unfiltered
                                                    withComGoogleCommonBasePredicate:(id<ComGoogleCommonBasePredicate>)valuePredicate;

+ (id<ComGoogleCommonCollectMultimap>)filterEntriesWithComGoogleCommonCollectMultimap:(id<ComGoogleCommonCollectMultimap>)unfiltered
                                                     withComGoogleCommonBasePredicate:(id<ComGoogleCommonBasePredicate>)entryPredicate;

@end

J2OBJC_EMPTY_STATIC_INIT(ComGoogleCommonCollectMultimaps)

CF_EXTERN_C_BEGIN

FOUNDATION_EXPORT id<ComGoogleCommonCollectMultimap> ComGoogleCommonCollectMultimaps_newMultimapWithJavaUtilMap_withComGoogleCommonBaseSupplier_(id<JavaUtilMap> map, id<ComGoogleCommonBaseSupplier> factory);

FOUNDATION_EXPORT id<ComGoogleCommonCollectListMultimap> ComGoogleCommonCollectMultimaps_newListMultimapWithJavaUtilMap_withComGoogleCommonBaseSupplier_(id<JavaUtilMap> map, id<ComGoogleCommonBaseSupplier> factory);

FOUNDATION_EXPORT id<ComGoogleCommonCollectSetMultimap> ComGoogleCommonCollectMultimaps_newSetMultimapWithJavaUtilMap_withComGoogleCommonBaseSupplier_(id<JavaUtilMap> map, id<ComGoogleCommonBaseSupplier> factory);

FOUNDATION_EXPORT id<ComGoogleCommonCollectSortedSetMultimap> ComGoogleCommonCollectMultimaps_newSortedSetMultimapWithJavaUtilMap_withComGoogleCommonBaseSupplier_(id<JavaUtilMap> map, id<ComGoogleCommonBaseSupplier> factory);

FOUNDATION_EXPORT id ComGoogleCommonCollectMultimaps_invertFromWithComGoogleCommonCollectMultimap_withComGoogleCommonCollectMultimap_(id<ComGoogleCommonCollectMultimap> source, id<ComGoogleCommonCollectMultimap> dest);

FOUNDATION_EXPORT id<ComGoogleCommonCollectMultimap> ComGoogleCommonCollectMultimaps_synchronizedMultimapWithComGoogleCommonCollectMultimap_(id<ComGoogleCommonCollectMultimap> multimap);

FOUNDATION_EXPORT id<ComGoogleCommonCollectMultimap> ComGoogleCommonCollectMultimaps_unmodifiableMultimapWithComGoogleCommonCollectMultimap_(id<ComGoogleCommonCollectMultimap> delegate);

FOUNDATION_EXPORT id<ComGoogleCommonCollectMultimap> ComGoogleCommonCollectMultimaps_unmodifiableMultimapWithComGoogleCommonCollectImmutableMultimap_(ComGoogleCommonCollectImmutableMultimap *delegate);

FOUNDATION_EXPORT id<ComGoogleCommonCollectSetMultimap> ComGoogleCommonCollectMultimaps_synchronizedSetMultimapWithComGoogleCommonCollectSetMultimap_(id<ComGoogleCommonCollectSetMultimap> multimap);

FOUNDATION_EXPORT id<ComGoogleCommonCollectSetMultimap> ComGoogleCommonCollectMultimaps_unmodifiableSetMultimapWithComGoogleCommonCollectSetMultimap_(id<ComGoogleCommonCollectSetMultimap> delegate);

FOUNDATION_EXPORT id<ComGoogleCommonCollectSetMultimap> ComGoogleCommonCollectMultimaps_unmodifiableSetMultimapWithComGoogleCommonCollectImmutableSetMultimap_(ComGoogleCommonCollectImmutableSetMultimap *delegate);

FOUNDATION_EXPORT id<ComGoogleCommonCollectSortedSetMultimap> ComGoogleCommonCollectMultimaps_synchronizedSortedSetMultimapWithComGoogleCommonCollectSortedSetMultimap_(id<ComGoogleCommonCollectSortedSetMultimap> multimap);

FOUNDATION_EXPORT id<ComGoogleCommonCollectSortedSetMultimap> ComGoogleCommonCollectMultimaps_unmodifiableSortedSetMultimapWithComGoogleCommonCollectSortedSetMultimap_(id<ComGoogleCommonCollectSortedSetMultimap> delegate);

FOUNDATION_EXPORT id<ComGoogleCommonCollectListMultimap> ComGoogleCommonCollectMultimaps_synchronizedListMultimapWithComGoogleCommonCollectListMultimap_(id<ComGoogleCommonCollectListMultimap> multimap);

FOUNDATION_EXPORT id<ComGoogleCommonCollectListMultimap> ComGoogleCommonCollectMultimaps_unmodifiableListMultimapWithComGoogleCommonCollectListMultimap_(id<ComGoogleCommonCollectListMultimap> delegate);

FOUNDATION_EXPORT id<ComGoogleCommonCollectListMultimap> ComGoogleCommonCollectMultimaps_unmodifiableListMultimapWithComGoogleCommonCollectImmutableListMultimap_(ComGoogleCommonCollectImmutableListMultimap *delegate);

FOUNDATION_EXPORT id<ComGoogleCommonCollectSetMultimap> ComGoogleCommonCollectMultimaps_forMapWithJavaUtilMap_(id<JavaUtilMap> map);

FOUNDATION_EXPORT id<ComGoogleCommonCollectMultimap> ComGoogleCommonCollectMultimaps_transformValuesWithComGoogleCommonCollectMultimap_withComGoogleCommonBaseFunction_(id<ComGoogleCommonCollectMultimap> fromMultimap, id<ComGoogleCommonBaseFunction> function);

FOUNDATION_EXPORT id<ComGoogleCommonCollectMultimap> ComGoogleCommonCollectMultimaps_transformEntriesWithComGoogleCommonCollectMultimap_withComGoogleCommonCollectMaps_EntryTransformer_(id<ComGoogleCommonCollectMultimap> fromMap, id<ComGoogleCommonCollectMaps_EntryTransformer> transformer);

FOUNDATION_EXPORT id<ComGoogleCommonCollectListMultimap> ComGoogleCommonCollectMultimaps_transformValuesWithComGoogleCommonCollectListMultimap_withComGoogleCommonBaseFunction_(id<ComGoogleCommonCollectListMultimap> fromMultimap, id<ComGoogleCommonBaseFunction> function);

FOUNDATION_EXPORT id<ComGoogleCommonCollectListMultimap> ComGoogleCommonCollectMultimaps_transformEntriesWithComGoogleCommonCollectListMultimap_withComGoogleCommonCollectMaps_EntryTransformer_(id<ComGoogleCommonCollectListMultimap> fromMap, id<ComGoogleCommonCollectMaps_EntryTransformer> transformer);

FOUNDATION_EXPORT ComGoogleCommonCollectImmutableListMultimap *ComGoogleCommonCollectMultimaps_indexWithJavaLangIterable_withComGoogleCommonBaseFunction_(id<JavaLangIterable> values, id<ComGoogleCommonBaseFunction> keyFunction);

FOUNDATION_EXPORT ComGoogleCommonCollectImmutableListMultimap *ComGoogleCommonCollectMultimaps_indexWithJavaUtilIterator_withComGoogleCommonBaseFunction_(id<JavaUtilIterator> values, id<ComGoogleCommonBaseFunction> keyFunction);

FOUNDATION_EXPORT id<ComGoogleCommonCollectMultimap> ComGoogleCommonCollectMultimaps_filterKeysWithComGoogleCommonCollectMultimap_withComGoogleCommonBasePredicate_(id<ComGoogleCommonCollectMultimap> unfiltered, id<ComGoogleCommonBasePredicate> keyPredicate);

FOUNDATION_EXPORT id<ComGoogleCommonCollectMultimap> ComGoogleCommonCollectMultimaps_filterValuesWithComGoogleCommonCollectMultimap_withComGoogleCommonBasePredicate_(id<ComGoogleCommonCollectMultimap> unfiltered, id<ComGoogleCommonBasePredicate> valuePredicate);

FOUNDATION_EXPORT id<ComGoogleCommonCollectMultimap> ComGoogleCommonCollectMultimaps_filterEntriesWithComGoogleCommonCollectMultimap_withComGoogleCommonBasePredicate_(id<ComGoogleCommonCollectMultimap> unfiltered, id<ComGoogleCommonBasePredicate> entryPredicate);
CF_EXTERN_C_END
#endif

J2OBJC_TYPE_LITERAL_HEADER(ComGoogleCommonCollectMultimaps)
#if !defined (_ComGoogleCommonCollectMultimaps_CustomMultimap_) && (ComGoogleCommonCollectMultimaps_INCLUDE_ALL || ComGoogleCommonCollectMultimaps_CustomMultimap_INCLUDE)
#define _ComGoogleCommonCollectMultimaps_CustomMultimap_

@class JavaIoObjectInputStream;
@class JavaIoObjectOutputStream;
@protocol ComGoogleCommonBaseSupplier;
@protocol JavaUtilCollection;
@protocol JavaUtilMap;

#define ComGoogleCommonCollectAbstractMapBasedMultimap_RESTRICT 1
#define ComGoogleCommonCollectAbstractMapBasedMultimap_INCLUDE 1
#include "com/google/common/collect/AbstractMapBasedMultimap.h"


#define ComGoogleCommonCollectMultimaps_CustomMultimap_serialVersionUID 0LL

@interface ComGoogleCommonCollectMultimaps_CustomMultimap : ComGoogleCommonCollectAbstractMapBasedMultimap {
 @public
  id<ComGoogleCommonBaseSupplier> factory_;
}

- (instancetype)initWithJavaUtilMap:(id<JavaUtilMap>)map
    withComGoogleCommonBaseSupplier:(id<ComGoogleCommonBaseSupplier>)factory;

- (id<JavaUtilCollection>)createCollection;

@end

J2OBJC_EMPTY_STATIC_INIT(ComGoogleCommonCollectMultimaps_CustomMultimap)

J2OBJC_FIELD_SETTER(ComGoogleCommonCollectMultimaps_CustomMultimap, factory_, id<ComGoogleCommonBaseSupplier>)

CF_EXTERN_C_BEGIN

J2OBJC_STATIC_FIELD_GETTER(ComGoogleCommonCollectMultimaps_CustomMultimap, serialVersionUID, jlong)
CF_EXTERN_C_END
#endif

J2OBJC_TYPE_LITERAL_HEADER(ComGoogleCommonCollectMultimaps_CustomMultimap)
#if !defined (_ComGoogleCommonCollectMultimaps_CustomListMultimap_) && (ComGoogleCommonCollectMultimaps_INCLUDE_ALL || ComGoogleCommonCollectMultimaps_CustomListMultimap_INCLUDE)
#define _ComGoogleCommonCollectMultimaps_CustomListMultimap_

@class JavaIoObjectInputStream;
@class JavaIoObjectOutputStream;
@protocol ComGoogleCommonBaseSupplier;
@protocol JavaUtilList;
@protocol JavaUtilMap;

#define ComGoogleCommonCollectAbstractListMultimap_RESTRICT 1
#define ComGoogleCommonCollectAbstractListMultimap_INCLUDE 1
#include "com/google/common/collect/AbstractListMultimap.h"


#define ComGoogleCommonCollectMultimaps_CustomListMultimap_serialVersionUID 0LL

@interface ComGoogleCommonCollectMultimaps_CustomListMultimap : ComGoogleCommonCollectAbstractListMultimap {
 @public
  id<ComGoogleCommonBaseSupplier> factory_;
}

- (instancetype)initWithJavaUtilMap:(id<JavaUtilMap>)map
    withComGoogleCommonBaseSupplier:(id<ComGoogleCommonBaseSupplier>)factory;

- (id<JavaUtilList>)createCollection;

@end

J2OBJC_EMPTY_STATIC_INIT(ComGoogleCommonCollectMultimaps_CustomListMultimap)

J2OBJC_FIELD_SETTER(ComGoogleCommonCollectMultimaps_CustomListMultimap, factory_, id<ComGoogleCommonBaseSupplier>)

CF_EXTERN_C_BEGIN

J2OBJC_STATIC_FIELD_GETTER(ComGoogleCommonCollectMultimaps_CustomListMultimap, serialVersionUID, jlong)
CF_EXTERN_C_END
#endif

J2OBJC_TYPE_LITERAL_HEADER(ComGoogleCommonCollectMultimaps_CustomListMultimap)
#if !defined (_ComGoogleCommonCollectMultimaps_CustomSetMultimap_) && (ComGoogleCommonCollectMultimaps_INCLUDE_ALL || ComGoogleCommonCollectMultimaps_CustomSetMultimap_INCLUDE)
#define _ComGoogleCommonCollectMultimaps_CustomSetMultimap_

@class JavaIoObjectInputStream;
@class JavaIoObjectOutputStream;
@protocol ComGoogleCommonBaseSupplier;
@protocol JavaUtilMap;
@protocol JavaUtilSet;

#define ComGoogleCommonCollectAbstractSetMultimap_RESTRICT 1
#define ComGoogleCommonCollectAbstractSetMultimap_INCLUDE 1
#include "com/google/common/collect/AbstractSetMultimap.h"


#define ComGoogleCommonCollectMultimaps_CustomSetMultimap_serialVersionUID 0LL

@interface ComGoogleCommonCollectMultimaps_CustomSetMultimap : ComGoogleCommonCollectAbstractSetMultimap {
 @public
  id<ComGoogleCommonBaseSupplier> factory_;
}

- (instancetype)initWithJavaUtilMap:(id<JavaUtilMap>)map
    withComGoogleCommonBaseSupplier:(id<ComGoogleCommonBaseSupplier>)factory;

- (id<JavaUtilSet>)createCollection;

@end

J2OBJC_EMPTY_STATIC_INIT(ComGoogleCommonCollectMultimaps_CustomSetMultimap)

J2OBJC_FIELD_SETTER(ComGoogleCommonCollectMultimaps_CustomSetMultimap, factory_, id<ComGoogleCommonBaseSupplier>)

CF_EXTERN_C_BEGIN

J2OBJC_STATIC_FIELD_GETTER(ComGoogleCommonCollectMultimaps_CustomSetMultimap, serialVersionUID, jlong)
CF_EXTERN_C_END
#endif

J2OBJC_TYPE_LITERAL_HEADER(ComGoogleCommonCollectMultimaps_CustomSetMultimap)
#if !defined (_ComGoogleCommonCollectMultimaps_CustomSortedSetMultimap_) && (ComGoogleCommonCollectMultimaps_INCLUDE_ALL || ComGoogleCommonCollectMultimaps_CustomSortedSetMultimap_INCLUDE)
#define _ComGoogleCommonCollectMultimaps_CustomSortedSetMultimap_

@class JavaIoObjectInputStream;
@class JavaIoObjectOutputStream;
@protocol ComGoogleCommonBaseSupplier;
@protocol JavaUtilComparator;
@protocol JavaUtilMap;
@protocol JavaUtilSortedSet;

#define ComGoogleCommonCollectAbstractSortedSetMultimap_RESTRICT 1
#define ComGoogleCommonCollectAbstractSortedSetMultimap_INCLUDE 1
#include "com/google/common/collect/AbstractSortedSetMultimap.h"


#define ComGoogleCommonCollectMultimaps_CustomSortedSetMultimap_serialVersionUID 0LL

@interface ComGoogleCommonCollectMultimaps_CustomSortedSetMultimap : ComGoogleCommonCollectAbstractSortedSetMultimap {
 @public
  id<ComGoogleCommonBaseSupplier> factory_;
  id<JavaUtilComparator> valueComparator__;
}

- (instancetype)initWithJavaUtilMap:(id<JavaUtilMap>)map
    withComGoogleCommonBaseSupplier:(id<ComGoogleCommonBaseSupplier>)factory;

- (id<JavaUtilSortedSet>)createCollection;

- (id<JavaUtilComparator>)valueComparator;

@end

J2OBJC_EMPTY_STATIC_INIT(ComGoogleCommonCollectMultimaps_CustomSortedSetMultimap)

J2OBJC_FIELD_SETTER(ComGoogleCommonCollectMultimaps_CustomSortedSetMultimap, factory_, id<ComGoogleCommonBaseSupplier>)
J2OBJC_FIELD_SETTER(ComGoogleCommonCollectMultimaps_CustomSortedSetMultimap, valueComparator__, id<JavaUtilComparator>)

CF_EXTERN_C_BEGIN

J2OBJC_STATIC_FIELD_GETTER(ComGoogleCommonCollectMultimaps_CustomSortedSetMultimap, serialVersionUID, jlong)
CF_EXTERN_C_END
#endif

J2OBJC_TYPE_LITERAL_HEADER(ComGoogleCommonCollectMultimaps_CustomSortedSetMultimap)
#if !defined (_ComGoogleCommonCollectMultimaps_UnmodifiableMultimap_$1_) && (ComGoogleCommonCollectMultimaps_INCLUDE_ALL || ComGoogleCommonCollectMultimaps_UnmodifiableMultimap_$1_INCLUDE)
#define _ComGoogleCommonCollectMultimaps_UnmodifiableMultimap_$1_

@protocol JavaUtilCollection;
@protocol JavaUtilMap;
@protocol JavaUtilSet;

#define ComGoogleCommonCollectForwardingMap_RESTRICT 1
#define ComGoogleCommonCollectForwardingMap_INCLUDE 1
#include "com/google/common/collect/ForwardingMap.h"


@interface ComGoogleCommonCollectMultimaps_UnmodifiableMultimap_$1 : ComGoogleCommonCollectForwardingMap {
 @public
  id<JavaUtilSet> entrySet__;
  id<JavaUtilCollection> asMapValues_;
}

- (id<JavaUtilMap>)delegate;

- (id<JavaUtilSet>)entrySet;

- (id<JavaUtilCollection>)getWithId:(id)key;

- (id<JavaUtilCollection>)values;

- (jboolean)containsValueWithId:(id)o;

- (instancetype)initWithJavaUtilMap:(id<JavaUtilMap>)capture$0;

@end

J2OBJC_EMPTY_STATIC_INIT(ComGoogleCommonCollectMultimaps_UnmodifiableMultimap_$1)

J2OBJC_FIELD_SETTER(ComGoogleCommonCollectMultimaps_UnmodifiableMultimap_$1, entrySet__, id<JavaUtilSet>)
J2OBJC_FIELD_SETTER(ComGoogleCommonCollectMultimaps_UnmodifiableMultimap_$1, asMapValues_, id<JavaUtilCollection>)

CF_EXTERN_C_BEGIN
CF_EXTERN_C_END
#endif

J2OBJC_TYPE_LITERAL_HEADER(ComGoogleCommonCollectMultimaps_UnmodifiableMultimap_$1)
#if !defined (_ComGoogleCommonCollectMultimaps_UnmodifiableAsMapValues_) && (ComGoogleCommonCollectMultimaps_INCLUDE_ALL || ComGoogleCommonCollectMultimaps_UnmodifiableAsMapValues_INCLUDE)
#define _ComGoogleCommonCollectMultimaps_UnmodifiableAsMapValues_

@class IOSObjectArray;
@protocol JavaUtilCollection;
@protocol JavaUtilIterator;

#define ComGoogleCommonCollectForwardingCollection_RESTRICT 1
#define ComGoogleCommonCollectForwardingCollection_INCLUDE 1
#include "com/google/common/collect/ForwardingCollection.h"


@interface ComGoogleCommonCollectMultimaps_UnmodifiableAsMapValues : ComGoogleCommonCollectForwardingCollection {
 @public
  id<JavaUtilCollection> delegate__;
}

- (instancetype)initWithJavaUtilCollection:(id<JavaUtilCollection>)delegate;

- (id<JavaUtilCollection>)delegate;

- (id<JavaUtilIterator>)iterator;

- (IOSObjectArray *)toArray;

- (IOSObjectArray *)toArrayWithNSObjectArray:(IOSObjectArray *)array;

- (jboolean)containsWithId:(id)o;

- (jboolean)containsAllWithJavaUtilCollection:(id<JavaUtilCollection>)c;


@end

J2OBJC_EMPTY_STATIC_INIT(ComGoogleCommonCollectMultimaps_UnmodifiableAsMapValues)

J2OBJC_FIELD_SETTER(ComGoogleCommonCollectMultimaps_UnmodifiableAsMapValues, delegate__, id<JavaUtilCollection>)

CF_EXTERN_C_BEGIN
CF_EXTERN_C_END
#endif

J2OBJC_TYPE_LITERAL_HEADER(ComGoogleCommonCollectMultimaps_UnmodifiableAsMapValues)
#if !defined (_ComGoogleCommonCollectMultimaps_UnmodifiableAsMapValues_$1_) && (ComGoogleCommonCollectMultimaps_INCLUDE_ALL || ComGoogleCommonCollectMultimaps_UnmodifiableAsMapValues_$1_INCLUDE)
#define _ComGoogleCommonCollectMultimaps_UnmodifiableAsMapValues_$1_

@protocol JavaUtilCollection;
@protocol JavaUtilIterator;

#define ComGoogleCommonCollectUnmodifiableIterator_RESTRICT 1
#define ComGoogleCommonCollectUnmodifiableIterator_INCLUDE 1
#include "com/google/common/collect/UnmodifiableIterator.h"


@interface ComGoogleCommonCollectMultimaps_UnmodifiableAsMapValues_$1 : ComGoogleCommonCollectUnmodifiableIterator {
}

- (jboolean)hasNext;

- (id<JavaUtilCollection>)next;

- (instancetype)initWithJavaUtilIterator:(id<JavaUtilIterator>)capture$0;

@end

J2OBJC_EMPTY_STATIC_INIT(ComGoogleCommonCollectMultimaps_UnmodifiableAsMapValues_$1)

CF_EXTERN_C_BEGIN
CF_EXTERN_C_END
#endif

J2OBJC_TYPE_LITERAL_HEADER(ComGoogleCommonCollectMultimaps_UnmodifiableAsMapValues_$1)
#if !defined (_ComGoogleCommonCollectMultimaps_UnmodifiableMultimap_) && (ComGoogleCommonCollectMultimaps_INCLUDE_ALL || ComGoogleCommonCollectMultimaps_UnmodifiableMultimap_INCLUDE)
#define _ComGoogleCommonCollectMultimaps_UnmodifiableMultimap_

@protocol ComGoogleCommonCollectMultimap;
@protocol ComGoogleCommonCollectMultiset;
@protocol JavaLangIterable;
@protocol JavaUtilCollection;
@protocol JavaUtilMap;
@protocol JavaUtilSet;

#define ComGoogleCommonCollectForwardingMultimap_RESTRICT 1
#define ComGoogleCommonCollectForwardingMultimap_INCLUDE 1
#include "com/google/common/collect/ForwardingMultimap.h"

#define JavaIoSerializable_RESTRICT 1
#define JavaIoSerializable_INCLUDE 1
#include "java/io/Serializable.h"


#define ComGoogleCommonCollectMultimaps_UnmodifiableMultimap_serialVersionUID 0LL

@interface ComGoogleCommonCollectMultimaps_UnmodifiableMultimap : ComGoogleCommonCollectForwardingMultimap < JavaIoSerializable > {
 @public
  id<ComGoogleCommonCollectMultimap> delegate__;
  id<JavaUtilCollection> entries__;
  id<ComGoogleCommonCollectMultiset> keys__;
  id<JavaUtilSet> keySet__;
  id<JavaUtilCollection> values__;
  id<JavaUtilMap> map_;
}

- (instancetype)initWithComGoogleCommonCollectMultimap:(id<ComGoogleCommonCollectMultimap>)delegate;

- (id<ComGoogleCommonCollectMultimap>)delegate;

- (void)clear;

- (id<JavaUtilMap>)asMap;

- (id<JavaUtilCollection>)entries;

- (id<JavaUtilCollection>)getWithId:(id)key;

- (id<ComGoogleCommonCollectMultiset>)keys;

- (id<JavaUtilSet>)keySet;

- (jboolean)putWithId:(id)key
               withId:(id)value;

- (jboolean)putAllWithId:(id)key
    withJavaLangIterable:(id<JavaLangIterable>)values;

- (jboolean)putAllWithComGoogleCommonCollectMultimap:(id<ComGoogleCommonCollectMultimap>)multimap;

- (jboolean)removeWithId:(id)key
                  withId:(id)value;

- (id<JavaUtilCollection>)removeAllWithId:(id)key;

- (id<JavaUtilCollection>)replaceValuesWithId:(id)key
                         withJavaLangIterable:(id<JavaLangIterable>)values;

- (id<JavaUtilCollection>)values;

@end

J2OBJC_EMPTY_STATIC_INIT(ComGoogleCommonCollectMultimaps_UnmodifiableMultimap)

J2OBJC_FIELD_SETTER(ComGoogleCommonCollectMultimaps_UnmodifiableMultimap, delegate__, id<ComGoogleCommonCollectMultimap>)
J2OBJC_FIELD_SETTER(ComGoogleCommonCollectMultimaps_UnmodifiableMultimap, entries__, id<JavaUtilCollection>)
J2OBJC_FIELD_SETTER(ComGoogleCommonCollectMultimaps_UnmodifiableMultimap, keys__, id<ComGoogleCommonCollectMultiset>)
J2OBJC_FIELD_SETTER(ComGoogleCommonCollectMultimaps_UnmodifiableMultimap, keySet__, id<JavaUtilSet>)
J2OBJC_FIELD_SETTER(ComGoogleCommonCollectMultimaps_UnmodifiableMultimap, values__, id<JavaUtilCollection>)
J2OBJC_FIELD_SETTER(ComGoogleCommonCollectMultimaps_UnmodifiableMultimap, map_, id<JavaUtilMap>)

CF_EXTERN_C_BEGIN

J2OBJC_STATIC_FIELD_GETTER(ComGoogleCommonCollectMultimaps_UnmodifiableMultimap, serialVersionUID, jlong)
CF_EXTERN_C_END
#endif

J2OBJC_TYPE_LITERAL_HEADER(ComGoogleCommonCollectMultimaps_UnmodifiableMultimap)
#if !defined (_ComGoogleCommonCollectMultimaps_UnmodifiableListMultimap_) && (ComGoogleCommonCollectMultimaps_INCLUDE_ALL || ComGoogleCommonCollectMultimaps_UnmodifiableListMultimap_INCLUDE)
#define _ComGoogleCommonCollectMultimaps_UnmodifiableListMultimap_

@protocol JavaLangIterable;
@protocol JavaUtilList;

#define ComGoogleCommonCollectListMultimap_RESTRICT 1
#define ComGoogleCommonCollectListMultimap_INCLUDE 1
#include "com/google/common/collect/ListMultimap.h"


#define ComGoogleCommonCollectMultimaps_UnmodifiableListMultimap_serialVersionUID 0LL

@interface ComGoogleCommonCollectMultimaps_UnmodifiableListMultimap : ComGoogleCommonCollectMultimaps_UnmodifiableMultimap < ComGoogleCommonCollectListMultimap > {
}

- (instancetype)initWithComGoogleCommonCollectListMultimap:(id<ComGoogleCommonCollectListMultimap>)delegate;

- (id<ComGoogleCommonCollectListMultimap>)delegate;

- (id<JavaUtilList>)getWithId:(id)key;

- (id<JavaUtilList>)removeAllWithId:(id)key;

- (id<JavaUtilList>)replaceValuesWithId:(id)key
                   withJavaLangIterable:(id<JavaLangIterable>)values;

@end

J2OBJC_EMPTY_STATIC_INIT(ComGoogleCommonCollectMultimaps_UnmodifiableListMultimap)

CF_EXTERN_C_BEGIN

J2OBJC_STATIC_FIELD_GETTER(ComGoogleCommonCollectMultimaps_UnmodifiableListMultimap, serialVersionUID, jlong)
CF_EXTERN_C_END
#endif

J2OBJC_TYPE_LITERAL_HEADER(ComGoogleCommonCollectMultimaps_UnmodifiableListMultimap)
#if !defined (_ComGoogleCommonCollectMultimaps_UnmodifiableSetMultimap_) && (ComGoogleCommonCollectMultimaps_INCLUDE_ALL || ComGoogleCommonCollectMultimaps_UnmodifiableSetMultimap_INCLUDE)
#define _ComGoogleCommonCollectMultimaps_UnmodifiableSetMultimap_

@protocol JavaLangIterable;
@protocol JavaUtilSet;

#define ComGoogleCommonCollectSetMultimap_RESTRICT 1
#define ComGoogleCommonCollectSetMultimap_INCLUDE 1
#include "com/google/common/collect/SetMultimap.h"


#define ComGoogleCommonCollectMultimaps_UnmodifiableSetMultimap_serialVersionUID 0LL

@interface ComGoogleCommonCollectMultimaps_UnmodifiableSetMultimap : ComGoogleCommonCollectMultimaps_UnmodifiableMultimap < ComGoogleCommonCollectSetMultimap > {
}

- (instancetype)initWithComGoogleCommonCollectSetMultimap:(id<ComGoogleCommonCollectSetMultimap>)delegate;

- (id<ComGoogleCommonCollectSetMultimap>)delegate;

- (id<JavaUtilSet>)getWithId:(id)key;

- (id<JavaUtilSet>)entries;

- (id<JavaUtilSet>)removeAllWithId:(id)key;

- (id<JavaUtilSet>)replaceValuesWithId:(id)key
                  withJavaLangIterable:(id<JavaLangIterable>)values;

@end

J2OBJC_EMPTY_STATIC_INIT(ComGoogleCommonCollectMultimaps_UnmodifiableSetMultimap)

CF_EXTERN_C_BEGIN

J2OBJC_STATIC_FIELD_GETTER(ComGoogleCommonCollectMultimaps_UnmodifiableSetMultimap, serialVersionUID, jlong)
CF_EXTERN_C_END
#endif

J2OBJC_TYPE_LITERAL_HEADER(ComGoogleCommonCollectMultimaps_UnmodifiableSetMultimap)
#if !defined (_ComGoogleCommonCollectMultimaps_UnmodifiableSortedSetMultimap_) && (ComGoogleCommonCollectMultimaps_INCLUDE_ALL || ComGoogleCommonCollectMultimaps_UnmodifiableSortedSetMultimap_INCLUDE)
#define _ComGoogleCommonCollectMultimaps_UnmodifiableSortedSetMultimap_

@protocol JavaLangIterable;
@protocol JavaUtilComparator;
@protocol JavaUtilSortedSet;

#define ComGoogleCommonCollectSortedSetMultimap_RESTRICT 1
#define ComGoogleCommonCollectSortedSetMultimap_INCLUDE 1
#include "com/google/common/collect/SortedSetMultimap.h"


#define ComGoogleCommonCollectMultimaps_UnmodifiableSortedSetMultimap_serialVersionUID 0LL

@interface ComGoogleCommonCollectMultimaps_UnmodifiableSortedSetMultimap : ComGoogleCommonCollectMultimaps_UnmodifiableSetMultimap < ComGoogleCommonCollectSortedSetMultimap > {
}

- (instancetype)initWithComGoogleCommonCollectSortedSetMultimap:(id<ComGoogleCommonCollectSortedSetMultimap>)delegate;

- (id<ComGoogleCommonCollectSortedSetMultimap>)delegate;

- (id<JavaUtilSortedSet>)getWithId:(id)key;

- (id<JavaUtilSortedSet>)removeAllWithId:(id)key;

- (id<JavaUtilSortedSet>)replaceValuesWithId:(id)key
                        withJavaLangIterable:(id<JavaLangIterable>)values;

- (id<JavaUtilComparator>)valueComparator;

@end

J2OBJC_EMPTY_STATIC_INIT(ComGoogleCommonCollectMultimaps_UnmodifiableSortedSetMultimap)

CF_EXTERN_C_BEGIN

J2OBJC_STATIC_FIELD_GETTER(ComGoogleCommonCollectMultimaps_UnmodifiableSortedSetMultimap, serialVersionUID, jlong)
CF_EXTERN_C_END
#endif

J2OBJC_TYPE_LITERAL_HEADER(ComGoogleCommonCollectMultimaps_UnmodifiableSortedSetMultimap)
#if !defined (_ComGoogleCommonCollectMultimaps_UnmodifiableAsMapEntries_) && (ComGoogleCommonCollectMultimaps_INCLUDE_ALL || ComGoogleCommonCollectMultimaps_UnmodifiableAsMapEntries_INCLUDE)
#define _ComGoogleCommonCollectMultimaps_UnmodifiableAsMapEntries_

@class IOSObjectArray;
@protocol JavaUtilCollection;
@protocol JavaUtilIterator;
@protocol JavaUtilSet;

#define ComGoogleCommonCollectForwardingSet_RESTRICT 1
#define ComGoogleCommonCollectForwardingSet_INCLUDE 1
#include "com/google/common/collect/ForwardingSet.h"


@interface ComGoogleCommonCollectMultimaps_UnmodifiableAsMapEntries : ComGoogleCommonCollectForwardingSet {
}

- (instancetype)initWithJavaUtilSet:(id<JavaUtilSet>)delegate;

- (id<JavaUtilSet>)delegate;

- (id<JavaUtilIterator>)iterator;

- (IOSObjectArray *)toArray;

- (IOSObjectArray *)toArrayWithNSObjectArray:(IOSObjectArray *)array;

- (jboolean)containsWithId:(id)o;

- (jboolean)containsAllWithJavaUtilCollection:(id<JavaUtilCollection>)c;

- (jboolean)isEqual:(id)object;


@end

J2OBJC_EMPTY_STATIC_INIT(ComGoogleCommonCollectMultimaps_UnmodifiableAsMapEntries)

CF_EXTERN_C_BEGIN
CF_EXTERN_C_END
#endif

J2OBJC_TYPE_LITERAL_HEADER(ComGoogleCommonCollectMultimaps_UnmodifiableAsMapEntries)
#if !defined (_ComGoogleCommonCollectMultimaps_UnmodifiableAsMapEntries_$1_) && (ComGoogleCommonCollectMultimaps_INCLUDE_ALL || ComGoogleCommonCollectMultimaps_UnmodifiableAsMapEntries_$1_INCLUDE)
#define _ComGoogleCommonCollectMultimaps_UnmodifiableAsMapEntries_$1_

@protocol JavaUtilIterator;
@protocol JavaUtilMap_Entry;

#define ComGoogleCommonCollectForwardingIterator_RESTRICT 1
#define ComGoogleCommonCollectForwardingIterator_INCLUDE 1
#include "com/google/common/collect/ForwardingIterator.h"


@interface ComGoogleCommonCollectMultimaps_UnmodifiableAsMapEntries_$1 : ComGoogleCommonCollectForwardingIterator {
}

- (id<JavaUtilIterator>)delegate;

- (id<JavaUtilMap_Entry>)next;

- (instancetype)initWithJavaUtilIterator:(id<JavaUtilIterator>)capture$0;

@end

J2OBJC_EMPTY_STATIC_INIT(ComGoogleCommonCollectMultimaps_UnmodifiableAsMapEntries_$1)

CF_EXTERN_C_BEGIN
CF_EXTERN_C_END
#endif

J2OBJC_TYPE_LITERAL_HEADER(ComGoogleCommonCollectMultimaps_UnmodifiableAsMapEntries_$1)
#if !defined (_ComGoogleCommonCollectMultimaps_MapMultimap_) && (ComGoogleCommonCollectMultimaps_INCLUDE_ALL || ComGoogleCommonCollectMultimaps_MapMultimap_INCLUDE)
#define _ComGoogleCommonCollectMultimaps_MapMultimap_

@class ComGoogleCommonBaseJoiner_MapJoiner;
@protocol ComGoogleCommonCollectMultimap;
@protocol ComGoogleCommonCollectMultiset;
@protocol JavaLangIterable;
@protocol JavaUtilCollection;
@protocol JavaUtilMap;
@protocol JavaUtilSet;

#define ComGoogleCommonCollectSetMultimap_RESTRICT 1
#define ComGoogleCommonCollectSetMultimap_INCLUDE 1
#include "com/google/common/collect/SetMultimap.h"

#define JavaIoSerializable_RESTRICT 1
#define JavaIoSerializable_INCLUDE 1
#include "java/io/Serializable.h"


#define ComGoogleCommonCollectMultimaps_MapMultimap_serialVersionUID 7845222491160860175LL

@interface ComGoogleCommonCollectMultimaps_MapMultimap : NSObject < ComGoogleCommonCollectSetMultimap, JavaIoSerializable > {
 @public
  id<JavaUtilMap> map_;
  id<JavaUtilMap> asMap__;
}

- (instancetype)initWithJavaUtilMap:(id<JavaUtilMap>)map;

- (jint)size;

- (jboolean)isEmpty;

- (jboolean)containsKeyWithId:(id)key;

- (jboolean)containsValueWithId:(id)value;

- (jboolean)containsEntryWithId:(id)key
                         withId:(id)value;

- (id<JavaUtilSet>)getWithId:(id)key;

- (jboolean)putWithId:(id)key
               withId:(id)value;

- (jboolean)putAllWithId:(id)key
    withJavaLangIterable:(id<JavaLangIterable>)values;

- (jboolean)putAllWithComGoogleCommonCollectMultimap:(id<ComGoogleCommonCollectMultimap>)multimap;

- (id<JavaUtilSet>)replaceValuesWithId:(id)key
                  withJavaLangIterable:(id<JavaLangIterable>)values;

- (jboolean)removeWithId:(id)key
                  withId:(id)value;

- (id<JavaUtilSet>)removeAllWithId:(id)key;

- (void)clear;

- (id<JavaUtilSet>)keySet;

- (id<ComGoogleCommonCollectMultiset>)keys;

- (id<JavaUtilCollection>)values;

- (id<JavaUtilSet>)entries;

- (id<JavaUtilMap>)asMap;

- (jboolean)isEqual:(id)object;

- (NSUInteger)hash;

- (NSString *)description;

@end

FOUNDATION_EXPORT BOOL ComGoogleCommonCollectMultimaps_MapMultimap_initialized;
J2OBJC_STATIC_INIT(ComGoogleCommonCollectMultimaps_MapMultimap)

J2OBJC_FIELD_SETTER(ComGoogleCommonCollectMultimaps_MapMultimap, map_, id<JavaUtilMap>)
J2OBJC_FIELD_SETTER(ComGoogleCommonCollectMultimaps_MapMultimap, asMap__, id<JavaUtilMap>)

CF_EXTERN_C_BEGIN

FOUNDATION_EXPORT ComGoogleCommonBaseJoiner_MapJoiner *ComGoogleCommonCollectMultimaps_MapMultimap_JOINER_;
J2OBJC_STATIC_FIELD_GETTER(ComGoogleCommonCollectMultimaps_MapMultimap, JOINER_, ComGoogleCommonBaseJoiner_MapJoiner *)

J2OBJC_STATIC_FIELD_GETTER(ComGoogleCommonCollectMultimaps_MapMultimap, serialVersionUID, jlong)
CF_EXTERN_C_END
#endif

J2OBJC_TYPE_LITERAL_HEADER(ComGoogleCommonCollectMultimaps_MapMultimap)
#if !defined (_ComGoogleCommonCollectMultimaps_MapMultimap_AsMapEntries_) && (ComGoogleCommonCollectMultimaps_INCLUDE_ALL || ComGoogleCommonCollectMultimaps_MapMultimap_AsMapEntries_INCLUDE)
#define _ComGoogleCommonCollectMultimaps_MapMultimap_AsMapEntries_

@class ComGoogleCommonCollectMultimaps_MapMultimap;
@protocol JavaUtilIterator;

#define ComGoogleCommonCollectSets_RESTRICT 1
#define ComGoogleCommonCollectSets_ImprovedAbstractSet_INCLUDE 1
#include "com/google/common/collect/Sets.h"


@interface ComGoogleCommonCollectMultimaps_MapMultimap_AsMapEntries : ComGoogleCommonCollectSets_ImprovedAbstractSet {
}

- (jint)size;

- (id<JavaUtilIterator>)iterator;

- (jboolean)containsWithId:(id)o;

- (jboolean)removeWithId:(id)o;

- (instancetype)initWithComGoogleCommonCollectMultimaps_MapMultimap:(ComGoogleCommonCollectMultimaps_MapMultimap *)outer$;


@end

J2OBJC_EMPTY_STATIC_INIT(ComGoogleCommonCollectMultimaps_MapMultimap_AsMapEntries)

CF_EXTERN_C_BEGIN
CF_EXTERN_C_END
#endif

J2OBJC_TYPE_LITERAL_HEADER(ComGoogleCommonCollectMultimaps_MapMultimap_AsMapEntries)
#if !defined (_ComGoogleCommonCollectMultimaps_MapMultimap_AsMapEntries_$1_) && (ComGoogleCommonCollectMultimaps_INCLUDE_ALL || ComGoogleCommonCollectMultimaps_MapMultimap_AsMapEntries_$1_INCLUDE)
#define _ComGoogleCommonCollectMultimaps_MapMultimap_AsMapEntries_$1_

@class ComGoogleCommonCollectMultimaps_MapMultimap_AsMapEntries;
@protocol JavaUtilIterator;
@protocol JavaUtilMap_Entry;

#define ComGoogleCommonCollectTransformedIterator_RESTRICT 1
#define ComGoogleCommonCollectTransformedIterator_INCLUDE 1
#include "com/google/common/collect/TransformedIterator.h"


@interface ComGoogleCommonCollectMultimaps_MapMultimap_AsMapEntries_$1 : ComGoogleCommonCollectTransformedIterator {
}

- (id<JavaUtilMap_Entry>)transformWithId:(id)key;

- (instancetype)initWithComGoogleCommonCollectMultimaps_MapMultimap_AsMapEntries:(ComGoogleCommonCollectMultimaps_MapMultimap_AsMapEntries *)outer$
                                                            withJavaUtilIterator:(id<JavaUtilIterator>)arg$0;

@end

J2OBJC_EMPTY_STATIC_INIT(ComGoogleCommonCollectMultimaps_MapMultimap_AsMapEntries_$1)

CF_EXTERN_C_BEGIN
CF_EXTERN_C_END
#endif

J2OBJC_TYPE_LITERAL_HEADER(ComGoogleCommonCollectMultimaps_MapMultimap_AsMapEntries_$1)
#if !defined (_ComGoogleCommonCollectMultimaps_MapMultimap_AsMapEntries_$1_$1_) && (ComGoogleCommonCollectMultimaps_INCLUDE_ALL || ComGoogleCommonCollectMultimaps_MapMultimap_AsMapEntries_$1_$1_INCLUDE)
#define _ComGoogleCommonCollectMultimaps_MapMultimap_AsMapEntries_$1_$1_

@class ComGoogleCommonCollectMultimaps_MapMultimap_AsMapEntries_$1;
@protocol JavaUtilCollection;

#define ComGoogleCommonCollectAbstractMapEntry_RESTRICT 1
#define ComGoogleCommonCollectAbstractMapEntry_INCLUDE 1
#include "com/google/common/collect/AbstractMapEntry.h"


@interface ComGoogleCommonCollectMultimaps_MapMultimap_AsMapEntries_$1_$1 : ComGoogleCommonCollectAbstractMapEntry {
}

- (id)getKey;

- (id<JavaUtilCollection>)getValue;

- (instancetype)initWithComGoogleCommonCollectMultimaps_MapMultimap_AsMapEntries_$1:(ComGoogleCommonCollectMultimaps_MapMultimap_AsMapEntries_$1 *)outer$
                                                                             withId:(id)capture$0;

@end

J2OBJC_EMPTY_STATIC_INIT(ComGoogleCommonCollectMultimaps_MapMultimap_AsMapEntries_$1_$1)

CF_EXTERN_C_BEGIN
CF_EXTERN_C_END
#endif

J2OBJC_TYPE_LITERAL_HEADER(ComGoogleCommonCollectMultimaps_MapMultimap_AsMapEntries_$1_$1)
#if !defined (_ComGoogleCommonCollectMultimaps_MapMultimap_AsMap_) && (ComGoogleCommonCollectMultimaps_INCLUDE_ALL || ComGoogleCommonCollectMultimaps_MapMultimap_AsMap_INCLUDE)
#define _ComGoogleCommonCollectMultimaps_MapMultimap_AsMap_

@class ComGoogleCommonCollectMultimaps_MapMultimap;
@protocol JavaUtilCollection;
@protocol JavaUtilSet;

#define ComGoogleCommonCollectMaps_RESTRICT 1
#define ComGoogleCommonCollectMaps_ImprovedAbstractMap_INCLUDE 1
#include "com/google/common/collect/Maps.h"


@interface ComGoogleCommonCollectMultimaps_MapMultimap_AsMap : ComGoogleCommonCollectMaps_ImprovedAbstractMap {
}

- (id<JavaUtilSet>)createEntrySet;

- (jboolean)containsKeyWithId:(id)key;

- (id<JavaUtilCollection>)getWithId:(id)key;

- (id<JavaUtilCollection>)removeWithId:(id)key;

- (instancetype)initWithComGoogleCommonCollectMultimaps_MapMultimap:(ComGoogleCommonCollectMultimaps_MapMultimap *)outer$;

@end

J2OBJC_EMPTY_STATIC_INIT(ComGoogleCommonCollectMultimaps_MapMultimap_AsMap)

CF_EXTERN_C_BEGIN
CF_EXTERN_C_END
#endif

J2OBJC_TYPE_LITERAL_HEADER(ComGoogleCommonCollectMultimaps_MapMultimap_AsMap)
#if !defined (_ComGoogleCommonCollectMultimaps_MapMultimap_$1_) && (ComGoogleCommonCollectMultimaps_INCLUDE_ALL || ComGoogleCommonCollectMultimaps_MapMultimap_$1_INCLUDE)
#define _ComGoogleCommonCollectMultimaps_MapMultimap_$1_

@class ComGoogleCommonCollectMultimaps_MapMultimap;
@protocol JavaUtilIterator;

#define ComGoogleCommonCollectSets_RESTRICT 1
#define ComGoogleCommonCollectSets_ImprovedAbstractSet_INCLUDE 1
#include "com/google/common/collect/Sets.h"


@interface ComGoogleCommonCollectMultimaps_MapMultimap_$1 : ComGoogleCommonCollectSets_ImprovedAbstractSet {
}

- (id<JavaUtilIterator>)iterator;

- (jint)size;

- (instancetype)initWithComGoogleCommonCollectMultimaps_MapMultimap:(ComGoogleCommonCollectMultimaps_MapMultimap *)outer$
                                                             withId:(id)capture$0;


@end

J2OBJC_EMPTY_STATIC_INIT(ComGoogleCommonCollectMultimaps_MapMultimap_$1)

CF_EXTERN_C_BEGIN
CF_EXTERN_C_END
#endif

J2OBJC_TYPE_LITERAL_HEADER(ComGoogleCommonCollectMultimaps_MapMultimap_$1)
#if !defined (_ComGoogleCommonCollectMultimaps_MapMultimap_$1_$1_) && (ComGoogleCommonCollectMultimaps_INCLUDE_ALL || ComGoogleCommonCollectMultimaps_MapMultimap_$1_$1_INCLUDE)
#define _ComGoogleCommonCollectMultimaps_MapMultimap_$1_$1_

@class ComGoogleCommonCollectMultimaps_MapMultimap_$1;

#define JavaUtilIterator_RESTRICT 1
#define JavaUtilIterator_INCLUDE 1
#include "java/util/Iterator.h"


@interface ComGoogleCommonCollectMultimaps_MapMultimap_$1_$1 : NSObject < JavaUtilIterator > {
 @public
  jint i_;
}

- (jboolean)hasNext;

- (id)next;

- (void)remove;

- (instancetype)initWithComGoogleCommonCollectMultimaps_MapMultimap_$1:(ComGoogleCommonCollectMultimaps_MapMultimap_$1 *)outer$;

@end

J2OBJC_EMPTY_STATIC_INIT(ComGoogleCommonCollectMultimaps_MapMultimap_$1_$1)

CF_EXTERN_C_BEGIN
CF_EXTERN_C_END
#endif

J2OBJC_TYPE_LITERAL_HEADER(ComGoogleCommonCollectMultimaps_MapMultimap_$1_$1)
#if !defined (_ComGoogleCommonCollectMultimaps_ValueFunction_) && (ComGoogleCommonCollectMultimaps_INCLUDE_ALL || ComGoogleCommonCollectMultimaps_ValueFunction_INCLUDE)
#define _ComGoogleCommonCollectMultimaps_ValueFunction_

@protocol ComGoogleCommonCollectMaps_EntryTransformer;

#define ComGoogleCommonBaseFunction_RESTRICT 1
#define ComGoogleCommonBaseFunction_INCLUDE 1
#include "com/google/common/base/Function.h"


@interface ComGoogleCommonCollectMultimaps_ValueFunction : NSObject < ComGoogleCommonBaseFunction > {
}

- (instancetype)initWithId:(id)key
withComGoogleCommonCollectMaps_EntryTransformer:(id<ComGoogleCommonCollectMaps_EntryTransformer>)transformer;

- (id)applyWithId:(id)value;

@end

J2OBJC_EMPTY_STATIC_INIT(ComGoogleCommonCollectMultimaps_ValueFunction)

CF_EXTERN_C_BEGIN
CF_EXTERN_C_END
#endif

J2OBJC_TYPE_LITERAL_HEADER(ComGoogleCommonCollectMultimaps_ValueFunction)
#if !defined (_ComGoogleCommonCollectMultimaps_TransformedEntriesMultimap_$1_) && (ComGoogleCommonCollectMultimaps_INCLUDE_ALL || ComGoogleCommonCollectMultimaps_TransformedEntriesMultimap_$1_INCLUDE)
#define _ComGoogleCommonCollectMultimaps_TransformedEntriesMultimap_$1_

@class ComGoogleCommonCollectMultimaps_TransformedEntriesMultimap;
@protocol JavaUtilCollection;

#define ComGoogleCommonCollectMaps_RESTRICT 1
#define ComGoogleCommonCollectMaps_EntryTransformer_INCLUDE 1
#include "com/google/common/collect/Maps.h"


@interface ComGoogleCommonCollectMultimaps_TransformedEntriesMultimap_$1 : NSObject < ComGoogleCommonCollectMaps_EntryTransformer > {
}

- (id<JavaUtilCollection>)transformEntryWithId:(id)key
                                        withId:(id<JavaUtilCollection>)value;

- (instancetype)initWithComGoogleCommonCollectMultimaps_TransformedEntriesMultimap:(ComGoogleCommonCollectMultimaps_TransformedEntriesMultimap *)outer$;

@end

J2OBJC_EMPTY_STATIC_INIT(ComGoogleCommonCollectMultimaps_TransformedEntriesMultimap_$1)

CF_EXTERN_C_BEGIN
CF_EXTERN_C_END
#endif

J2OBJC_TYPE_LITERAL_HEADER(ComGoogleCommonCollectMultimaps_TransformedEntriesMultimap_$1)
#if !defined (_ComGoogleCommonCollectMultimaps_TransformedEntriesMultimap_$2_) && (ComGoogleCommonCollectMultimaps_INCLUDE_ALL || ComGoogleCommonCollectMultimaps_TransformedEntriesMultimap_$2_INCLUDE)
#define _ComGoogleCommonCollectMultimaps_TransformedEntriesMultimap_$2_

@class ComGoogleCommonCollectMultimaps_TransformedEntriesMultimap;
@protocol JavaUtilMap_Entry;

#define ComGoogleCommonBaseFunction_RESTRICT 1
#define ComGoogleCommonBaseFunction_INCLUDE 1
#include "com/google/common/base/Function.h"


@interface ComGoogleCommonCollectMultimaps_TransformedEntriesMultimap_$2 : NSObject < ComGoogleCommonBaseFunction > {
}

- (id<JavaUtilMap_Entry>)applyWithId:(id<JavaUtilMap_Entry>)entry_;

- (instancetype)initWithComGoogleCommonCollectMultimaps_TransformedEntriesMultimap:(ComGoogleCommonCollectMultimaps_TransformedEntriesMultimap *)outer$;

@end

J2OBJC_EMPTY_STATIC_INIT(ComGoogleCommonCollectMultimaps_TransformedEntriesMultimap_$2)

CF_EXTERN_C_BEGIN
CF_EXTERN_C_END
#endif

J2OBJC_TYPE_LITERAL_HEADER(ComGoogleCommonCollectMultimaps_TransformedEntriesMultimap_$2)
#if !defined (_ComGoogleCommonCollectMultimaps_TransformedEntriesMultimap_$2_$1_) && (ComGoogleCommonCollectMultimaps_INCLUDE_ALL || ComGoogleCommonCollectMultimaps_TransformedEntriesMultimap_$2_$1_INCLUDE)
#define _ComGoogleCommonCollectMultimaps_TransformedEntriesMultimap_$2_$1_

@class ComGoogleCommonCollectMultimaps_TransformedEntriesMultimap_$2;
@protocol JavaUtilMap_Entry;

#define ComGoogleCommonCollectAbstractMapEntry_RESTRICT 1
#define ComGoogleCommonCollectAbstractMapEntry_INCLUDE 1
#include "com/google/common/collect/AbstractMapEntry.h"


@interface ComGoogleCommonCollectMultimaps_TransformedEntriesMultimap_$2_$1 : ComGoogleCommonCollectAbstractMapEntry {
}

- (id)getKey;

- (id)getValue;

- (instancetype)initWithComGoogleCommonCollectMultimaps_TransformedEntriesMultimap_$2:(ComGoogleCommonCollectMultimaps_TransformedEntriesMultimap_$2 *)outer$
                                                                withJavaUtilMap_Entry:(id<JavaUtilMap_Entry>)capture$0;

@end

J2OBJC_EMPTY_STATIC_INIT(ComGoogleCommonCollectMultimaps_TransformedEntriesMultimap_$2_$1)

CF_EXTERN_C_BEGIN
CF_EXTERN_C_END
#endif

J2OBJC_TYPE_LITERAL_HEADER(ComGoogleCommonCollectMultimaps_TransformedEntriesMultimap_$2_$1)
#if !defined (_ComGoogleCommonCollectMultimaps_TransformedEntriesMultimap_$3_) && (ComGoogleCommonCollectMultimaps_INCLUDE_ALL || ComGoogleCommonCollectMultimaps_TransformedEntriesMultimap_$3_INCLUDE)
#define _ComGoogleCommonCollectMultimaps_TransformedEntriesMultimap_$3_

@class ComGoogleCommonCollectMultimaps_TransformedEntriesMultimap;
@protocol JavaUtilMap_Entry;

#define ComGoogleCommonBaseFunction_RESTRICT 1
#define ComGoogleCommonBaseFunction_INCLUDE 1
#include "com/google/common/base/Function.h"


@interface ComGoogleCommonCollectMultimaps_TransformedEntriesMultimap_$3 : NSObject < ComGoogleCommonBaseFunction > {
}

- (id)applyWithId:(id<JavaUtilMap_Entry>)entry_;

- (instancetype)initWithComGoogleCommonCollectMultimaps_TransformedEntriesMultimap:(ComGoogleCommonCollectMultimaps_TransformedEntriesMultimap *)outer$;

@end

J2OBJC_EMPTY_STATIC_INIT(ComGoogleCommonCollectMultimaps_TransformedEntriesMultimap_$3)

CF_EXTERN_C_BEGIN
CF_EXTERN_C_END
#endif

J2OBJC_TYPE_LITERAL_HEADER(ComGoogleCommonCollectMultimaps_TransformedEntriesMultimap_$3)
#if !defined (_ComGoogleCommonCollectMultimaps_TransformedEntriesMultimap_) && (ComGoogleCommonCollectMultimaps_INCLUDE_ALL || ComGoogleCommonCollectMultimaps_TransformedEntriesMultimap_INCLUDE)
#define _ComGoogleCommonCollectMultimaps_TransformedEntriesMultimap_

@protocol ComGoogleCommonCollectMaps_EntryTransformer;
@protocol ComGoogleCommonCollectMultimap;
@protocol ComGoogleCommonCollectMultiset;
@protocol JavaLangIterable;
@protocol JavaUtilCollection;
@protocol JavaUtilIterator;
@protocol JavaUtilMap;
@protocol JavaUtilSet;

#define ComGoogleCommonCollectAbstractMultimap_RESTRICT 1
#define ComGoogleCommonCollectAbstractMultimap_INCLUDE 1
#include "com/google/common/collect/AbstractMultimap.h"


@interface ComGoogleCommonCollectMultimaps_TransformedEntriesMultimap : ComGoogleCommonCollectAbstractMultimap {
 @public
  id<ComGoogleCommonCollectMultimap> fromMultimap_;
  id<ComGoogleCommonCollectMaps_EntryTransformer> transformer_;
}

- (instancetype)initWithComGoogleCommonCollectMultimap:(id<ComGoogleCommonCollectMultimap>)fromMultimap
       withComGoogleCommonCollectMaps_EntryTransformer:(id<ComGoogleCommonCollectMaps_EntryTransformer>)transformer;

- (id<JavaUtilCollection>)transformWithId:(id)key
                   withJavaUtilCollection:(id<JavaUtilCollection>)values;

- (id<JavaUtilMap>)createAsMap;

- (void)clear;

- (jboolean)containsEntryWithId:(id)key
                         withId:(id)value;

- (jboolean)containsKeyWithId:(id)key;

- (jboolean)containsValueWithId:(id)value;

- (id<JavaUtilIterator>)entryIterator;

- (id<JavaUtilCollection>)getWithId:(id)key;

- (jboolean)isEmpty;

- (id<JavaUtilSet>)keySet;

- (id<ComGoogleCommonCollectMultiset>)keys;

- (jboolean)putWithId:(id)key
               withId:(id)value;

- (jboolean)putAllWithId:(id)key
    withJavaLangIterable:(id<JavaLangIterable>)values;

- (jboolean)putAllWithComGoogleCommonCollectMultimap:(id<ComGoogleCommonCollectMultimap>)multimap;

- (jboolean)removeWithId:(id)key
                  withId:(id)value;

- (id<JavaUtilCollection>)removeAllWithId:(id)key;

- (id<JavaUtilCollection>)replaceValuesWithId:(id)key
                         withJavaLangIterable:(id<JavaLangIterable>)values;

- (jint)size;

- (id<JavaUtilCollection>)createValues;

@end

J2OBJC_EMPTY_STATIC_INIT(ComGoogleCommonCollectMultimaps_TransformedEntriesMultimap)

J2OBJC_FIELD_SETTER(ComGoogleCommonCollectMultimaps_TransformedEntriesMultimap, fromMultimap_, id<ComGoogleCommonCollectMultimap>)
J2OBJC_FIELD_SETTER(ComGoogleCommonCollectMultimaps_TransformedEntriesMultimap, transformer_, id<ComGoogleCommonCollectMaps_EntryTransformer>)

CF_EXTERN_C_BEGIN
CF_EXTERN_C_END
#endif

J2OBJC_TYPE_LITERAL_HEADER(ComGoogleCommonCollectMultimaps_TransformedEntriesMultimap)
#if !defined (_ComGoogleCommonCollectMultimaps_TransformedEntriesListMultimap_) && (ComGoogleCommonCollectMultimaps_INCLUDE_ALL || ComGoogleCommonCollectMultimaps_TransformedEntriesListMultimap_INCLUDE)
#define _ComGoogleCommonCollectMultimaps_TransformedEntriesListMultimap_

@protocol ComGoogleCommonCollectMaps_EntryTransformer;
@protocol JavaLangIterable;
@protocol JavaUtilCollection;
@protocol JavaUtilList;

#define ComGoogleCommonCollectListMultimap_RESTRICT 1
#define ComGoogleCommonCollectListMultimap_INCLUDE 1
#include "com/google/common/collect/ListMultimap.h"


@interface ComGoogleCommonCollectMultimaps_TransformedEntriesListMultimap : ComGoogleCommonCollectMultimaps_TransformedEntriesMultimap < ComGoogleCommonCollectListMultimap > {
}

- (instancetype)initWithComGoogleCommonCollectListMultimap:(id<ComGoogleCommonCollectListMultimap>)fromMultimap
           withComGoogleCommonCollectMaps_EntryTransformer:(id<ComGoogleCommonCollectMaps_EntryTransformer>)transformer;

- (id<JavaUtilList>)transformWithId:(id)key
             withJavaUtilCollection:(id<JavaUtilCollection>)values;

- (id<JavaUtilList>)getWithId:(id)key;

- (id<JavaUtilList>)removeAllWithId:(id)key;

- (id<JavaUtilList>)replaceValuesWithId:(id)key
                   withJavaLangIterable:(id<JavaLangIterable>)values;

@end

J2OBJC_EMPTY_STATIC_INIT(ComGoogleCommonCollectMultimaps_TransformedEntriesListMultimap)

CF_EXTERN_C_BEGIN
CF_EXTERN_C_END
#endif

J2OBJC_TYPE_LITERAL_HEADER(ComGoogleCommonCollectMultimaps_TransformedEntriesListMultimap)
#if !defined (_ComGoogleCommonCollectMultimaps_TransformedEntriesListMultimap_$1_) && (ComGoogleCommonCollectMultimaps_INCLUDE_ALL || ComGoogleCommonCollectMultimaps_TransformedEntriesListMultimap_$1_INCLUDE)
#define _ComGoogleCommonCollectMultimaps_TransformedEntriesListMultimap_$1_

@class ComGoogleCommonCollectMultimaps_TransformedEntriesListMultimap;

#define ComGoogleCommonBaseFunction_RESTRICT 1
#define ComGoogleCommonBaseFunction_INCLUDE 1
#include "com/google/common/base/Function.h"


@interface ComGoogleCommonCollectMultimaps_TransformedEntriesListMultimap_$1 : NSObject < ComGoogleCommonBaseFunction > {
}

- (id)applyWithId:(id)value;

- (instancetype)initWithComGoogleCommonCollectMultimaps_TransformedEntriesListMultimap:(ComGoogleCommonCollectMultimaps_TransformedEntriesListMultimap *)outer$
                                                                                withId:(id)capture$0;

@end

J2OBJC_EMPTY_STATIC_INIT(ComGoogleCommonCollectMultimaps_TransformedEntriesListMultimap_$1)

CF_EXTERN_C_BEGIN
CF_EXTERN_C_END
#endif

J2OBJC_TYPE_LITERAL_HEADER(ComGoogleCommonCollectMultimaps_TransformedEntriesListMultimap_$1)
#if !defined (_ComGoogleCommonCollectMultimaps_Keys_) && (ComGoogleCommonCollectMultimaps_INCLUDE_ALL || ComGoogleCommonCollectMultimaps_Keys_INCLUDE)
#define _ComGoogleCommonCollectMultimaps_Keys_

@protocol ComGoogleCommonCollectMultimap;
@protocol JavaUtilIterator;
@protocol JavaUtilSet;

#define ComGoogleCommonCollectAbstractMultiset_RESTRICT 1
#define ComGoogleCommonCollectAbstractMultiset_INCLUDE 1
#include "com/google/common/collect/AbstractMultiset.h"


@interface ComGoogleCommonCollectMultimaps_Keys : ComGoogleCommonCollectAbstractMultiset {
 @public
  __weak id<ComGoogleCommonCollectMultimap> multimap_;
}

- (instancetype)initWithComGoogleCommonCollectMultimap:(id<ComGoogleCommonCollectMultimap>)multimap;

- (id<JavaUtilIterator>)entryIterator;

- (jint)distinctElements;

- (id<JavaUtilSet>)createEntrySet;

- (jboolean)containsWithId:(id)element;

- (id<JavaUtilIterator>)iterator;

- (jint)countWithId:(id)element;

- (jint)removeWithId:(id)element
             withInt:(jint)occurrences;

- (void)clear;

- (id<JavaUtilSet>)elementSet;


@end

J2OBJC_EMPTY_STATIC_INIT(ComGoogleCommonCollectMultimaps_Keys)

CF_EXTERN_C_BEGIN
CF_EXTERN_C_END
#endif

J2OBJC_TYPE_LITERAL_HEADER(ComGoogleCommonCollectMultimaps_Keys)
#if !defined (_ComGoogleCommonCollectMultimaps_Keys_KeysEntrySet_) && (ComGoogleCommonCollectMultimaps_INCLUDE_ALL || ComGoogleCommonCollectMultimaps_Keys_KeysEntrySet_INCLUDE)
#define _ComGoogleCommonCollectMultimaps_Keys_KeysEntrySet_

@class ComGoogleCommonCollectMultimaps_Keys;
@protocol ComGoogleCommonCollectMultiset;
@protocol JavaUtilIterator;

#define ComGoogleCommonCollectMultisets_RESTRICT 1
#define ComGoogleCommonCollectMultisets_EntrySet_INCLUDE 1
#include "com/google/common/collect/Multisets.h"


@interface ComGoogleCommonCollectMultimaps_Keys_KeysEntrySet : ComGoogleCommonCollectMultisets_EntrySet {
}

- (id<ComGoogleCommonCollectMultiset>)multiset;

- (id<JavaUtilIterator>)iterator;

- (jint)size;

- (jboolean)isEmpty;

- (jboolean)containsWithId:(id)o;

- (jboolean)removeWithId:(id)o;

- (instancetype)initWithComGoogleCommonCollectMultimaps_Keys:(ComGoogleCommonCollectMultimaps_Keys *)outer$;


@end

J2OBJC_EMPTY_STATIC_INIT(ComGoogleCommonCollectMultimaps_Keys_KeysEntrySet)

CF_EXTERN_C_BEGIN
CF_EXTERN_C_END
#endif

J2OBJC_TYPE_LITERAL_HEADER(ComGoogleCommonCollectMultimaps_Keys_KeysEntrySet)
#if !defined (_ComGoogleCommonCollectMultimaps_Keys_$1_) && (ComGoogleCommonCollectMultimaps_INCLUDE_ALL || ComGoogleCommonCollectMultimaps_Keys_$1_INCLUDE)
#define _ComGoogleCommonCollectMultimaps_Keys_$1_

@protocol ComGoogleCommonCollectMultiset_Entry;
@protocol JavaUtilIterator;
@protocol JavaUtilMap_Entry;

#define ComGoogleCommonCollectTransformedIterator_RESTRICT 1
#define ComGoogleCommonCollectTransformedIterator_INCLUDE 1
#include "com/google/common/collect/TransformedIterator.h"


@interface ComGoogleCommonCollectMultimaps_Keys_$1 : ComGoogleCommonCollectTransformedIterator {
}

- (id<ComGoogleCommonCollectMultiset_Entry>)transformWithId:(id<JavaUtilMap_Entry>)backingEntry;

- (instancetype)initWithJavaUtilIterator:(id<JavaUtilIterator>)arg$0;

@end

J2OBJC_EMPTY_STATIC_INIT(ComGoogleCommonCollectMultimaps_Keys_$1)

CF_EXTERN_C_BEGIN
CF_EXTERN_C_END
#endif

J2OBJC_TYPE_LITERAL_HEADER(ComGoogleCommonCollectMultimaps_Keys_$1)
#if !defined (_ComGoogleCommonCollectMultimaps_Keys_$1_$1_) && (ComGoogleCommonCollectMultimaps_INCLUDE_ALL || ComGoogleCommonCollectMultimaps_Keys_$1_$1_INCLUDE)
#define _ComGoogleCommonCollectMultimaps_Keys_$1_$1_

@protocol JavaUtilMap_Entry;

#define ComGoogleCommonCollectMultisets_RESTRICT 1
#define ComGoogleCommonCollectMultisets_AbstractEntry_INCLUDE 1
#include "com/google/common/collect/Multisets.h"


@interface ComGoogleCommonCollectMultimaps_Keys_$1_$1 : ComGoogleCommonCollectMultisets_AbstractEntry {
}

- (id)getElement;

- (jint)getCount;

- (instancetype)initWithJavaUtilMap_Entry:(id<JavaUtilMap_Entry>)capture$0;

@end

J2OBJC_EMPTY_STATIC_INIT(ComGoogleCommonCollectMultimaps_Keys_$1_$1)

CF_EXTERN_C_BEGIN
CF_EXTERN_C_END
#endif

J2OBJC_TYPE_LITERAL_HEADER(ComGoogleCommonCollectMultimaps_Keys_$1_$1)
#if !defined (_ComGoogleCommonCollectMultimaps_Values_) && (ComGoogleCommonCollectMultimaps_INCLUDE_ALL || ComGoogleCommonCollectMultimaps_Values_INCLUDE)
#define _ComGoogleCommonCollectMultimaps_Values_

@protocol ComGoogleCommonCollectMultimap;
@protocol JavaUtilIterator;

#define JavaUtilAbstractCollection_RESTRICT 1
#define JavaUtilAbstractCollection_INCLUDE 1
#include "java/util/AbstractCollection.h"


@interface ComGoogleCommonCollectMultimaps_Values : JavaUtilAbstractCollection {
 @public
  __weak id<ComGoogleCommonCollectMultimap> multimap_;
}

- (instancetype)initWithComGoogleCommonCollectMultimap:(id<ComGoogleCommonCollectMultimap>)multimap;

- (id<JavaUtilIterator>)iterator;

- (jint)size;

- (jboolean)containsWithId:(id)o;

- (void)clear;


@end

J2OBJC_EMPTY_STATIC_INIT(ComGoogleCommonCollectMultimaps_Values)

CF_EXTERN_C_BEGIN
CF_EXTERN_C_END
#endif

J2OBJC_TYPE_LITERAL_HEADER(ComGoogleCommonCollectMultimaps_Values)
#if !defined (_ComGoogleCommonCollectMultimaps_Entries_) && (ComGoogleCommonCollectMultimaps_INCLUDE_ALL || ComGoogleCommonCollectMultimaps_Entries_INCLUDE)
#define _ComGoogleCommonCollectMultimaps_Entries_

@protocol ComGoogleCommonCollectMultimap;

#define JavaUtilAbstractCollection_RESTRICT 1
#define JavaUtilAbstractCollection_INCLUDE 1
#include "java/util/AbstractCollection.h"


@interface ComGoogleCommonCollectMultimaps_Entries : JavaUtilAbstractCollection {
}

- (id<ComGoogleCommonCollectMultimap>)multimap;

- (jint)size;

- (jboolean)containsWithId:(id)o;

- (jboolean)removeWithId:(id)o;

- (void)clear;

- (instancetype)init;


@end

J2OBJC_EMPTY_STATIC_INIT(ComGoogleCommonCollectMultimaps_Entries)

CF_EXTERN_C_BEGIN
CF_EXTERN_C_END
#endif

J2OBJC_TYPE_LITERAL_HEADER(ComGoogleCommonCollectMultimaps_Entries)
#if !defined (_ComGoogleCommonCollectMultimaps_EntrySet_) && (ComGoogleCommonCollectMultimaps_INCLUDE_ALL || ComGoogleCommonCollectMultimaps_EntrySet_INCLUDE)
#define _ComGoogleCommonCollectMultimaps_EntrySet_

#define JavaUtilSet_RESTRICT 1
#define JavaUtilSet_INCLUDE 1
#include "java/util/Set.h"


@interface ComGoogleCommonCollectMultimaps_EntrySet : ComGoogleCommonCollectMultimaps_Entries < JavaUtilSet > {
}

- (NSUInteger)hash;

- (jboolean)isEqual:(id)obj;

- (instancetype)init;


@end

J2OBJC_EMPTY_STATIC_INIT(ComGoogleCommonCollectMultimaps_EntrySet)

CF_EXTERN_C_BEGIN
CF_EXTERN_C_END
#endif

J2OBJC_TYPE_LITERAL_HEADER(ComGoogleCommonCollectMultimaps_EntrySet)
#if !defined (_ComGoogleCommonCollectMultimaps_AsMap_) && (ComGoogleCommonCollectMultimaps_INCLUDE_ALL || ComGoogleCommonCollectMultimaps_AsMap_INCLUDE)
#define _ComGoogleCommonCollectMultimaps_AsMap_

@protocol ComGoogleCommonCollectMultimap;
@protocol JavaUtilCollection;
@protocol JavaUtilIterator;
@protocol JavaUtilSet;

#define ComGoogleCommonCollectMaps_RESTRICT 1
#define ComGoogleCommonCollectMaps_ImprovedAbstractMap_INCLUDE 1
#include "com/google/common/collect/Maps.h"


@interface ComGoogleCommonCollectMultimaps_AsMap : ComGoogleCommonCollectMaps_ImprovedAbstractMap {
}

- (id<ComGoogleCommonCollectMultimap>)multimap;

- (jint)size;

- (id<JavaUtilIterator>)entryIterator;

- (id<JavaUtilSet>)createEntrySet;

- (void)removeValuesForKeyWithId:(id)key;

- (id<JavaUtilCollection>)getWithId:(id)key;

- (id<JavaUtilCollection>)removeWithId:(id)key;

- (id<JavaUtilSet>)keySet;

- (jboolean)isEmpty;

- (jboolean)containsKeyWithId:(id)key;

- (void)clear;

- (instancetype)init;

@end

J2OBJC_EMPTY_STATIC_INIT(ComGoogleCommonCollectMultimaps_AsMap)

CF_EXTERN_C_BEGIN
CF_EXTERN_C_END
#endif

J2OBJC_TYPE_LITERAL_HEADER(ComGoogleCommonCollectMultimaps_AsMap)
#if !defined (_ComGoogleCommonCollectMultimaps_AsMap_EntrySet_) && (ComGoogleCommonCollectMultimaps_INCLUDE_ALL || ComGoogleCommonCollectMultimaps_AsMap_EntrySet_INCLUDE)
#define _ComGoogleCommonCollectMultimaps_AsMap_EntrySet_

@class ComGoogleCommonCollectMultimaps_AsMap;
@protocol JavaUtilIterator;
@protocol JavaUtilMap;

#define ComGoogleCommonCollectMaps_RESTRICT 1
#define ComGoogleCommonCollectMaps_EntrySet_INCLUDE 1
#include "com/google/common/collect/Maps.h"


@interface ComGoogleCommonCollectMultimaps_AsMap_EntrySet : ComGoogleCommonCollectMaps_EntrySet {
}

- (id<JavaUtilMap>)map;

- (id<JavaUtilIterator>)iterator;

- (jboolean)removeWithId:(id)o;

- (instancetype)initWithComGoogleCommonCollectMultimaps_AsMap:(ComGoogleCommonCollectMultimaps_AsMap *)outer$;


@end

J2OBJC_EMPTY_STATIC_INIT(ComGoogleCommonCollectMultimaps_AsMap_EntrySet)

CF_EXTERN_C_BEGIN
CF_EXTERN_C_END
#endif

J2OBJC_TYPE_LITERAL_HEADER(ComGoogleCommonCollectMultimaps_AsMap_EntrySet)
#if !defined (_ComGoogleCommonCollectMultimaps_$1_) && (ComGoogleCommonCollectMultimaps_INCLUDE_ALL || ComGoogleCommonCollectMultimaps_$1_INCLUDE)
#define _ComGoogleCommonCollectMultimaps_$1_

@protocol JavaUtilCollection;
@protocol JavaUtilMap_Entry;

#define ComGoogleCommonCollectAbstractMapEntry_RESTRICT 1
#define ComGoogleCommonCollectAbstractMapEntry_INCLUDE 1
#include "com/google/common/collect/AbstractMapEntry.h"


@interface ComGoogleCommonCollectMultimaps_$1 : ComGoogleCommonCollectAbstractMapEntry {
}

- (id)getKey;

- (id<JavaUtilCollection>)getValue;

- (instancetype)initWithJavaUtilMap_Entry:(id<JavaUtilMap_Entry>)capture$0;

@end

J2OBJC_EMPTY_STATIC_INIT(ComGoogleCommonCollectMultimaps_$1)

CF_EXTERN_C_BEGIN
CF_EXTERN_C_END
#endif

J2OBJC_TYPE_LITERAL_HEADER(ComGoogleCommonCollectMultimaps_$1)
#if !defined (_ComGoogleCommonCollectMultimaps_$2_) && (ComGoogleCommonCollectMultimaps_INCLUDE_ALL || ComGoogleCommonCollectMultimaps_$2_INCLUDE)
#define _ComGoogleCommonCollectMultimaps_$2_

@protocol ComGoogleCommonBaseFunction;

#define ComGoogleCommonCollectMaps_RESTRICT 1
#define ComGoogleCommonCollectMaps_EntryTransformer_INCLUDE 1
#include "com/google/common/collect/Maps.h"


@interface ComGoogleCommonCollectMultimaps_$2 : NSObject < ComGoogleCommonCollectMaps_EntryTransformer > {
}

- (id)transformEntryWithId:(id)key
                    withId:(id)value;

- (instancetype)initWithComGoogleCommonBaseFunction:(id<ComGoogleCommonBaseFunction>)capture$0;

@end

J2OBJC_EMPTY_STATIC_INIT(ComGoogleCommonCollectMultimaps_$2)

CF_EXTERN_C_BEGIN
CF_EXTERN_C_END
#endif

J2OBJC_TYPE_LITERAL_HEADER(ComGoogleCommonCollectMultimaps_$2)
#if !defined (_ComGoogleCommonCollectMultimaps_$3_) && (ComGoogleCommonCollectMultimaps_INCLUDE_ALL || ComGoogleCommonCollectMultimaps_$3_INCLUDE)
#define _ComGoogleCommonCollectMultimaps_$3_

@protocol ComGoogleCommonBaseFunction;

#define ComGoogleCommonCollectMaps_RESTRICT 1
#define ComGoogleCommonCollectMaps_EntryTransformer_INCLUDE 1
#include "com/google/common/collect/Maps.h"


@interface ComGoogleCommonCollectMultimaps_$3 : NSObject < ComGoogleCommonCollectMaps_EntryTransformer > {
}

- (id)transformEntryWithId:(id)key
                    withId:(id)value;

- (instancetype)initWithComGoogleCommonBaseFunction:(id<ComGoogleCommonBaseFunction>)capture$0;

@end

J2OBJC_EMPTY_STATIC_INIT(ComGoogleCommonCollectMultimaps_$3)

CF_EXTERN_C_BEGIN
CF_EXTERN_C_END
#endif

J2OBJC_TYPE_LITERAL_HEADER(ComGoogleCommonCollectMultimaps_$3)
