//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: /Users/krasnocka/Downloads/j2objc-master/guava/sources/com/google/common/collect/Multimap.java
//

#include "J2ObjC_header.h"

#if !ComGoogleCommonCollectMultimap_RESTRICT
#define ComGoogleCommonCollectMultimap_INCLUDE_ALL 1
#endif
#undef ComGoogleCommonCollectMultimap_RESTRICT
#if !defined (_ComGoogleCommonCollectMultimap_) && (ComGoogleCommonCollectMultimap_INCLUDE_ALL || ComGoogleCommonCollectMultimap_INCLUDE)
#define _ComGoogleCommonCollectMultimap_

@protocol ComGoogleCommonCollectMultiset;
@protocol JavaLangIterable;
@protocol JavaUtilCollection;
@protocol JavaUtilMap;
@protocol JavaUtilSet;


@protocol ComGoogleCommonCollectMultimap < NSObject, JavaObject >

- (jint)size;

- (jboolean)isEmpty;

- (jboolean)containsKeyWithId:(id)key;

- (jboolean)containsValueWithId:(id)value;

- (jboolean)containsEntryWithId:(id)key
                         withId:(id)value;

- (jboolean)putWithId:(id)key
               withId:(id)value;

- (jboolean)removeWithId:(id)key
                  withId:(id)value;

- (jboolean)putAllWithId:(id)key
    withJavaLangIterable:(id<JavaLangIterable>)values;

- (jboolean)putAllWithComGoogleCommonCollectMultimap:(id<ComGoogleCommonCollectMultimap>)multimap;

- (id<JavaUtilCollection>)replaceValuesWithId:(id)key
                         withJavaLangIterable:(id<JavaLangIterable>)values;

- (id<JavaUtilCollection>)removeAllWithId:(id)key;

- (void)clear;

- (id<JavaUtilCollection>)getWithId:(id)key;

- (id<JavaUtilSet>)keySet;

- (id<ComGoogleCommonCollectMultiset>)keys;

- (id<JavaUtilCollection>)values;

- (id<JavaUtilCollection>)entries;

- (id<JavaUtilMap>)asMap;

- (jboolean)isEqual:(id)obj;

- (NSUInteger)hash;

@end

J2OBJC_EMPTY_STATIC_INIT(ComGoogleCommonCollectMultimap)
#endif

J2OBJC_TYPE_LITERAL_HEADER(ComGoogleCommonCollectMultimap)
