//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: /Users/krasnocka/Downloads/j2objc-master/guava/sources/com/google/common/collect/RegularImmutableMap.java
//

#include "J2ObjC_header.h"

#if !ComGoogleCommonCollectRegularImmutableMap_RESTRICT
#define ComGoogleCommonCollectRegularImmutableMap_INCLUDE_ALL 1
#endif
#undef ComGoogleCommonCollectRegularImmutableMap_RESTRICT
#if ComGoogleCommonCollectRegularImmutableMap_TerminalEntry_INCLUDE
#define ComGoogleCommonCollectRegularImmutableMap_LinkedEntry_INCLUDE 1
#endif
#if ComGoogleCommonCollectRegularImmutableMap_NonTerminalEntry_INCLUDE
#define ComGoogleCommonCollectRegularImmutableMap_LinkedEntry_INCLUDE 1
#endif
#if !defined (_ComGoogleCommonCollectRegularImmutableMap_) && (ComGoogleCommonCollectRegularImmutableMap_INCLUDE_ALL || ComGoogleCommonCollectRegularImmutableMap_INCLUDE)
#define _ComGoogleCommonCollectRegularImmutableMap_

@class ComGoogleCommonCollectImmutableSet;
@class IOSObjectArray;
@protocol ComGoogleCommonCollectRegularImmutableMap_LinkedEntry;

#define ComGoogleCommonCollectImmutableMap_RESTRICT 1
#define ComGoogleCommonCollectImmutableMap_INCLUDE 1
#include "com/google/common/collect/ImmutableMap.h"


#define ComGoogleCommonCollectRegularImmutableMap_MAX_LOAD_FACTOR 1.2
#define ComGoogleCommonCollectRegularImmutableMap_serialVersionUID 0LL

@interface ComGoogleCommonCollectRegularImmutableMap : ComGoogleCommonCollectImmutableMap {
}

- (instancetype)initWithJavaUtilMap_EntryArray:(IOSObjectArray *)immutableEntries;

- (id)getWithId:(id)key;

- (jint)size;

- (jboolean)isPartialView;

- (ComGoogleCommonCollectImmutableSet *)createEntrySet;

@end

J2OBJC_EMPTY_STATIC_INIT(ComGoogleCommonCollectRegularImmutableMap)

CF_EXTERN_C_BEGIN

J2OBJC_STATIC_FIELD_GETTER(ComGoogleCommonCollectRegularImmutableMap, MAX_LOAD_FACTOR, jdouble)

J2OBJC_STATIC_FIELD_GETTER(ComGoogleCommonCollectRegularImmutableMap, serialVersionUID, jlong)
CF_EXTERN_C_END
#endif

J2OBJC_TYPE_LITERAL_HEADER(ComGoogleCommonCollectRegularImmutableMap)
#if !defined (_ComGoogleCommonCollectRegularImmutableMap_LinkedEntry_) && (ComGoogleCommonCollectRegularImmutableMap_INCLUDE_ALL || ComGoogleCommonCollectRegularImmutableMap_LinkedEntry_INCLUDE)
#define _ComGoogleCommonCollectRegularImmutableMap_LinkedEntry_

#define JavaUtilMap_RESTRICT 1
#define JavaUtilMap_Entry_INCLUDE 1
#include "java/util/Map.h"


@protocol ComGoogleCommonCollectRegularImmutableMap_LinkedEntry < JavaUtilMap_Entry, NSObject, JavaObject >
- (id<ComGoogleCommonCollectRegularImmutableMap_LinkedEntry>)next;

@end

J2OBJC_EMPTY_STATIC_INIT(ComGoogleCommonCollectRegularImmutableMap_LinkedEntry)
#endif

J2OBJC_TYPE_LITERAL_HEADER(ComGoogleCommonCollectRegularImmutableMap_LinkedEntry)
#if !defined (_ComGoogleCommonCollectRegularImmutableMap_NonTerminalEntry_) && (ComGoogleCommonCollectRegularImmutableMap_INCLUDE_ALL || ComGoogleCommonCollectRegularImmutableMap_NonTerminalEntry_INCLUDE)
#define _ComGoogleCommonCollectRegularImmutableMap_NonTerminalEntry_

#define ComGoogleCommonCollectImmutableEntry_RESTRICT 1
#define ComGoogleCommonCollectImmutableEntry_INCLUDE 1
#include "com/google/common/collect/ImmutableEntry.h"


@interface ComGoogleCommonCollectRegularImmutableMap_NonTerminalEntry : ComGoogleCommonCollectImmutableEntry < ComGoogleCommonCollectRegularImmutableMap_LinkedEntry > {
 @public
  id<ComGoogleCommonCollectRegularImmutableMap_LinkedEntry> next__;
}

- (instancetype)initWithId:(id)key
                    withId:(id)value
withComGoogleCommonCollectRegularImmutableMap_LinkedEntry:(id<ComGoogleCommonCollectRegularImmutableMap_LinkedEntry>)next;

- (id<ComGoogleCommonCollectRegularImmutableMap_LinkedEntry>)next;

@end

J2OBJC_EMPTY_STATIC_INIT(ComGoogleCommonCollectRegularImmutableMap_NonTerminalEntry)

J2OBJC_FIELD_SETTER(ComGoogleCommonCollectRegularImmutableMap_NonTerminalEntry, next__, id<ComGoogleCommonCollectRegularImmutableMap_LinkedEntry>)

CF_EXTERN_C_BEGIN
CF_EXTERN_C_END
#endif

J2OBJC_TYPE_LITERAL_HEADER(ComGoogleCommonCollectRegularImmutableMap_NonTerminalEntry)
#if !defined (_ComGoogleCommonCollectRegularImmutableMap_TerminalEntry_) && (ComGoogleCommonCollectRegularImmutableMap_INCLUDE_ALL || ComGoogleCommonCollectRegularImmutableMap_TerminalEntry_INCLUDE)
#define _ComGoogleCommonCollectRegularImmutableMap_TerminalEntry_

#define ComGoogleCommonCollectImmutableEntry_RESTRICT 1
#define ComGoogleCommonCollectImmutableEntry_INCLUDE 1
#include "com/google/common/collect/ImmutableEntry.h"


@interface ComGoogleCommonCollectRegularImmutableMap_TerminalEntry : ComGoogleCommonCollectImmutableEntry < ComGoogleCommonCollectRegularImmutableMap_LinkedEntry > {
}

- (instancetype)initWithId:(id)key
                    withId:(id)value;

- (id<ComGoogleCommonCollectRegularImmutableMap_LinkedEntry>)next;

@end

J2OBJC_EMPTY_STATIC_INIT(ComGoogleCommonCollectRegularImmutableMap_TerminalEntry)

CF_EXTERN_C_BEGIN
CF_EXTERN_C_END
#endif

J2OBJC_TYPE_LITERAL_HEADER(ComGoogleCommonCollectRegularImmutableMap_TerminalEntry)
#if !defined (_ComGoogleCommonCollectRegularImmutableMap_EntrySet_) && (ComGoogleCommonCollectRegularImmutableMap_INCLUDE_ALL || ComGoogleCommonCollectRegularImmutableMap_EntrySet_INCLUDE)
#define _ComGoogleCommonCollectRegularImmutableMap_EntrySet_

@class ComGoogleCommonCollectImmutableList;
@class ComGoogleCommonCollectImmutableMap;
@class ComGoogleCommonCollectRegularImmutableMap;
@class ComGoogleCommonCollectUnmodifiableIterator;

#define ComGoogleCommonCollectImmutableMapEntrySet_RESTRICT 1
#define ComGoogleCommonCollectImmutableMapEntrySet_INCLUDE 1
#include "com/google/common/collect/ImmutableMapEntrySet.h"


@interface ComGoogleCommonCollectRegularImmutableMap_EntrySet : ComGoogleCommonCollectImmutableMapEntrySet {
}

- (ComGoogleCommonCollectImmutableMap *)map;

- (ComGoogleCommonCollectUnmodifiableIterator *)iterator;

- (ComGoogleCommonCollectImmutableList *)createAsList;

- (instancetype)initWithComGoogleCommonCollectRegularImmutableMap:(ComGoogleCommonCollectRegularImmutableMap *)outer$;


@end

J2OBJC_EMPTY_STATIC_INIT(ComGoogleCommonCollectRegularImmutableMap_EntrySet)

CF_EXTERN_C_BEGIN
CF_EXTERN_C_END
#endif

J2OBJC_TYPE_LITERAL_HEADER(ComGoogleCommonCollectRegularImmutableMap_EntrySet)
