//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: /Users/krasnocka/Downloads/j2objc-master/guava/sources/com/google/common/collect/RegularImmutableBiMap.java
//

#include "J2ObjC_header.h"

#if !ComGoogleCommonCollectRegularImmutableBiMap_RESTRICT
#define ComGoogleCommonCollectRegularImmutableBiMap_INCLUDE_ALL 1
#endif
#undef ComGoogleCommonCollectRegularImmutableBiMap_RESTRICT
#if ComGoogleCommonCollectRegularImmutableBiMap_NonTerminalBiMapEntry_INCLUDE
#define ComGoogleCommonCollectRegularImmutableBiMap_BiMapEntry_INCLUDE 1
#endif
#if !defined (_ComGoogleCommonCollectRegularImmutableBiMap_) && (ComGoogleCommonCollectRegularImmutableBiMap_INCLUDE_ALL || ComGoogleCommonCollectRegularImmutableBiMap_INCLUDE)
#define _ComGoogleCommonCollectRegularImmutableBiMap_

@class ComGoogleCommonCollectImmutableSet;
@class IOSObjectArray;
@protocol JavaUtilCollection;

#define ComGoogleCommonCollectImmutableBiMap_RESTRICT 1
#define ComGoogleCommonCollectImmutableBiMap_INCLUDE 1
#include "com/google/common/collect/ImmutableBiMap.h"


#define ComGoogleCommonCollectRegularImmutableBiMap_MAX_LOAD_FACTOR 1.2

@interface ComGoogleCommonCollectRegularImmutableBiMap : ComGoogleCommonCollectImmutableBiMap {
}

- (instancetype)initWithJavaUtilCollection:(id<JavaUtilCollection>)entriesToAdd;

- (id)getWithId:(id)key;

- (ComGoogleCommonCollectImmutableSet *)createEntrySet;

- (jboolean)isPartialView;

- (jint)size;

- (ComGoogleCommonCollectImmutableBiMap *)inverse;

@end

J2OBJC_EMPTY_STATIC_INIT(ComGoogleCommonCollectRegularImmutableBiMap)

CF_EXTERN_C_BEGIN

J2OBJC_STATIC_FIELD_GETTER(ComGoogleCommonCollectRegularImmutableBiMap, MAX_LOAD_FACTOR, jdouble)
CF_EXTERN_C_END
#endif

J2OBJC_TYPE_LITERAL_HEADER(ComGoogleCommonCollectRegularImmutableBiMap)
#if !defined (_ComGoogleCommonCollectRegularImmutableBiMap_BiMapEntry_) && (ComGoogleCommonCollectRegularImmutableBiMap_INCLUDE_ALL || ComGoogleCommonCollectRegularImmutableBiMap_BiMapEntry_INCLUDE)
#define _ComGoogleCommonCollectRegularImmutableBiMap_BiMapEntry_

#define ComGoogleCommonCollectImmutableEntry_RESTRICT 1
#define ComGoogleCommonCollectImmutableEntry_INCLUDE 1
#include "com/google/common/collect/ImmutableEntry.h"


@interface ComGoogleCommonCollectRegularImmutableBiMap_BiMapEntry : ComGoogleCommonCollectImmutableEntry {
}

- (instancetype)initWithId:(id)key
                    withId:(id)value;

- (ComGoogleCommonCollectRegularImmutableBiMap_BiMapEntry *)getNextInKToVBucket;

- (ComGoogleCommonCollectRegularImmutableBiMap_BiMapEntry *)getNextInVToKBucket;

@end

J2OBJC_EMPTY_STATIC_INIT(ComGoogleCommonCollectRegularImmutableBiMap_BiMapEntry)

CF_EXTERN_C_BEGIN
CF_EXTERN_C_END
#endif

J2OBJC_TYPE_LITERAL_HEADER(ComGoogleCommonCollectRegularImmutableBiMap_BiMapEntry)
#if !defined (_ComGoogleCommonCollectRegularImmutableBiMap_NonTerminalBiMapEntry_) && (ComGoogleCommonCollectRegularImmutableBiMap_INCLUDE_ALL || ComGoogleCommonCollectRegularImmutableBiMap_NonTerminalBiMapEntry_INCLUDE)
#define _ComGoogleCommonCollectRegularImmutableBiMap_NonTerminalBiMapEntry_


@interface ComGoogleCommonCollectRegularImmutableBiMap_NonTerminalBiMapEntry : ComGoogleCommonCollectRegularImmutableBiMap_BiMapEntry {
}

- (instancetype)initWithId:(id)key
                    withId:(id)value
withComGoogleCommonCollectRegularImmutableBiMap_BiMapEntry:(ComGoogleCommonCollectRegularImmutableBiMap_BiMapEntry *)nextInKToVBucket
withComGoogleCommonCollectRegularImmutableBiMap_BiMapEntry:(ComGoogleCommonCollectRegularImmutableBiMap_BiMapEntry *)nextInVToKBucket;

- (ComGoogleCommonCollectRegularImmutableBiMap_BiMapEntry *)getNextInKToVBucket;

- (ComGoogleCommonCollectRegularImmutableBiMap_BiMapEntry *)getNextInVToKBucket;

@end

J2OBJC_EMPTY_STATIC_INIT(ComGoogleCommonCollectRegularImmutableBiMap_NonTerminalBiMapEntry)

CF_EXTERN_C_BEGIN
CF_EXTERN_C_END
#endif

J2OBJC_TYPE_LITERAL_HEADER(ComGoogleCommonCollectRegularImmutableBiMap_NonTerminalBiMapEntry)
#if !defined (_ComGoogleCommonCollectRegularImmutableBiMap_createEntrySet_RegularImmutableBiMapEntrySet_) && (ComGoogleCommonCollectRegularImmutableBiMap_INCLUDE_ALL || ComGoogleCommonCollectRegularImmutableBiMap_createEntrySet_RegularImmutableBiMapEntrySet_INCLUDE)
#define _ComGoogleCommonCollectRegularImmutableBiMap_createEntrySet_RegularImmutableBiMapEntrySet_

@class ComGoogleCommonCollectImmutableList;
@class ComGoogleCommonCollectImmutableMap;
@class ComGoogleCommonCollectRegularImmutableBiMap;
@class ComGoogleCommonCollectUnmodifiableIterator;

#define ComGoogleCommonCollectImmutableMapEntrySet_RESTRICT 1
#define ComGoogleCommonCollectImmutableMapEntrySet_INCLUDE 1
#include "com/google/common/collect/ImmutableMapEntrySet.h"


@interface ComGoogleCommonCollectRegularImmutableBiMap_createEntrySet_RegularImmutableBiMapEntrySet : ComGoogleCommonCollectImmutableMapEntrySet {
}

- (ComGoogleCommonCollectImmutableMap *)map;

- (ComGoogleCommonCollectUnmodifiableIterator *)iterator;

- (ComGoogleCommonCollectImmutableList *)createAsList;

- (jboolean)isHashCodeFast;

- (NSUInteger)hash;

- (instancetype)initWithComGoogleCommonCollectRegularImmutableBiMap:(ComGoogleCommonCollectRegularImmutableBiMap *)outer$;


@end

J2OBJC_EMPTY_STATIC_INIT(ComGoogleCommonCollectRegularImmutableBiMap_createEntrySet_RegularImmutableBiMapEntrySet)

CF_EXTERN_C_BEGIN
CF_EXTERN_C_END
#endif

J2OBJC_TYPE_LITERAL_HEADER(ComGoogleCommonCollectRegularImmutableBiMap_createEntrySet_RegularImmutableBiMapEntrySet)
#if !defined (_ComGoogleCommonCollectRegularImmutableBiMap_Inverse_) && (ComGoogleCommonCollectRegularImmutableBiMap_INCLUDE_ALL || ComGoogleCommonCollectRegularImmutableBiMap_Inverse_INCLUDE)
#define _ComGoogleCommonCollectRegularImmutableBiMap_Inverse_

@class ComGoogleCommonCollectImmutableSet;
@class ComGoogleCommonCollectRegularImmutableBiMap;

#define ComGoogleCommonCollectImmutableBiMap_RESTRICT 1
#define ComGoogleCommonCollectImmutableBiMap_INCLUDE 1
#include "com/google/common/collect/ImmutableBiMap.h"


@interface ComGoogleCommonCollectRegularImmutableBiMap_Inverse : ComGoogleCommonCollectImmutableBiMap {
}

- (jint)size;

- (ComGoogleCommonCollectImmutableBiMap *)inverse;

- (id)getWithId:(id)value;

- (ComGoogleCommonCollectImmutableSet *)createEntrySet;

- (jboolean)isPartialView;

- (id)writeReplace;

- (instancetype)initWithComGoogleCommonCollectRegularImmutableBiMap:(ComGoogleCommonCollectRegularImmutableBiMap *)outer$;

@end

J2OBJC_EMPTY_STATIC_INIT(ComGoogleCommonCollectRegularImmutableBiMap_Inverse)

CF_EXTERN_C_BEGIN
CF_EXTERN_C_END
#endif

J2OBJC_TYPE_LITERAL_HEADER(ComGoogleCommonCollectRegularImmutableBiMap_Inverse)
#if !defined (_ComGoogleCommonCollectRegularImmutableBiMap_Inverse_InverseEntrySet_) && (ComGoogleCommonCollectRegularImmutableBiMap_INCLUDE_ALL || ComGoogleCommonCollectRegularImmutableBiMap_Inverse_InverseEntrySet_INCLUDE)
#define _ComGoogleCommonCollectRegularImmutableBiMap_Inverse_InverseEntrySet_

@class ComGoogleCommonCollectImmutableList;
@class ComGoogleCommonCollectImmutableMap;
@class ComGoogleCommonCollectRegularImmutableBiMap_Inverse;
@class ComGoogleCommonCollectUnmodifiableIterator;

#define ComGoogleCommonCollectImmutableMapEntrySet_RESTRICT 1
#define ComGoogleCommonCollectImmutableMapEntrySet_INCLUDE 1
#include "com/google/common/collect/ImmutableMapEntrySet.h"


@interface ComGoogleCommonCollectRegularImmutableBiMap_Inverse_InverseEntrySet : ComGoogleCommonCollectImmutableMapEntrySet {
}

- (ComGoogleCommonCollectImmutableMap *)map;

- (jboolean)isHashCodeFast;

- (NSUInteger)hash;

- (ComGoogleCommonCollectUnmodifiableIterator *)iterator;

- (ComGoogleCommonCollectImmutableList *)createAsList;

- (instancetype)initWithComGoogleCommonCollectRegularImmutableBiMap_Inverse:(ComGoogleCommonCollectRegularImmutableBiMap_Inverse *)outer$;


@end

J2OBJC_EMPTY_STATIC_INIT(ComGoogleCommonCollectRegularImmutableBiMap_Inverse_InverseEntrySet)

CF_EXTERN_C_BEGIN
CF_EXTERN_C_END
#endif

J2OBJC_TYPE_LITERAL_HEADER(ComGoogleCommonCollectRegularImmutableBiMap_Inverse_InverseEntrySet)
#if !defined (_ComGoogleCommonCollectRegularImmutableBiMap_Inverse_InverseEntrySet_$1_) && (ComGoogleCommonCollectRegularImmutableBiMap_INCLUDE_ALL || ComGoogleCommonCollectRegularImmutableBiMap_Inverse_InverseEntrySet_$1_INCLUDE)
#define _ComGoogleCommonCollectRegularImmutableBiMap_Inverse_InverseEntrySet_$1_

@class ComGoogleCommonCollectImmutableCollection;
@class ComGoogleCommonCollectRegularImmutableBiMap_Inverse_InverseEntrySet;
@protocol JavaUtilMap_Entry;

#define ComGoogleCommonCollectImmutableAsList_RESTRICT 1
#define ComGoogleCommonCollectImmutableAsList_INCLUDE 1
#include "com/google/common/collect/ImmutableAsList.h"


@interface ComGoogleCommonCollectRegularImmutableBiMap_Inverse_InverseEntrySet_$1 : ComGoogleCommonCollectImmutableAsList {
}

- (id<JavaUtilMap_Entry>)getWithInt:(jint)index;

- (ComGoogleCommonCollectImmutableCollection *)delegateCollection;

- (instancetype)initWithComGoogleCommonCollectRegularImmutableBiMap_Inverse_InverseEntrySet:(ComGoogleCommonCollectRegularImmutableBiMap_Inverse_InverseEntrySet *)outer$;


@end

J2OBJC_EMPTY_STATIC_INIT(ComGoogleCommonCollectRegularImmutableBiMap_Inverse_InverseEntrySet_$1)

CF_EXTERN_C_BEGIN
CF_EXTERN_C_END
#endif

J2OBJC_TYPE_LITERAL_HEADER(ComGoogleCommonCollectRegularImmutableBiMap_Inverse_InverseEntrySet_$1)
#if !defined (_ComGoogleCommonCollectRegularImmutableBiMap_InverseSerializedForm_) && (ComGoogleCommonCollectRegularImmutableBiMap_INCLUDE_ALL || ComGoogleCommonCollectRegularImmutableBiMap_InverseSerializedForm_INCLUDE)
#define _ComGoogleCommonCollectRegularImmutableBiMap_InverseSerializedForm_

@class ComGoogleCommonCollectImmutableBiMap;

#define JavaIoSerializable_RESTRICT 1
#define JavaIoSerializable_INCLUDE 1
#include "java/io/Serializable.h"


#define ComGoogleCommonCollectRegularImmutableBiMap_InverseSerializedForm_serialVersionUID 1LL

@interface ComGoogleCommonCollectRegularImmutableBiMap_InverseSerializedForm : NSObject < JavaIoSerializable > {
}

- (instancetype)initWithComGoogleCommonCollectImmutableBiMap:(ComGoogleCommonCollectImmutableBiMap *)forward;

- (id)readResolve;

@end

J2OBJC_EMPTY_STATIC_INIT(ComGoogleCommonCollectRegularImmutableBiMap_InverseSerializedForm)

CF_EXTERN_C_BEGIN

J2OBJC_STATIC_FIELD_GETTER(ComGoogleCommonCollectRegularImmutableBiMap_InverseSerializedForm, serialVersionUID, jlong)
CF_EXTERN_C_END
#endif

J2OBJC_TYPE_LITERAL_HEADER(ComGoogleCommonCollectRegularImmutableBiMap_InverseSerializedForm)
