//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: /Users/krasnocka/Downloads/j2objc-master/guava/sources/com/google/common/collect/SortedIterables.java
//

#include "J2ObjC_header.h"

#if !ComGoogleCommonCollectSortedIterables_RESTRICT
#define ComGoogleCommonCollectSortedIterables_INCLUDE_ALL 1
#endif
#undef ComGoogleCommonCollectSortedIterables_RESTRICT
#if !defined (_ComGoogleCommonCollectSortedIterables_) && (ComGoogleCommonCollectSortedIterables_INCLUDE_ALL || ComGoogleCommonCollectSortedIterables_INCLUDE)
#define _ComGoogleCommonCollectSortedIterables_

@protocol JavaLangIterable;
@protocol JavaUtilComparator;
@protocol JavaUtilSortedSet;


@interface ComGoogleCommonCollectSortedIterables : NSObject {
}

+ (jboolean)hasSameComparatorWithJavaUtilComparator:(id<JavaUtilComparator>)comparator
                               withJavaLangIterable:(id<JavaLangIterable>)elements;

+ (id<JavaUtilComparator>)comparatorWithJavaUtilSortedSet:(id<JavaUtilSortedSet>)sortedSet;

@end

J2OBJC_EMPTY_STATIC_INIT(ComGoogleCommonCollectSortedIterables)

CF_EXTERN_C_BEGIN

FOUNDATION_EXPORT jboolean ComGoogleCommonCollectSortedIterables_hasSameComparatorWithJavaUtilComparator_withJavaLangIterable_(id<JavaUtilComparator> comparator, id<JavaLangIterable> elements);

FOUNDATION_EXPORT id<JavaUtilComparator> ComGoogleCommonCollectSortedIterables_comparatorWithJavaUtilSortedSet_(id<JavaUtilSortedSet> sortedSet);
CF_EXTERN_C_END
#endif

J2OBJC_TYPE_LITERAL_HEADER(ComGoogleCommonCollectSortedIterables)
