//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: apache_harmony/classlib/modules/luni/src/main/java/java/io/FilterInputStream.java
//
//  Created by tball on 7/15/13.
//

#ifndef _JavaIoFilterInputStream_H_
#define _JavaIoFilterInputStream_H_

@class IOSByteArray;

#import "JreEmulation.h"
#include "java/io/InputStream.h"

@interface JavaIoFilterInputStream : JavaIoInputStream {
 @public
  JavaIoInputStream *in_;
}

@property (nonatomic, retain) JavaIoInputStream *in;

- (id)initWithJavaIoInputStream:(JavaIoInputStream *)inArg;
- (int)available;
- (void)close;
- (void)markWithInt:(int)readlimit;
- (BOOL)markSupported;
- (int)read;
- (int)readWithByteArray:(IOSByteArray *)buffer;
- (int)readWithByteArray:(IOSByteArray *)buffer
                 withInt:(int)offset
                 withInt:(int)count;
- (void)reset;
- (long long int)skipWithLongInt:(long long int)count;
@end

#endif // _JavaIoFilterInputStream_H_
