//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: apache_harmony/classlib/modules/luni/src/main/java/java/io/UTFDataFormatException.java
//
//  Created by tball on 7/15/13.
//

#ifndef _JavaIoUTFDataFormatException_H_
#define _JavaIoUTFDataFormatException_H_

#import "JreEmulation.h"
#include "java/io/IOException.h"

#define JavaIoUTFDataFormatException_serialVersionUID 420743449228280612

@interface JavaIoUTFDataFormatException : JavaIoIOException {
}

- (id)init;
- (id)initWithNSString:(NSString *)detailMessage;
@end

#endif // _JavaIoUTFDataFormatException_H_
