//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: /Users/krasnocka/Downloads/j2objc-master/guava/sources/com/google/common/eventbus/AnnotatedHandlerFinder.java
//

#include "J2ObjC_header.h"

#if !ComGoogleCommonEventbusAnnotatedHandlerFinder_RESTRICT
#define ComGoogleCommonEventbusAnnotatedHandlerFinder_INCLUDE_ALL 1
#endif
#undef ComGoogleCommonEventbusAnnotatedHandlerFinder_RESTRICT
#if !defined (_ComGoogleCommonEventbusAnnotatedHandlerFinder_) && (ComGoogleCommonEventbusAnnotatedHandlerFinder_INCLUDE_ALL || ComGoogleCommonEventbusAnnotatedHandlerFinder_INCLUDE)
#define _ComGoogleCommonEventbusAnnotatedHandlerFinder_

@class ComGoogleCommonCollectImmutableList;
@class ComGoogleCommonEventbusEventHandler;
@class IOSClass;
@class JavaLangReflectMethod;
@protocol ComGoogleCommonCacheLoadingCache;
@protocol ComGoogleCommonCollectMultimap;

#define ComGoogleCommonEventbusHandlerFindingStrategy_RESTRICT 1
#define ComGoogleCommonEventbusHandlerFindingStrategy_INCLUDE 1
#include "com/google/common/eventbus/HandlerFindingStrategy.h"


@interface ComGoogleCommonEventbusAnnotatedHandlerFinder : NSObject < ComGoogleCommonEventbusHandlerFindingStrategy > {
}

- (id<ComGoogleCommonCollectMultimap>)findAllHandlersWithId:(id)listener;

- (instancetype)init;

@end

FOUNDATION_EXPORT BOOL ComGoogleCommonEventbusAnnotatedHandlerFinder_initialized;
J2OBJC_STATIC_INIT(ComGoogleCommonEventbusAnnotatedHandlerFinder)

CF_EXTERN_C_BEGIN

FOUNDATION_EXPORT id<ComGoogleCommonCacheLoadingCache> ComGoogleCommonEventbusAnnotatedHandlerFinder_handlerMethodsCache_;
J2OBJC_STATIC_FIELD_GETTER(ComGoogleCommonEventbusAnnotatedHandlerFinder, handlerMethodsCache_, id<ComGoogleCommonCacheLoadingCache>)
CF_EXTERN_C_END
#endif

J2OBJC_TYPE_LITERAL_HEADER(ComGoogleCommonEventbusAnnotatedHandlerFinder)
#if !defined (_ComGoogleCommonEventbusAnnotatedHandlerFinder_$1_) && (ComGoogleCommonEventbusAnnotatedHandlerFinder_INCLUDE_ALL || ComGoogleCommonEventbusAnnotatedHandlerFinder_$1_INCLUDE)
#define _ComGoogleCommonEventbusAnnotatedHandlerFinder_$1_

@class ComGoogleCommonCollectImmutableList;
@class IOSClass;

#define ComGoogleCommonCacheCacheLoader_RESTRICT 1
#define ComGoogleCommonCacheCacheLoader_INCLUDE 1
#include "com/google/common/cache/CacheLoader.h"


@interface ComGoogleCommonEventbusAnnotatedHandlerFinder_$1 : ComGoogleCommonCacheCacheLoader {
}

- (ComGoogleCommonCollectImmutableList *)load__WithId:(IOSClass *)concreteClass;

- (instancetype)init;

@end

J2OBJC_EMPTY_STATIC_INIT(ComGoogleCommonEventbusAnnotatedHandlerFinder_$1)

CF_EXTERN_C_BEGIN
CF_EXTERN_C_END
#endif

J2OBJC_TYPE_LITERAL_HEADER(ComGoogleCommonEventbusAnnotatedHandlerFinder_$1)
