//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: /Users/krasnocka/Downloads/j2objc-master/testing/mockito/build_result/java/org/mockito/internal/reporting/Pluralizer.java
//

#ifndef _OrgMockitoInternalReportingPluralizer_H_
#define _OrgMockitoInternalReportingPluralizer_H_

#include "J2ObjC_header.h"

@interface OrgMockitoInternalReportingPluralizer : NSObject {
}

+ (NSString *)pluralizeWithInt:(jint)number;

- (instancetype)init;

@end

J2OBJC_EMPTY_STATIC_INIT(OrgMockitoInternalReportingPluralizer)

CF_EXTERN_C_BEGIN

FOUNDATION_EXPORT NSString *OrgMockitoInternalReportingPluralizer_pluralizeWithInt_(jint number);
CF_EXTERN_C_END

J2OBJC_TYPE_LITERAL_HEADER(OrgMockitoInternalReportingPluralizer)

#endif // _OrgMockitoInternalReportingPluralizer_H_
