//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: /Users/krasnocka/Downloads/j2objc-master/testing/mockito/build_result/java/org/mockito/internal/verification/api/VerificationInOrderMode.java
//

#ifndef _OrgMockitoInternalVerificationApiVerificationInOrderMode_H_
#define _OrgMockitoInternalVerificationApiVerificationInOrderMode_H_

@protocol OrgMockitoInternalVerificationApiVerificationDataInOrder;

#include "J2ObjC_header.h"

@protocol OrgMockitoInternalVerificationApiVerificationInOrderMode < NSObject, JavaObject >

- (void)verifyInOrderWithOrgMockitoInternalVerificationApiVerificationDataInOrder:(id<OrgMockitoInternalVerificationApiVerificationDataInOrder>)data;

@end

J2OBJC_EMPTY_STATIC_INIT(OrgMockitoInternalVerificationApiVerificationInOrderMode)

J2OBJC_TYPE_LITERAL_HEADER(OrgMockitoInternalVerificationApiVerificationInOrderMode)

#endif // _OrgMockitoInternalVerificationApiVerificationInOrderMode_H_
