//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: android/libcore/luni/src/main/java/java/net/Proxy.java
//

#ifndef _JavaNetProxy_H_
#define _JavaNetProxy_H_

@class JavaNetProxy_TypeEnum;
@class JavaNetSocketAddress;

#include "J2ObjC_header.h"
#include "java/lang/Enum.h"

@interface JavaNetProxy : NSObject {
}

- (instancetype)initWithJavaNetProxy_TypeEnum:(JavaNetProxy_TypeEnum *)type
                     withJavaNetSocketAddress:(JavaNetSocketAddress *)sa;

- (JavaNetProxy_TypeEnum *)type;

- (JavaNetSocketAddress *)address;

- (NSString *)description;

- (jboolean)isEqual:(id)obj;

- (NSUInteger)hash;

@end

FOUNDATION_EXPORT BOOL JavaNetProxy_initialized;
J2OBJC_STATIC_INIT(JavaNetProxy)

CF_EXTERN_C_BEGIN

FOUNDATION_EXPORT JavaNetProxy *JavaNetProxy_NO_PROXY_;
J2OBJC_STATIC_FIELD_GETTER(JavaNetProxy, NO_PROXY_, JavaNetProxy *)
CF_EXTERN_C_END

J2OBJC_TYPE_LITERAL_HEADER(JavaNetProxy)

typedef NS_ENUM(NSUInteger, JavaNetProxy_Type) {
  JavaNetProxy_Type_DIRECT = 0,
  JavaNetProxy_Type_HTTP = 1,
  JavaNetProxy_Type_SOCKS = 2,
};

@interface JavaNetProxy_TypeEnum : JavaLangEnum < NSCopying > {
}

- (instancetype)initWithNSString:(NSString *)__name
                         withInt:(jint)__ordinal;

+ (IOSObjectArray *)values;
FOUNDATION_EXPORT IOSObjectArray *JavaNetProxy_TypeEnum_values();

+ (JavaNetProxy_TypeEnum *)valueOfWithNSString:(NSString *)name;

FOUNDATION_EXPORT JavaNetProxy_TypeEnum *JavaNetProxy_TypeEnum_valueOfWithNSString_(NSString *name);
- (id)copyWithZone:(NSZone *)zone;

@end

FOUNDATION_EXPORT BOOL JavaNetProxy_TypeEnum_initialized;
J2OBJC_STATIC_INIT(JavaNetProxy_TypeEnum)

FOUNDATION_EXPORT JavaNetProxy_TypeEnum *JavaNetProxy_TypeEnum_values_[];

#define JavaNetProxy_TypeEnum_DIRECT JavaNetProxy_TypeEnum_values_[JavaNetProxy_Type_DIRECT]
J2OBJC_ENUM_CONSTANT_GETTER(JavaNetProxy_TypeEnum, DIRECT)

#define JavaNetProxy_TypeEnum_HTTP JavaNetProxy_TypeEnum_values_[JavaNetProxy_Type_HTTP]
J2OBJC_ENUM_CONSTANT_GETTER(JavaNetProxy_TypeEnum, HTTP)

#define JavaNetProxy_TypeEnum_SOCKS JavaNetProxy_TypeEnum_values_[JavaNetProxy_Type_SOCKS]
J2OBJC_ENUM_CONSTANT_GETTER(JavaNetProxy_TypeEnum, SOCKS)

J2OBJC_TYPE_LITERAL_HEADER(JavaNetProxy_TypeEnum)

#endif // _JavaNetProxy_H_
