//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: android/libcore/luni/src/main/java/java/lang/reflect/ParameterizedType.java
//

#ifndef _JavaLangReflectParameterizedType_H_
#define _JavaLangReflectParameterizedType_H_

@class IOSObjectArray;

#include "J2ObjC_header.h"
#include "java/lang/reflect/Type.h"

@protocol JavaLangReflectParameterizedType < JavaLangReflectType, NSObject, JavaObject >
- (IOSObjectArray *)getActualTypeArguments;

- (id<JavaLangReflectType>)getOwnerType;

- (id<JavaLangReflectType>)getRawType;

@end

J2OBJC_EMPTY_STATIC_INIT(JavaLangReflectParameterizedType)

J2OBJC_TYPE_LITERAL_HEADER(JavaLangReflectParameterizedType)

#endif // _JavaLangReflectParameterizedType_H_
