//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: android/libcore/luni/src/main/java/java/lang/reflect/UndeclaredThrowableException.java
//
//  Created by tball on 7/15/13.
//

#ifndef _JavaLangReflectUndeclaredThrowableException_H_
#define _JavaLangReflectUndeclaredThrowableException_H_

@class JavaLangThrowable;

#import "JreEmulation.h"
#include "java/lang/RuntimeException.h"

#define JavaLangReflectUndeclaredThrowableException_serialVersionUID 330127114055056639

@interface JavaLangReflectUndeclaredThrowableException : JavaLangRuntimeException {
 @public
  JavaLangThrowable *undeclaredThrowable_;
}

@property (nonatomic, retain) JavaLangThrowable *undeclaredThrowable;

- (id)initWithJavaLangThrowable:(JavaLangThrowable *)exception;
- (id)initWithJavaLangThrowable:(JavaLangThrowable *)exception
                   withNSString:(NSString *)detailMessage;
- (JavaLangThrowable *)getUndeclaredThrowable;
- (JavaLangThrowable *)getCause;
@end

#endif // _JavaLangReflectUndeclaredThrowableException_H_
