//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: android/libcore/luni/src/main/java/java/security/InvalidKeyException.java
//

#ifndef _JavaSecurityInvalidKeyException_H_
#define _JavaSecurityInvalidKeyException_H_

@class JavaLangThrowable;

#include "J2ObjC_header.h"
#include "java/security/KeyException.h"

#define JavaSecurityInvalidKeyException_serialVersionUID 5698479920593359816LL

@interface JavaSecurityInvalidKeyException : JavaSecurityKeyException {
}

- (instancetype)initWithNSString:(NSString *)msg;

- (instancetype)init;

- (instancetype)initWithNSString:(NSString *)message
           withJavaLangThrowable:(JavaLangThrowable *)cause;

- (instancetype)initWithJavaLangThrowable:(JavaLangThrowable *)cause;

@end

J2OBJC_EMPTY_STATIC_INIT(JavaSecurityInvalidKeyException)

CF_EXTERN_C_BEGIN

J2OBJC_STATIC_FIELD_GETTER(JavaSecurityInvalidKeyException, serialVersionUID, jlong)
CF_EXTERN_C_END

J2OBJC_TYPE_LITERAL_HEADER(JavaSecurityInvalidKeyException)

#endif // _JavaSecurityInvalidKeyException_H_
