//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: android/libcore/luni/src/main/java/java/security/PrivilegedAction.java
//

#ifndef _JavaSecurityPrivilegedAction_H_
#define _JavaSecurityPrivilegedAction_H_

#include "J2ObjC_header.h"

@protocol JavaSecurityPrivilegedAction < NSObject, JavaObject >

- (id)run;

@end

J2OBJC_EMPTY_STATIC_INIT(JavaSecurityPrivilegedAction)

J2OBJC_TYPE_LITERAL_HEADER(JavaSecurityPrivilegedAction)

#endif // _JavaSecurityPrivilegedAction_H_
