//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: android/libcore/luni/src/main/java/java/security/spec/ECField.java
//

#ifndef _JavaSecuritySpecECField_H_
#define _JavaSecuritySpecECField_H_

#include "J2ObjC_header.h"

@protocol JavaSecuritySpecECField < NSObject, JavaObject >

- (jint)getFieldSize;

@end

J2OBJC_EMPTY_STATIC_INIT(JavaSecuritySpecECField)

J2OBJC_TYPE_LITERAL_HEADER(JavaSecuritySpecECField)

#endif // _JavaSecuritySpecECField_H_
