//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: apache_harmony/classlib/modules/luni/src/main/java/java/lang/ArrayIndexOutOfBoundsException.java
//
//  Created by tball on 7/15/13.
//

#ifndef _JavaLangArrayIndexOutOfBoundsException_H_
#define _JavaLangArrayIndexOutOfBoundsException_H_

#import "JreEmulation.h"
#include "java/lang/IndexOutOfBoundsException.h"

#define JavaLangArrayIndexOutOfBoundsException_serialVersionUID -5116101128118950844

@interface JavaLangArrayIndexOutOfBoundsException : JavaLangIndexOutOfBoundsException {
}

- (id)init;
- (id)initWithInt:(int)index;
- (id)initWithNSString:(NSString *)detailMessage;
@end

#endif // _JavaLangArrayIndexOutOfBoundsException_H_
