//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: /Users/krasnocka/Downloads/j2objc-master/testing/mockito/build_result/java/org/mockito/internal/matchers/Matches.java
//

#ifndef _OrgMockitoInternalMatchersMatches_H_
#define _OrgMockitoInternalMatchersMatches_H_

@protocol OrgHamcrestDescription;

#include "J2ObjC_header.h"
#include "java/io/Serializable.h"
#include "org/mockito/ArgumentMatcher.h"

#define OrgMockitoInternalMatchersMatches_serialVersionUID 8787704593379472029LL

@interface OrgMockitoInternalMatchersMatches : OrgMockitoArgumentMatcher < JavaIoSerializable > {
}

- (instancetype)initWithNSString:(NSString *)regex;

- (jboolean)matchesWithId:(id)actual;

- (void)describeToWithOrgHamcrestDescription:(id<OrgHamcrestDescription>)description_;

@end

J2OBJC_EMPTY_STATIC_INIT(OrgMockitoInternalMatchersMatches)

CF_EXTERN_C_BEGIN

J2OBJC_STATIC_FIELD_GETTER(OrgMockitoInternalMatchersMatches, serialVersionUID, jlong)
CF_EXTERN_C_END

J2OBJC_TYPE_LITERAL_HEADER(OrgMockitoInternalMatchersMatches)

#endif // _OrgMockitoInternalMatchersMatches_H_
