//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: /Users/krasnocka/Downloads/j2objc-master/junit/build_result/java/junit/framework/Protectable.java
//

#ifndef _JunitFrameworkProtectable_H_
#define _JunitFrameworkProtectable_H_

#include "J2ObjC_header.h"

@protocol JunitFrameworkProtectable < NSObject, JavaObject >

- (void)protect;

@end

J2OBJC_EMPTY_STATIC_INIT(JunitFrameworkProtectable)

J2OBJC_TYPE_LITERAL_HEADER(JunitFrameworkProtectable)

#endif // _JunitFrameworkProtectable_H_
