//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: /Users/krasnocka/Downloads/j2objc-master/junit/build_result/java/junit/framework/Test.java
//

#ifndef _JunitFrameworkTest_H_
#define _JunitFrameworkTest_H_

@class JunitFrameworkTestResult;

#include "J2ObjC_header.h"

@protocol JunitFrameworkTest < NSObject, JavaObject >

- (jint)countTestCases;

- (void)runWithJunitFrameworkTestResult:(JunitFrameworkTestResult *)result;

@end

J2OBJC_EMPTY_STATIC_INIT(JunitFrameworkTest)

J2OBJC_TYPE_LITERAL_HEADER(JunitFrameworkTest)

#endif // _JunitFrameworkTest_H_
