//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: apache_harmony/classlib/modules/math/src/main/java/java/math/MathContext.java
//

#ifndef _JavaMathMathContext_H_
#define _JavaMathMathContext_H_

@class IOSCharArray;
@class JavaMathRoundingModeEnum;

#include "J2ObjC_header.h"
#include "java/io/Serializable.h"

#define JavaMathMathContext_serialVersionUID 5579720004786848255LL

@interface JavaMathMathContext : NSObject < JavaIoSerializable > {
}

- (instancetype)initWithInt:(jint)precision;

- (instancetype)initWithInt:(jint)precision
withJavaMathRoundingModeEnum:(JavaMathRoundingModeEnum *)roundingMode;

- (instancetype)initWithNSString:(NSString *)val;

- (jint)getPrecision;

- (JavaMathRoundingModeEnum *)getRoundingMode;

- (jboolean)isEqual:(id)x;

- (NSUInteger)hash;

- (NSString *)description;

@end

FOUNDATION_EXPORT BOOL JavaMathMathContext_initialized;
J2OBJC_STATIC_INIT(JavaMathMathContext)

CF_EXTERN_C_BEGIN

FOUNDATION_EXPORT JavaMathMathContext *JavaMathMathContext_DECIMAL128_;
J2OBJC_STATIC_FIELD_GETTER(JavaMathMathContext, DECIMAL128_, JavaMathMathContext *)

FOUNDATION_EXPORT JavaMathMathContext *JavaMathMathContext_DECIMAL32_;
J2OBJC_STATIC_FIELD_GETTER(JavaMathMathContext, DECIMAL32_, JavaMathMathContext *)

FOUNDATION_EXPORT JavaMathMathContext *JavaMathMathContext_DECIMAL64_;
J2OBJC_STATIC_FIELD_GETTER(JavaMathMathContext, DECIMAL64_, JavaMathMathContext *)

FOUNDATION_EXPORT JavaMathMathContext *JavaMathMathContext_UNLIMITED_;
J2OBJC_STATIC_FIELD_GETTER(JavaMathMathContext, UNLIMITED_, JavaMathMathContext *)

J2OBJC_STATIC_FIELD_GETTER(JavaMathMathContext, serialVersionUID, jlong)

FOUNDATION_EXPORT IOSCharArray *JavaMathMathContext_chPrecision_;
J2OBJC_STATIC_FIELD_GETTER(JavaMathMathContext, chPrecision_, IOSCharArray *)

FOUNDATION_EXPORT IOSCharArray *JavaMathMathContext_chRoundingMode_;
J2OBJC_STATIC_FIELD_GETTER(JavaMathMathContext, chRoundingMode_, IOSCharArray *)
CF_EXTERN_C_END

J2OBJC_TYPE_LITERAL_HEADER(JavaMathMathContext)

#endif // _JavaMathMathContext_H_
