//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: /Users/krasnocka/Downloads/j2objc-master/junit/build_result/java/org/hamcrest/StringDescription.java
//

#ifndef _OrgHamcrestStringDescription_H_
#define _OrgHamcrestStringDescription_H_

@protocol JavaLangAppendable;
@protocol OrgHamcrestSelfDescribing;

#include "J2ObjC_header.h"
#include "org/hamcrest/BaseDescription.h"

@interface OrgHamcrestStringDescription : OrgHamcrestBaseDescription {
}

- (instancetype)init;

- (instancetype)initWithJavaLangAppendable:(id<JavaLangAppendable>)outArg;

+ (NSString *)toStringWithOrgHamcrestSelfDescribing:(id<OrgHamcrestSelfDescribing>)value;

+ (NSString *)asStringWithOrgHamcrestSelfDescribing:(id<OrgHamcrestSelfDescribing>)selfDescribing;

- (void)appendWithNSString:(NSString *)str;

- (void)appendWithChar:(jchar)c;

- (NSString *)description;

@end

J2OBJC_EMPTY_STATIC_INIT(OrgHamcrestStringDescription)

CF_EXTERN_C_BEGIN

FOUNDATION_EXPORT NSString *OrgHamcrestStringDescription_toStringWithOrgHamcrestSelfDescribing_(id<OrgHamcrestSelfDescribing> value);

FOUNDATION_EXPORT NSString *OrgHamcrestStringDescription_asStringWithOrgHamcrestSelfDescribing_(id<OrgHamcrestSelfDescribing> selfDescribing);
CF_EXTERN_C_END

J2OBJC_TYPE_LITERAL_HEADER(OrgHamcrestStringDescription)

#endif // _OrgHamcrestStringDescription_H_
