//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: /Users/krasnocka/Downloads/j2objc-master/junit/build_result/java/org/hamcrest/core/AllOf.java
//

#ifndef _OrgHamcrestCoreAllOf_H_
#define _OrgHamcrestCoreAllOf_H_

@class IOSObjectArray;
@protocol JavaLangIterable;
@protocol OrgHamcrestDescription;
@protocol OrgHamcrestMatcher;

#include "J2ObjC_header.h"
#include "org/hamcrest/BaseMatcher.h"

@interface OrgHamcrestCoreAllOf : OrgHamcrestBaseMatcher {
}

- (instancetype)initWithJavaLangIterable:(id<JavaLangIterable>)matchers;

- (jboolean)matchesWithId:(id)o;

- (void)describeToWithOrgHamcrestDescription:(id<OrgHamcrestDescription>)description_;

+ (id<OrgHamcrestMatcher>)allOfWithOrgHamcrestMatcherArray:(IOSObjectArray *)matchers;

+ (id<OrgHamcrestMatcher>)allOfWithJavaLangIterable:(id<JavaLangIterable>)matchers;

@end

J2OBJC_EMPTY_STATIC_INIT(OrgHamcrestCoreAllOf)

CF_EXTERN_C_BEGIN

FOUNDATION_EXPORT id<OrgHamcrestMatcher> OrgHamcrestCoreAllOf_allOfWithOrgHamcrestMatcherArray_(IOSObjectArray *matchers);

FOUNDATION_EXPORT id<OrgHamcrestMatcher> OrgHamcrestCoreAllOf_allOfWithJavaLangIterable_(id<JavaLangIterable> matchers);
CF_EXTERN_C_END

J2OBJC_TYPE_LITERAL_HEADER(OrgHamcrestCoreAllOf)

#endif // _OrgHamcrestCoreAllOf_H_
