//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: android/libcore/luni/src/main/java/java/util/zip/CheckedInputStream.java
//

#ifndef _JavaUtilZipCheckedInputStream_H_
#define _JavaUtilZipCheckedInputStream_H_

@class IOSByteArray;
@class JavaIoInputStream;
@protocol JavaUtilZipChecksum;

#include "J2ObjC_header.h"
#include "java/io/FilterInputStream.h"

@interface JavaUtilZipCheckedInputStream : JavaIoFilterInputStream {
}

- (instancetype)initWithJavaIoInputStream:(JavaIoInputStream *)is
                  withJavaUtilZipChecksum:(id<JavaUtilZipChecksum>)csum;

- (jint)read;

- (jint)readWithByteArray:(IOSByteArray *)buffer
                  withInt:(jint)byteOffset
                  withInt:(jint)byteCount;

- (id<JavaUtilZipChecksum>)getChecksum;

- (jlong)skipWithLong:(jlong)byteCount;

@end

J2OBJC_EMPTY_STATIC_INIT(JavaUtilZipCheckedInputStream)

CF_EXTERN_C_BEGIN
CF_EXTERN_C_END

J2OBJC_TYPE_LITERAL_HEADER(JavaUtilZipCheckedInputStream)

#endif // _JavaUtilZipCheckedInputStream_H_
