//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: android/libcore/luni/src/main/java/org/xml/sax/SAXNotSupportedException.java
//

#ifndef _OrgXmlSaxSAXNotSupportedException_H_
#define _OrgXmlSaxSAXNotSupportedException_H_

#include "J2ObjC_header.h"
#include "org/xml/sax/SAXException.h"

@interface OrgXmlSaxSAXNotSupportedException : OrgXmlSaxSAXException {
}

- (instancetype)init;

- (instancetype)initWithNSString:(NSString *)message;

@end

J2OBJC_EMPTY_STATIC_INIT(OrgXmlSaxSAXNotSupportedException)

CF_EXTERN_C_BEGIN
CF_EXTERN_C_END

J2OBJC_TYPE_LITERAL_HEADER(OrgXmlSaxSAXNotSupportedException)

#endif // _OrgXmlSaxSAXNotSupportedException_H_
