//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: android/libcore/luni/src/main/java/java/util/ArrayDeque.java
//

#ifndef _JavaUtilArrayDeque_H_
#define _JavaUtilArrayDeque_H_

@class IOSObjectArray;
@class JavaIoObjectInputStream;
@class JavaIoObjectOutputStream;
@protocol JavaUtilCollection;

#include "J2ObjC_header.h"
#include "java/io/Serializable.h"
#include "java/util/AbstractCollection.h"
#include "java/util/Deque.h"
#include "java/util/Iterator.h"

#define JavaUtilArrayDeque_MIN_INITIAL_CAPACITY 8
#define JavaUtilArrayDeque_serialVersionUID 2340985798034038923LL

@interface JavaUtilArrayDeque : JavaUtilAbstractCollection < JavaUtilDeque, NSCopying, JavaIoSerializable > {
}

- (instancetype)init;

- (instancetype)initWithInt:(jint)numElements;

- (instancetype)initWithJavaUtilCollection:(id<JavaUtilCollection>)c;

- (void)addFirstWithId:(id)e;

- (void)addLastWithId:(id)e;

- (jboolean)offerFirstWithId:(id)e;

- (jboolean)offerLastWithId:(id)e;

- (id)removeFirst;

- (id)removeLast;

- (id)pollFirst;

- (id)pollLast;

- (id)getFirst;

- (id)getLast;

- (id)peekFirst;

- (id)peekLast;

- (jboolean)removeFirstOccurrenceWithId:(id)o;

- (jboolean)removeLastOccurrenceWithId:(id)o;

- (jboolean)addWithId:(id)e;

- (jboolean)offerWithId:(id)e;

- (id)remove;

- (id)poll;

- (id)element;

- (id)peek;

- (void)pushWithId:(id)e;

- (id)pop;

- (jint)size;

- (jboolean)isEmpty;

- (id<JavaUtilIterator>)iterator;

- (id<JavaUtilIterator>)descendingIterator;

- (jboolean)containsWithId:(id)o;

- (jboolean)removeWithId:(id)o;

- (void)clear;

- (IOSObjectArray *)toArray;

- (IOSObjectArray *)toArrayWithNSObjectArray:(IOSObjectArray *)a;

- (JavaUtilArrayDeque *)clone;


@end

J2OBJC_EMPTY_STATIC_INIT(JavaUtilArrayDeque)

CF_EXTERN_C_BEGIN

J2OBJC_STATIC_FIELD_GETTER(JavaUtilArrayDeque, MIN_INITIAL_CAPACITY, jint)

J2OBJC_STATIC_FIELD_GETTER(JavaUtilArrayDeque, serialVersionUID, jlong)
CF_EXTERN_C_END

J2OBJC_TYPE_LITERAL_HEADER(JavaUtilArrayDeque)

@interface JavaUtilArrayDeque_DeqIterator : NSObject < JavaUtilIterator > {
}

- (jboolean)hasNext;

- (id)next;

- (void)remove;

- (instancetype)initWithJavaUtilArrayDeque:(JavaUtilArrayDeque *)outer$;

@end

J2OBJC_EMPTY_STATIC_INIT(JavaUtilArrayDeque_DeqIterator)

CF_EXTERN_C_BEGIN
CF_EXTERN_C_END

J2OBJC_TYPE_LITERAL_HEADER(JavaUtilArrayDeque_DeqIterator)

@interface JavaUtilArrayDeque_DescendingIterator : NSObject < JavaUtilIterator > {
}

- (jboolean)hasNext;

- (id)next;

- (void)remove;

- (instancetype)initWithJavaUtilArrayDeque:(JavaUtilArrayDeque *)outer$;

@end

J2OBJC_EMPTY_STATIC_INIT(JavaUtilArrayDeque_DescendingIterator)

CF_EXTERN_C_BEGIN
CF_EXTERN_C_END

J2OBJC_TYPE_LITERAL_HEADER(JavaUtilArrayDeque_DescendingIterator)

#endif // _JavaUtilArrayDeque_H_
