//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: android/libcore/luni/src/main/java/java/util/EmptyStackException.java
//

#ifndef _JavaUtilEmptyStackException_H_
#define _JavaUtilEmptyStackException_H_

#include "J2ObjC_header.h"
#include "java/lang/RuntimeException.h"

#define JavaUtilEmptyStackException_serialVersionUID 5084686378493302095LL

@interface JavaUtilEmptyStackException : JavaLangRuntimeException {
}

- (instancetype)init;

@end

J2OBJC_EMPTY_STATIC_INIT(JavaUtilEmptyStackException)

CF_EXTERN_C_BEGIN

J2OBJC_STATIC_FIELD_GETTER(JavaUtilEmptyStackException, serialVersionUID, jlong)
CF_EXTERN_C_END

J2OBJC_TYPE_LITERAL_HEADER(JavaUtilEmptyStackException)

#endif // _JavaUtilEmptyStackException_H_
