//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: android/libcore/luni/src/main/java/java/util/FormattableFlags.java
//

#ifndef _JavaUtilFormattableFlags_H_
#define _JavaUtilFormattableFlags_H_

#include "J2ObjC_header.h"

#define JavaUtilFormattableFlags_ALTERNATE 4
#define JavaUtilFormattableFlags_LEFT_JUSTIFY 1
#define JavaUtilFormattableFlags_UPPERCASE 2

@interface JavaUtilFormattableFlags : NSObject {
}

@end

J2OBJC_EMPTY_STATIC_INIT(JavaUtilFormattableFlags)

CF_EXTERN_C_BEGIN

J2OBJC_STATIC_FIELD_GETTER(JavaUtilFormattableFlags, LEFT_JUSTIFY, jint)

J2OBJC_STATIC_FIELD_GETTER(JavaUtilFormattableFlags, UPPERCASE, jint)

J2OBJC_STATIC_FIELD_GETTER(JavaUtilFormattableFlags, ALTERNATE, jint)
CF_EXTERN_C_END

J2OBJC_TYPE_LITERAL_HEADER(JavaUtilFormattableFlags)

#endif // _JavaUtilFormattableFlags_H_
