//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: android/libcore/luni/src/main/java/java/util/InvalidPropertiesFormatException.java
//

#ifndef _JavaUtilInvalidPropertiesFormatException_H_
#define _JavaUtilInvalidPropertiesFormatException_H_

@class JavaIoObjectInputStream;
@class JavaIoObjectOutputStream;
@class JavaLangThrowable;

#include "J2ObjC_header.h"
#include "java/io/IOException.h"

#define JavaUtilInvalidPropertiesFormatException_serialVersionUID 7763056076009360219LL

@interface JavaUtilInvalidPropertiesFormatException : JavaIoIOException {
}

- (instancetype)initWithNSString:(NSString *)m;

- (instancetype)initWithJavaLangThrowable:(JavaLangThrowable *)c;

@end

J2OBJC_EMPTY_STATIC_INIT(JavaUtilInvalidPropertiesFormatException)

CF_EXTERN_C_BEGIN

J2OBJC_STATIC_FIELD_GETTER(JavaUtilInvalidPropertiesFormatException, serialVersionUID, jlong)
CF_EXTERN_C_END

J2OBJC_TYPE_LITERAL_HEADER(JavaUtilInvalidPropertiesFormatException)

#endif // _JavaUtilInvalidPropertiesFormatException_H_
