//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: android/libcore/luni/src/main/java/java/util/ListResourceBundle.java
//

#ifndef _JavaUtilListResourceBundle_H_
#define _JavaUtilListResourceBundle_H_

@class IOSObjectArray;
@class JavaUtilHashMap;
@protocol JavaUtilIterator;
@protocol JavaUtilSet;

#include "J2ObjC_header.h"
#include "java/util/Enumeration.h"
#include "java/util/ResourceBundle.h"

@interface JavaUtilListResourceBundle : JavaUtilResourceBundle {
 @public
  JavaUtilHashMap *table_;
}

- (instancetype)init;

- (IOSObjectArray *)getContents;

- (id<JavaUtilEnumeration>)getKeys;

- (id)handleGetObjectWithNSString:(NSString *)key;

- (id<JavaUtilSet>)handleKeySet;

@end

J2OBJC_EMPTY_STATIC_INIT(JavaUtilListResourceBundle)

J2OBJC_FIELD_SETTER(JavaUtilListResourceBundle, table_, JavaUtilHashMap *)

CF_EXTERN_C_BEGIN
CF_EXTERN_C_END

J2OBJC_TYPE_LITERAL_HEADER(JavaUtilListResourceBundle)

@interface JavaUtilListResourceBundle_$1 : NSObject < JavaUtilEnumeration > {
 @public
  id<JavaUtilIterator> local_;
  id<JavaUtilEnumeration> pEnum_;
  NSString *nextElement__;
}

- (jboolean)hasMoreElements;

- (NSString *)nextElement;

- (instancetype)initWithJavaUtilListResourceBundle:(JavaUtilListResourceBundle *)outer$;

@end

J2OBJC_EMPTY_STATIC_INIT(JavaUtilListResourceBundle_$1)

J2OBJC_FIELD_SETTER(JavaUtilListResourceBundle_$1, local_, id<JavaUtilIterator>)
J2OBJC_FIELD_SETTER(JavaUtilListResourceBundle_$1, pEnum_, id<JavaUtilEnumeration>)
J2OBJC_FIELD_SETTER(JavaUtilListResourceBundle_$1, nextElement__, NSString *)

CF_EXTERN_C_BEGIN
CF_EXTERN_C_END

J2OBJC_TYPE_LITERAL_HEADER(JavaUtilListResourceBundle_$1)

@interface JavaUtilListResourceBundle_$2 : NSObject < JavaUtilEnumeration > {
 @public
  id<JavaUtilIterator> it_;
}

- (jboolean)hasMoreElements;

- (NSString *)nextElement;

- (instancetype)initWithJavaUtilListResourceBundle:(JavaUtilListResourceBundle *)outer$;

@end

J2OBJC_EMPTY_STATIC_INIT(JavaUtilListResourceBundle_$2)

J2OBJC_FIELD_SETTER(JavaUtilListResourceBundle_$2, it_, id<JavaUtilIterator>)

CF_EXTERN_C_BEGIN
CF_EXTERN_C_END

J2OBJC_TYPE_LITERAL_HEADER(JavaUtilListResourceBundle_$2)

#endif // _JavaUtilListResourceBundle_H_
