//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: android/libcore/luni/src/main/java/java/util/Stack.java
//

#ifndef _JavaUtilStack_H_
#define _JavaUtilStack_H_

#include "J2ObjC_header.h"
#include "java/util/Vector.h"

#define JavaUtilStack_serialVersionUID 1224463164541339165LL

@interface JavaUtilStack : JavaUtilVector {
}

- (instancetype)init;

- (jboolean)empty;

- (id)peek;

- (id)pop;

- (id)pushWithId:(id)object;

- (jint)searchWithId:(id)o;


@end

J2OBJC_EMPTY_STATIC_INIT(JavaUtilStack)

CF_EXTERN_C_BEGIN

J2OBJC_STATIC_FIELD_GETTER(JavaUtilStack, serialVersionUID, jlong)
CF_EXTERN_C_END

J2OBJC_TYPE_LITERAL_HEADER(JavaUtilStack)

#endif // _JavaUtilStack_H_
