//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: android/libcore/luni/src/main/java/libcore/io/ErrnoException.java
//
//  Created by tball on 7/15/13.
//

#ifndef _LibcoreIoErrnoException_H_
#define _LibcoreIoErrnoException_H_

@class JavaIoIOException;
@class JavaLangThrowable;

#import "JreEmulation.h"
#include "java/lang/Exception.h"

@interface LibcoreIoErrnoException : JavaLangException {
 @public
  NSString *functionName_;
  int errno__;
}

@property (nonatomic, copy) NSString *functionName;
@property (nonatomic, assign) int errno_;

- (id)initWithNSString:(NSString *)functionName
               withInt:(int)errno_;
- (id)initWithNSString:(NSString *)functionName
               withInt:(int)errno_
 withJavaLangThrowable:(JavaLangThrowable *)cause;
- (NSString *)getMessage;
- (JavaIoIOException *)rethrowAsIOException;
@end

#endif // _LibcoreIoErrnoException_H_
