//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: android/libcore/luni/src/main/java/libcore/io/IoUtils.java
//

#ifndef _LibcoreIoIoUtils_H_
#define _LibcoreIoIoUtils_H_

@class IOSByteArray;
@class JavaIoByteArrayOutputStream;
@class JavaIoFile;
@class JavaIoFileDescriptor;
@class JavaNetSocket;
@protocol JavaLangAutoCloseable;

#include "J2ObjC_header.h"

@interface LibcoreIoIoUtils : NSObject {
}

+ (void)closeWithJavaIoFileDescriptor:(JavaIoFileDescriptor *)fd;

+ (void)closeQuietlyWithJavaLangAutoCloseable:(id<JavaLangAutoCloseable>)closeable;

+ (void)closeQuietlyWithJavaIoFileDescriptor:(JavaIoFileDescriptor *)fd;

+ (void)closeQuietlyWithJavaNetSocket:(JavaNetSocket *)socket;

+ (void)setBlockingWithJavaIoFileDescriptor:(JavaIoFileDescriptor *)fd
                                withBoolean:(jboolean)blocking;

+ (IOSByteArray *)readFileAsByteArrayWithNSString:(NSString *)path;

+ (NSString *)readFileAsStringWithNSString:(NSString *)path;

+ (void)deleteContentsWithJavaIoFile:(JavaIoFile *)dir;

+ (jboolean)canOpenReadOnlyWithNSString:(NSString *)path;

+ (void)throwInterruptedIoException;

@end

J2OBJC_EMPTY_STATIC_INIT(LibcoreIoIoUtils)

CF_EXTERN_C_BEGIN

FOUNDATION_EXPORT void LibcoreIoIoUtils_closeWithJavaIoFileDescriptor_(JavaIoFileDescriptor *fd);

FOUNDATION_EXPORT void LibcoreIoIoUtils_closeQuietlyWithJavaLangAutoCloseable_(id<JavaLangAutoCloseable> closeable);

FOUNDATION_EXPORT void LibcoreIoIoUtils_closeQuietlyWithJavaIoFileDescriptor_(JavaIoFileDescriptor *fd);

FOUNDATION_EXPORT void LibcoreIoIoUtils_closeQuietlyWithJavaNetSocket_(JavaNetSocket *socket);

FOUNDATION_EXPORT void LibcoreIoIoUtils_setBlockingWithJavaIoFileDescriptor_withBoolean_(JavaIoFileDescriptor *fd, jboolean blocking);

FOUNDATION_EXPORT IOSByteArray *LibcoreIoIoUtils_readFileAsByteArrayWithNSString_(NSString *path);

FOUNDATION_EXPORT NSString *LibcoreIoIoUtils_readFileAsStringWithNSString_(NSString *path);

FOUNDATION_EXPORT void LibcoreIoIoUtils_deleteContentsWithJavaIoFile_(JavaIoFile *dir);

FOUNDATION_EXPORT jboolean LibcoreIoIoUtils_canOpenReadOnlyWithNSString_(NSString *path);

FOUNDATION_EXPORT void LibcoreIoIoUtils_throwInterruptedIoException();
CF_EXTERN_C_END

J2OBJC_TYPE_LITERAL_HEADER(LibcoreIoIoUtils)

#endif // _LibcoreIoIoUtils_H_
