//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: /Users/krasnocka/Downloads/j2objc-master/guava/sources/com/google/common/io/ByteStreams.java
//

#include "J2ObjC_header.h"

#if !ComGoogleCommonIoByteStreams_RESTRICT
#define ComGoogleCommonIoByteStreams_INCLUDE_ALL 1
#endif
#undef ComGoogleCommonIoByteStreams_RESTRICT
#if !defined (_ComGoogleCommonIoByteStreams_) && (ComGoogleCommonIoByteStreams_INCLUDE_ALL || ComGoogleCommonIoByteStreams_INCLUDE)
#define _ComGoogleCommonIoByteStreams_

@class ComGoogleCommonHashHashCode;
@class ComGoogleCommonIoByteSink;
@class ComGoogleCommonIoByteSource;
@class IOSByteArray;
@class IOSObjectArray;
@class JavaIoInputStream;
@class JavaIoOutputStream;
@protocol ComGoogleCommonHashHashFunction;
@protocol ComGoogleCommonIoByteArrayDataInput;
@protocol ComGoogleCommonIoByteArrayDataOutput;
@protocol ComGoogleCommonIoByteProcessor;
@protocol ComGoogleCommonIoInputSupplier;
@protocol ComGoogleCommonIoOutputSupplier;
@protocol JavaLangIterable;
@protocol JavaUtilZipChecksum;


#define ComGoogleCommonIoByteStreams_BUF_SIZE 4096

@interface ComGoogleCommonIoByteStreams : NSObject {
}

+ (id<ComGoogleCommonIoInputSupplier>)newInputStreamSupplierWithByteArray:(IOSByteArray *)b OBJC_METHOD_FAMILY_NONE;

+ (id<ComGoogleCommonIoInputSupplier>)newInputStreamSupplierWithByteArray:(IOSByteArray *)b
                                                                  withInt:(jint)off
                                                                  withInt:(jint)len OBJC_METHOD_FAMILY_NONE;

+ (ComGoogleCommonIoByteSource *)asByteSourceWithByteArray:(IOSByteArray *)b;

+ (void)writeWithByteArray:(IOSByteArray *)from
withComGoogleCommonIoOutputSupplier:(id<ComGoogleCommonIoOutputSupplier>)to;

+ (jlong)copy__WithComGoogleCommonIoInputSupplier:(id<ComGoogleCommonIoInputSupplier>)from
              withComGoogleCommonIoOutputSupplier:(id<ComGoogleCommonIoOutputSupplier>)to OBJC_METHOD_FAMILY_NONE;

+ (jlong)copy__WithComGoogleCommonIoInputSupplier:(id<ComGoogleCommonIoInputSupplier>)from
                           withJavaIoOutputStream:(JavaIoOutputStream *)to OBJC_METHOD_FAMILY_NONE;

+ (jlong)copy__WithJavaIoInputStream:(JavaIoInputStream *)from
 withComGoogleCommonIoOutputSupplier:(id<ComGoogleCommonIoOutputSupplier>)to OBJC_METHOD_FAMILY_NONE;

+ (jlong)copy__WithJavaIoInputStream:(JavaIoInputStream *)from
              withJavaIoOutputStream:(JavaIoOutputStream *)to OBJC_METHOD_FAMILY_NONE;

+ (IOSByteArray *)toByteArrayWithJavaIoInputStream:(JavaIoInputStream *)inArg;

+ (IOSByteArray *)toByteArrayWithComGoogleCommonIoInputSupplier:(id<ComGoogleCommonIoInputSupplier>)supplier;

+ (id<ComGoogleCommonIoByteArrayDataInput>)newDataInputWithByteArray:(IOSByteArray *)bytes OBJC_METHOD_FAMILY_NONE;

+ (id<ComGoogleCommonIoByteArrayDataInput>)newDataInputWithByteArray:(IOSByteArray *)bytes
                                                             withInt:(jint)start OBJC_METHOD_FAMILY_NONE;

+ (id<ComGoogleCommonIoByteArrayDataOutput>)newDataOutput OBJC_METHOD_FAMILY_NONE;

+ (id<ComGoogleCommonIoByteArrayDataOutput>)newDataOutputWithInt:(jint)size OBJC_METHOD_FAMILY_NONE;

+ (JavaIoOutputStream *)nullOutputStream;

+ (JavaIoInputStream *)limitWithJavaIoInputStream:(JavaIoInputStream *)inArg
                                         withLong:(jlong)limit;

+ (jlong)lengthWithComGoogleCommonIoInputSupplier:(id<ComGoogleCommonIoInputSupplier>)supplier;

+ (jboolean)equalWithComGoogleCommonIoInputSupplier:(id<ComGoogleCommonIoInputSupplier>)supplier1
                 withComGoogleCommonIoInputSupplier:(id<ComGoogleCommonIoInputSupplier>)supplier2;

+ (void)readFullyWithJavaIoInputStream:(JavaIoInputStream *)inArg
                         withByteArray:(IOSByteArray *)b;

+ (void)readFullyWithJavaIoInputStream:(JavaIoInputStream *)inArg
                         withByteArray:(IOSByteArray *)b
                               withInt:(jint)off
                               withInt:(jint)len;

+ (void)skipFullyWithJavaIoInputStream:(JavaIoInputStream *)inArg
                              withLong:(jlong)n;

+ (id)readBytesWithComGoogleCommonIoInputSupplier:(id<ComGoogleCommonIoInputSupplier>)supplier
               withComGoogleCommonIoByteProcessor:(id<ComGoogleCommonIoByteProcessor>)processor;

+ (id)readBytesWithJavaIoInputStream:(JavaIoInputStream *)input
  withComGoogleCommonIoByteProcessor:(id<ComGoogleCommonIoByteProcessor>)processor;

+ (jlong)getChecksumWithComGoogleCommonIoInputSupplier:(id<ComGoogleCommonIoInputSupplier>)supplier
                               withJavaUtilZipChecksum:(id<JavaUtilZipChecksum>)checksum;

+ (ComGoogleCommonHashHashCode *)hash__WithComGoogleCommonIoInputSupplier:(id<ComGoogleCommonIoInputSupplier>)supplier
                                      withComGoogleCommonHashHashFunction:(id<ComGoogleCommonHashHashFunction>)hashFunction;

+ (jint)readWithJavaIoInputStream:(JavaIoInputStream *)inArg
                    withByteArray:(IOSByteArray *)b
                          withInt:(jint)off
                          withInt:(jint)len;

+ (id<ComGoogleCommonIoInputSupplier>)sliceWithComGoogleCommonIoInputSupplier:(id<ComGoogleCommonIoInputSupplier>)supplier
                                                                     withLong:(jlong)offset
                                                                     withLong:(jlong)length;

+ (id<ComGoogleCommonIoInputSupplier>)joinWithJavaLangIterable:(id<JavaLangIterable>)suppliers;

+ (id<ComGoogleCommonIoInputSupplier>)joinWithComGoogleCommonIoInputSupplierArray:(IOSObjectArray *)suppliers;

+ (id<ComGoogleCommonIoInputSupplier>)asInputSupplierWithComGoogleCommonIoByteSource:(ComGoogleCommonIoByteSource *)source;

+ (id<ComGoogleCommonIoOutputSupplier>)asOutputSupplierWithComGoogleCommonIoByteSink:(ComGoogleCommonIoByteSink *)sink;

+ (ComGoogleCommonIoByteSource *)asByteSourceWithComGoogleCommonIoInputSupplier:(id<ComGoogleCommonIoInputSupplier>)supplier;

+ (ComGoogleCommonIoByteSink *)asByteSinkWithComGoogleCommonIoOutputSupplier:(id<ComGoogleCommonIoOutputSupplier>)supplier;

@end

FOUNDATION_EXPORT BOOL ComGoogleCommonIoByteStreams_initialized;
J2OBJC_STATIC_INIT(ComGoogleCommonIoByteStreams)

CF_EXTERN_C_BEGIN

FOUNDATION_EXPORT id<ComGoogleCommonIoInputSupplier> ComGoogleCommonIoByteStreams_newInputStreamSupplierWithByteArray_(IOSByteArray *b);

FOUNDATION_EXPORT id<ComGoogleCommonIoInputSupplier> ComGoogleCommonIoByteStreams_newInputStreamSupplierWithByteArray_withInt_withInt_(IOSByteArray *b, jint off, jint len);

FOUNDATION_EXPORT ComGoogleCommonIoByteSource *ComGoogleCommonIoByteStreams_asByteSourceWithByteArray_(IOSByteArray *b);

FOUNDATION_EXPORT void ComGoogleCommonIoByteStreams_writeWithByteArray_withComGoogleCommonIoOutputSupplier_(IOSByteArray *from, id<ComGoogleCommonIoOutputSupplier> to);

FOUNDATION_EXPORT jlong ComGoogleCommonIoByteStreams_copy__WithComGoogleCommonIoInputSupplier_withComGoogleCommonIoOutputSupplier_(id<ComGoogleCommonIoInputSupplier> from, id<ComGoogleCommonIoOutputSupplier> to);

FOUNDATION_EXPORT jlong ComGoogleCommonIoByteStreams_copy__WithComGoogleCommonIoInputSupplier_withJavaIoOutputStream_(id<ComGoogleCommonIoInputSupplier> from, JavaIoOutputStream *to);

FOUNDATION_EXPORT jlong ComGoogleCommonIoByteStreams_copy__WithJavaIoInputStream_withComGoogleCommonIoOutputSupplier_(JavaIoInputStream *from, id<ComGoogleCommonIoOutputSupplier> to);

FOUNDATION_EXPORT jlong ComGoogleCommonIoByteStreams_copy__WithJavaIoInputStream_withJavaIoOutputStream_(JavaIoInputStream *from, JavaIoOutputStream *to);

FOUNDATION_EXPORT IOSByteArray *ComGoogleCommonIoByteStreams_toByteArrayWithJavaIoInputStream_(JavaIoInputStream *inArg);

FOUNDATION_EXPORT IOSByteArray *ComGoogleCommonIoByteStreams_toByteArrayWithComGoogleCommonIoInputSupplier_(id<ComGoogleCommonIoInputSupplier> supplier);

FOUNDATION_EXPORT id<ComGoogleCommonIoByteArrayDataInput> ComGoogleCommonIoByteStreams_newDataInputWithByteArray_(IOSByteArray *bytes);

FOUNDATION_EXPORT id<ComGoogleCommonIoByteArrayDataInput> ComGoogleCommonIoByteStreams_newDataInputWithByteArray_withInt_(IOSByteArray *bytes, jint start);

FOUNDATION_EXPORT id<ComGoogleCommonIoByteArrayDataOutput> ComGoogleCommonIoByteStreams_newDataOutput();

FOUNDATION_EXPORT id<ComGoogleCommonIoByteArrayDataOutput> ComGoogleCommonIoByteStreams_newDataOutputWithInt_(jint size);

FOUNDATION_EXPORT JavaIoOutputStream *ComGoogleCommonIoByteStreams_nullOutputStream();

FOUNDATION_EXPORT JavaIoInputStream *ComGoogleCommonIoByteStreams_limitWithJavaIoInputStream_withLong_(JavaIoInputStream *inArg, jlong limit);

FOUNDATION_EXPORT jlong ComGoogleCommonIoByteStreams_lengthWithComGoogleCommonIoInputSupplier_(id<ComGoogleCommonIoInputSupplier> supplier);

FOUNDATION_EXPORT jboolean ComGoogleCommonIoByteStreams_equalWithComGoogleCommonIoInputSupplier_withComGoogleCommonIoInputSupplier_(id<ComGoogleCommonIoInputSupplier> supplier1, id<ComGoogleCommonIoInputSupplier> supplier2);

FOUNDATION_EXPORT void ComGoogleCommonIoByteStreams_readFullyWithJavaIoInputStream_withByteArray_(JavaIoInputStream *inArg, IOSByteArray *b);

FOUNDATION_EXPORT void ComGoogleCommonIoByteStreams_readFullyWithJavaIoInputStream_withByteArray_withInt_withInt_(JavaIoInputStream *inArg, IOSByteArray *b, jint off, jint len);

FOUNDATION_EXPORT void ComGoogleCommonIoByteStreams_skipFullyWithJavaIoInputStream_withLong_(JavaIoInputStream *inArg, jlong n);

FOUNDATION_EXPORT id ComGoogleCommonIoByteStreams_readBytesWithComGoogleCommonIoInputSupplier_withComGoogleCommonIoByteProcessor_(id<ComGoogleCommonIoInputSupplier> supplier, id<ComGoogleCommonIoByteProcessor> processor);

FOUNDATION_EXPORT id ComGoogleCommonIoByteStreams_readBytesWithJavaIoInputStream_withComGoogleCommonIoByteProcessor_(JavaIoInputStream *input, id<ComGoogleCommonIoByteProcessor> processor);

FOUNDATION_EXPORT jlong ComGoogleCommonIoByteStreams_getChecksumWithComGoogleCommonIoInputSupplier_withJavaUtilZipChecksum_(id<ComGoogleCommonIoInputSupplier> supplier, id<JavaUtilZipChecksum> checksum);

FOUNDATION_EXPORT ComGoogleCommonHashHashCode *ComGoogleCommonIoByteStreams_hash__WithComGoogleCommonIoInputSupplier_withComGoogleCommonHashHashFunction_(id<ComGoogleCommonIoInputSupplier> supplier, id<ComGoogleCommonHashHashFunction> hashFunction);

FOUNDATION_EXPORT jint ComGoogleCommonIoByteStreams_readWithJavaIoInputStream_withByteArray_withInt_withInt_(JavaIoInputStream *inArg, IOSByteArray *b, jint off, jint len);

FOUNDATION_EXPORT id<ComGoogleCommonIoInputSupplier> ComGoogleCommonIoByteStreams_sliceWithComGoogleCommonIoInputSupplier_withLong_withLong_(id<ComGoogleCommonIoInputSupplier> supplier, jlong offset, jlong length);

FOUNDATION_EXPORT id<ComGoogleCommonIoInputSupplier> ComGoogleCommonIoByteStreams_joinWithJavaLangIterable_(id<JavaLangIterable> suppliers);

FOUNDATION_EXPORT id<ComGoogleCommonIoInputSupplier> ComGoogleCommonIoByteStreams_joinWithComGoogleCommonIoInputSupplierArray_(IOSObjectArray *suppliers);

FOUNDATION_EXPORT id<ComGoogleCommonIoInputSupplier> ComGoogleCommonIoByteStreams_asInputSupplierWithComGoogleCommonIoByteSource_(ComGoogleCommonIoByteSource *source);

FOUNDATION_EXPORT id<ComGoogleCommonIoOutputSupplier> ComGoogleCommonIoByteStreams_asOutputSupplierWithComGoogleCommonIoByteSink_(ComGoogleCommonIoByteSink *sink);

FOUNDATION_EXPORT ComGoogleCommonIoByteSource *ComGoogleCommonIoByteStreams_asByteSourceWithComGoogleCommonIoInputSupplier_(id<ComGoogleCommonIoInputSupplier> supplier);

FOUNDATION_EXPORT ComGoogleCommonIoByteSink *ComGoogleCommonIoByteStreams_asByteSinkWithComGoogleCommonIoOutputSupplier_(id<ComGoogleCommonIoOutputSupplier> supplier);

J2OBJC_STATIC_FIELD_GETTER(ComGoogleCommonIoByteStreams, BUF_SIZE, jint)

FOUNDATION_EXPORT JavaIoOutputStream *ComGoogleCommonIoByteStreams_NULL_OUTPUT_STREAM_;
J2OBJC_STATIC_FIELD_GETTER(ComGoogleCommonIoByteStreams, NULL_OUTPUT_STREAM_, JavaIoOutputStream *)
CF_EXTERN_C_END
#endif

J2OBJC_TYPE_LITERAL_HEADER(ComGoogleCommonIoByteStreams)
#if !defined (_ComGoogleCommonIoByteStreams_ByteArrayByteSource_) && (ComGoogleCommonIoByteStreams_INCLUDE_ALL || ComGoogleCommonIoByteStreams_ByteArrayByteSource_INCLUDE)
#define _ComGoogleCommonIoByteStreams_ByteArrayByteSource_

@class ComGoogleCommonHashHashCode;
@class IOSByteArray;
@class JavaIoInputStream;
@class JavaIoOutputStream;
@protocol ComGoogleCommonHashHashFunction;

#define ComGoogleCommonIoByteSource_RESTRICT 1
#define ComGoogleCommonIoByteSource_INCLUDE 1
#include "com/google/common/io/ByteSource.h"


@interface ComGoogleCommonIoByteStreams_ByteArrayByteSource : ComGoogleCommonIoByteSource {
}

- (JavaIoInputStream *)openStream;

- (jlong)size;

- (IOSByteArray *)read;

- (jlong)copyToWithJavaIoOutputStream:(JavaIoOutputStream *)output OBJC_METHOD_FAMILY_NONE;

- (ComGoogleCommonHashHashCode *)hash__WithComGoogleCommonHashHashFunction:(id<ComGoogleCommonHashHashFunction>)hashFunction;

- (NSString *)description;

@end

J2OBJC_EMPTY_STATIC_INIT(ComGoogleCommonIoByteStreams_ByteArrayByteSource)

CF_EXTERN_C_BEGIN
CF_EXTERN_C_END
#endif

J2OBJC_TYPE_LITERAL_HEADER(ComGoogleCommonIoByteStreams_ByteArrayByteSource)
#if !defined (_ComGoogleCommonIoByteStreams_ByteArrayDataInputStream_) && (ComGoogleCommonIoByteStreams_INCLUDE_ALL || ComGoogleCommonIoByteStreams_ByteArrayDataInputStream_INCLUDE)
#define _ComGoogleCommonIoByteStreams_ByteArrayDataInputStream_

@class IOSByteArray;
@protocol JavaIoDataInput;

#define ComGoogleCommonIoByteArrayDataInput_RESTRICT 1
#define ComGoogleCommonIoByteArrayDataInput_INCLUDE 1
#include "com/google/common/io/ByteArrayDataInput.h"


@interface ComGoogleCommonIoByteStreams_ByteArrayDataInputStream : NSObject < ComGoogleCommonIoByteArrayDataInput > {
 @public
  id<JavaIoDataInput> input_;
}

- (instancetype)initWithByteArray:(IOSByteArray *)bytes;

- (instancetype)initWithByteArray:(IOSByteArray *)bytes
                          withInt:(jint)start;

- (void)readFullyWithByteArray:(IOSByteArray *)b;

- (void)readFullyWithByteArray:(IOSByteArray *)b
                       withInt:(jint)off
                       withInt:(jint)len;

- (jint)skipBytesWithInt:(jint)n;

- (jboolean)readBoolean;

- (jbyte)readByte;

- (jint)readUnsignedByte;

- (jshort)readShort;

- (jint)readUnsignedShort;

- (jchar)readChar;

- (jint)readInt;

- (jlong)readLong;

- (jfloat)readFloat;

- (jdouble)readDouble;

- (NSString *)readLine;

- (NSString *)readUTF;

@end

J2OBJC_EMPTY_STATIC_INIT(ComGoogleCommonIoByteStreams_ByteArrayDataInputStream)

J2OBJC_FIELD_SETTER(ComGoogleCommonIoByteStreams_ByteArrayDataInputStream, input_, id<JavaIoDataInput>)

CF_EXTERN_C_BEGIN
CF_EXTERN_C_END
#endif

J2OBJC_TYPE_LITERAL_HEADER(ComGoogleCommonIoByteStreams_ByteArrayDataInputStream)
#if !defined (_ComGoogleCommonIoByteStreams_ByteArrayDataOutputStream_) && (ComGoogleCommonIoByteStreams_INCLUDE_ALL || ComGoogleCommonIoByteStreams_ByteArrayDataOutputStream_INCLUDE)
#define _ComGoogleCommonIoByteStreams_ByteArrayDataOutputStream_

@class IOSByteArray;
@class JavaIoByteArrayOutputStream;
@protocol JavaIoDataOutput;

#define ComGoogleCommonIoByteArrayDataOutput_RESTRICT 1
#define ComGoogleCommonIoByteArrayDataOutput_INCLUDE 1
#include "com/google/common/io/ByteArrayDataOutput.h"


@interface ComGoogleCommonIoByteStreams_ByteArrayDataOutputStream : NSObject < ComGoogleCommonIoByteArrayDataOutput > {
 @public
  id<JavaIoDataOutput> output_;
  JavaIoByteArrayOutputStream *byteArrayOutputSteam_;
}

- (instancetype)init;

- (instancetype)initWithInt:(jint)size;

- (instancetype)initWithJavaIoByteArrayOutputStream:(JavaIoByteArrayOutputStream *)byteArrayOutputSteam;

- (void)writeWithInt:(jint)b;

- (void)writeWithByteArray:(IOSByteArray *)b;

- (void)writeWithByteArray:(IOSByteArray *)b
                   withInt:(jint)off
                   withInt:(jint)len;

- (void)writeBooleanWithBoolean:(jboolean)v;

- (void)writeByteWithInt:(jint)v;

- (void)writeBytesWithNSString:(NSString *)s;

- (void)writeCharWithInt:(jint)v;

- (void)writeCharsWithNSString:(NSString *)s;

- (void)writeDoubleWithDouble:(jdouble)v;

- (void)writeFloatWithFloat:(jfloat)v;

- (void)writeIntWithInt:(jint)v;

- (void)writeLongWithLong:(jlong)v;

- (void)writeShortWithInt:(jint)v;

- (void)writeUTFWithNSString:(NSString *)s;

- (IOSByteArray *)toByteArray;

@end

J2OBJC_EMPTY_STATIC_INIT(ComGoogleCommonIoByteStreams_ByteArrayDataOutputStream)

J2OBJC_FIELD_SETTER(ComGoogleCommonIoByteStreams_ByteArrayDataOutputStream, output_, id<JavaIoDataOutput>)
J2OBJC_FIELD_SETTER(ComGoogleCommonIoByteStreams_ByteArrayDataOutputStream, byteArrayOutputSteam_, JavaIoByteArrayOutputStream *)

CF_EXTERN_C_BEGIN
CF_EXTERN_C_END
#endif

J2OBJC_TYPE_LITERAL_HEADER(ComGoogleCommonIoByteStreams_ByteArrayDataOutputStream)
#if !defined (_ComGoogleCommonIoByteStreams_LimitedInputStream_) && (ComGoogleCommonIoByteStreams_INCLUDE_ALL || ComGoogleCommonIoByteStreams_LimitedInputStream_INCLUDE)
#define _ComGoogleCommonIoByteStreams_LimitedInputStream_

@class IOSByteArray;
@class JavaIoInputStream;

#define JavaIoFilterInputStream_RESTRICT 1
#define JavaIoFilterInputStream_INCLUDE 1
#include "java/io/FilterInputStream.h"


@interface ComGoogleCommonIoByteStreams_LimitedInputStream : JavaIoFilterInputStream {
}

- (instancetype)initWithJavaIoInputStream:(JavaIoInputStream *)inArg
                                 withLong:(jlong)limit;

- (jint)available;

- (void)markWithInt:(jint)readLimit;

- (jint)read;

- (jint)readWithByteArray:(IOSByteArray *)b
                  withInt:(jint)off
                  withInt:(jint)len;

- (void)reset;

- (jlong)skipWithLong:(jlong)n;

@end

J2OBJC_EMPTY_STATIC_INIT(ComGoogleCommonIoByteStreams_LimitedInputStream)

CF_EXTERN_C_BEGIN
CF_EXTERN_C_END
#endif

J2OBJC_TYPE_LITERAL_HEADER(ComGoogleCommonIoByteStreams_LimitedInputStream)
#if !defined (_ComGoogleCommonIoByteStreams_$1_) && (ComGoogleCommonIoByteStreams_INCLUDE_ALL || ComGoogleCommonIoByteStreams_$1_INCLUDE)
#define _ComGoogleCommonIoByteStreams_$1_

@class IOSByteArray;

#define JavaIoOutputStream_RESTRICT 1
#define JavaIoOutputStream_INCLUDE 1
#include "java/io/OutputStream.h"


@interface ComGoogleCommonIoByteStreams_$1 : JavaIoOutputStream {
}

- (void)writeWithInt:(jint)b;

- (void)writeWithByteArray:(IOSByteArray *)b;

- (void)writeWithByteArray:(IOSByteArray *)b
                   withInt:(jint)off
                   withInt:(jint)len;

- (NSString *)description;

- (instancetype)init;

@end

J2OBJC_EMPTY_STATIC_INIT(ComGoogleCommonIoByteStreams_$1)

CF_EXTERN_C_BEGIN
CF_EXTERN_C_END
#endif

J2OBJC_TYPE_LITERAL_HEADER(ComGoogleCommonIoByteStreams_$1)
#if !defined (_ComGoogleCommonIoByteStreams_$2_) && (ComGoogleCommonIoByteStreams_INCLUDE_ALL || ComGoogleCommonIoByteStreams_$2_INCLUDE)
#define _ComGoogleCommonIoByteStreams_$2_

@class IOSByteArray;
@class JavaLangLong;
@protocol JavaUtilZipChecksum;

#define ComGoogleCommonIoByteProcessor_RESTRICT 1
#define ComGoogleCommonIoByteProcessor_INCLUDE 1
#include "com/google/common/io/ByteProcessor.h"


@interface ComGoogleCommonIoByteStreams_$2 : NSObject < ComGoogleCommonIoByteProcessor > {
}

- (jboolean)processBytesWithByteArray:(IOSByteArray *)buf
                              withInt:(jint)off
                              withInt:(jint)len;

- (JavaLangLong *)getResult;

- (instancetype)initWithJavaUtilZipChecksum:(id<JavaUtilZipChecksum>)capture$0;

@end

J2OBJC_EMPTY_STATIC_INIT(ComGoogleCommonIoByteStreams_$2)

CF_EXTERN_C_BEGIN
CF_EXTERN_C_END
#endif

J2OBJC_TYPE_LITERAL_HEADER(ComGoogleCommonIoByteStreams_$2)
#if !defined (_ComGoogleCommonIoByteStreams_$3_) && (ComGoogleCommonIoByteStreams_INCLUDE_ALL || ComGoogleCommonIoByteStreams_$3_INCLUDE)
#define _ComGoogleCommonIoByteStreams_$3_

@class JavaIoInputStream;
@protocol JavaLangIterable;

#define ComGoogleCommonIoInputSupplier_RESTRICT 1
#define ComGoogleCommonIoInputSupplier_INCLUDE 1
#include "com/google/common/io/InputSupplier.h"


@interface ComGoogleCommonIoByteStreams_$3 : NSObject < ComGoogleCommonIoInputSupplier > {
}

- (JavaIoInputStream *)getInput;

- (instancetype)initWithJavaLangIterable:(id<JavaLangIterable>)capture$0;

@end

J2OBJC_EMPTY_STATIC_INIT(ComGoogleCommonIoByteStreams_$3)

CF_EXTERN_C_BEGIN
CF_EXTERN_C_END
#endif

J2OBJC_TYPE_LITERAL_HEADER(ComGoogleCommonIoByteStreams_$3)
#if !defined (_ComGoogleCommonIoByteStreams_$4_) && (ComGoogleCommonIoByteStreams_INCLUDE_ALL || ComGoogleCommonIoByteStreams_$4_INCLUDE)
#define _ComGoogleCommonIoByteStreams_$4_

@class ComGoogleCommonIoByteSource;
@class JavaIoInputStream;

#define ComGoogleCommonIoInputSupplier_RESTRICT 1
#define ComGoogleCommonIoInputSupplier_INCLUDE 1
#include "com/google/common/io/InputSupplier.h"


@interface ComGoogleCommonIoByteStreams_$4 : NSObject < ComGoogleCommonIoInputSupplier > {
}

- (id)getInput;

- (instancetype)initWithComGoogleCommonIoByteSource:(ComGoogleCommonIoByteSource *)capture$0;

@end

J2OBJC_EMPTY_STATIC_INIT(ComGoogleCommonIoByteStreams_$4)

CF_EXTERN_C_BEGIN
CF_EXTERN_C_END
#endif

J2OBJC_TYPE_LITERAL_HEADER(ComGoogleCommonIoByteStreams_$4)
#if !defined (_ComGoogleCommonIoByteStreams_$5_) && (ComGoogleCommonIoByteStreams_INCLUDE_ALL || ComGoogleCommonIoByteStreams_$5_INCLUDE)
#define _ComGoogleCommonIoByteStreams_$5_

@class ComGoogleCommonIoByteSink;
@class JavaIoOutputStream;

#define ComGoogleCommonIoOutputSupplier_RESTRICT 1
#define ComGoogleCommonIoOutputSupplier_INCLUDE 1
#include "com/google/common/io/OutputSupplier.h"


@interface ComGoogleCommonIoByteStreams_$5 : NSObject < ComGoogleCommonIoOutputSupplier > {
}

- (id)getOutput;

- (instancetype)initWithComGoogleCommonIoByteSink:(ComGoogleCommonIoByteSink *)capture$0;

@end

J2OBJC_EMPTY_STATIC_INIT(ComGoogleCommonIoByteStreams_$5)

CF_EXTERN_C_BEGIN
CF_EXTERN_C_END
#endif

J2OBJC_TYPE_LITERAL_HEADER(ComGoogleCommonIoByteStreams_$5)
#if !defined (_ComGoogleCommonIoByteStreams_$6_) && (ComGoogleCommonIoByteStreams_INCLUDE_ALL || ComGoogleCommonIoByteStreams_$6_INCLUDE)
#define _ComGoogleCommonIoByteStreams_$6_

@class JavaIoInputStream;
@protocol ComGoogleCommonIoInputSupplier;

#define ComGoogleCommonIoByteSource_RESTRICT 1
#define ComGoogleCommonIoByteSource_INCLUDE 1
#include "com/google/common/io/ByteSource.h"


@interface ComGoogleCommonIoByteStreams_$6 : ComGoogleCommonIoByteSource {
}

- (JavaIoInputStream *)openStream;

- (instancetype)initWithComGoogleCommonIoInputSupplier:(id<ComGoogleCommonIoInputSupplier>)capture$0;

@end

J2OBJC_EMPTY_STATIC_INIT(ComGoogleCommonIoByteStreams_$6)

CF_EXTERN_C_BEGIN
CF_EXTERN_C_END
#endif

J2OBJC_TYPE_LITERAL_HEADER(ComGoogleCommonIoByteStreams_$6)
#if !defined (_ComGoogleCommonIoByteStreams_$7_) && (ComGoogleCommonIoByteStreams_INCLUDE_ALL || ComGoogleCommonIoByteStreams_$7_INCLUDE)
#define _ComGoogleCommonIoByteStreams_$7_

@class JavaIoOutputStream;
@protocol ComGoogleCommonIoOutputSupplier;

#define ComGoogleCommonIoByteSink_RESTRICT 1
#define ComGoogleCommonIoByteSink_INCLUDE 1
#include "com/google/common/io/ByteSink.h"


@interface ComGoogleCommonIoByteStreams_$7 : ComGoogleCommonIoByteSink {
}

- (JavaIoOutputStream *)openStream;

- (instancetype)initWithComGoogleCommonIoOutputSupplier:(id<ComGoogleCommonIoOutputSupplier>)capture$0;

@end

J2OBJC_EMPTY_STATIC_INIT(ComGoogleCommonIoByteStreams_$7)

CF_EXTERN_C_BEGIN
CF_EXTERN_C_END
#endif

J2OBJC_TYPE_LITERAL_HEADER(ComGoogleCommonIoByteStreams_$7)
