//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: /Users/krasnocka/Downloads/j2objc-master/testing/mockito/build_result/java/org/mockito/invocation/MockHandler.java
//

#ifndef _OrgMockitoInvocationMockHandler_H_
#define _OrgMockitoInvocationMockHandler_H_

@protocol OrgMockitoInvocationInvocation;

#include "J2ObjC_header.h"
#include "java/io/Serializable.h"

@protocol OrgMockitoInvocationMockHandler < JavaIoSerializable, NSObject, JavaObject >
- (id)handleWithOrgMockitoInvocationInvocation:(id<OrgMockitoInvocationInvocation>)invocation;

@end

J2OBJC_EMPTY_STATIC_INIT(OrgMockitoInvocationMockHandler)

J2OBJC_TYPE_LITERAL_HEADER(OrgMockitoInvocationMockHandler)

#endif // _OrgMockitoInvocationMockHandler_H_
