//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: /Users/krasnocka/Downloads/j2objc-master/testing/mockito/build_result/java/org/mockito/internal/util/collections/ArrayUtils.java
//

#ifndef _OrgMockitoInternalUtilCollectionsArrayUtils_H_
#define _OrgMockitoInternalUtilCollectionsArrayUtils_H_

@class IOSObjectArray;

#include "J2ObjC_header.h"

@interface OrgMockitoInternalUtilCollectionsArrayUtils : NSObject {
}

- (jboolean)isEmptyWithNSObjectArray:(IOSObjectArray *)array;

- (instancetype)init;

@end

J2OBJC_EMPTY_STATIC_INIT(OrgMockitoInternalUtilCollectionsArrayUtils)

CF_EXTERN_C_BEGIN
CF_EXTERN_C_END

J2OBJC_TYPE_LITERAL_HEADER(OrgMockitoInternalUtilCollectionsArrayUtils)

#endif // _OrgMockitoInternalUtilCollectionsArrayUtils_H_
