//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: android/libcore/luni/src/main/java/org/apache/harmony/security/x501/DirectoryString.java
//

#ifndef _OrgApacheHarmonySecurityX501DirectoryString_H_
#define _OrgApacheHarmonySecurityX501DirectoryString_H_

@class IOSObjectArray;

#include "J2ObjC_header.h"
#include "org/apache/harmony/security/asn1/ASN1Choice.h"

@interface OrgApacheHarmonySecurityX501DirectoryString : NSObject {
}

- (instancetype)init;

@end

FOUNDATION_EXPORT BOOL OrgApacheHarmonySecurityX501DirectoryString_initialized;
J2OBJC_STATIC_INIT(OrgApacheHarmonySecurityX501DirectoryString)

CF_EXTERN_C_BEGIN

FOUNDATION_EXPORT OrgApacheHarmonySecurityAsn1ASN1Choice *OrgApacheHarmonySecurityX501DirectoryString_ASN1_;
J2OBJC_STATIC_FIELD_GETTER(OrgApacheHarmonySecurityX501DirectoryString, ASN1_, OrgApacheHarmonySecurityAsn1ASN1Choice *)
CF_EXTERN_C_END

J2OBJC_TYPE_LITERAL_HEADER(OrgApacheHarmonySecurityX501DirectoryString)

@interface OrgApacheHarmonySecurityX501DirectoryString_$1 : OrgApacheHarmonySecurityAsn1ASN1Choice {
}

- (jint)getIndexWithId:(id)object;

- (id)getObjectToEncodeWithId:(id)object;

- (instancetype)initWithOrgApacheHarmonySecurityAsn1ASN1TypeArray:(IOSObjectArray *)arg$0;

@end

J2OBJC_EMPTY_STATIC_INIT(OrgApacheHarmonySecurityX501DirectoryString_$1)

CF_EXTERN_C_BEGIN
CF_EXTERN_C_END

J2OBJC_TYPE_LITERAL_HEADER(OrgApacheHarmonySecurityX501DirectoryString_$1)

#endif // _OrgApacheHarmonySecurityX501DirectoryString_H_
