//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: android/libcore/luni/src/main/java/org/xml/sax/ContentHandler.java
//
//  Created by tball on 7/15/13.
//

#ifndef _OrgXmlSaxContentHandler_H_
#define _OrgXmlSaxContentHandler_H_

@class IOSCharArray;
@protocol OrgXmlSaxAttributes;
@protocol OrgXmlSaxLocator;

#import "JreEmulation.h"

@protocol OrgXmlSaxContentHandler < NSObject, JavaObject >
- (void)setDocumentLocatorWithOrgXmlSaxLocator:(id<OrgXmlSaxLocator>)locator;
- (void)startDocument;
- (void)endDocument;
- (void)startPrefixMappingWithNSString:(NSString *)prefix
                          withNSString:(NSString *)uri;
- (void)endPrefixMappingWithNSString:(NSString *)prefix;
- (void)startElementWithNSString:(NSString *)uri
                    withNSString:(NSString *)localName
                    withNSString:(NSString *)qName
         withOrgXmlSaxAttributes:(id<OrgXmlSaxAttributes>)atts;
- (void)endElementWithNSString:(NSString *)uri
                  withNSString:(NSString *)localName
                  withNSString:(NSString *)qName;
- (void)charactersWithCharArray:(IOSCharArray *)ch
                        withInt:(int)start
                        withInt:(int)length;
- (void)ignorableWhitespaceWithCharArray:(IOSCharArray *)ch
                                 withInt:(int)start
                                 withInt:(int)length;
- (void)processingInstructionWithNSString:(NSString *)target
                             withNSString:(NSString *)data;
- (void)skippedEntityWithNSString:(NSString *)name;
@end

#endif // _OrgXmlSaxContentHandler_H_
