//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: /Users/krasnocka/Downloads/j2objc-master/guava/sources/com/google/common/reflect/AbstractInvocationHandler.java
//

#include "J2ObjC_header.h"

#if !ComGoogleCommonReflectAbstractInvocationHandler_RESTRICT
#define ComGoogleCommonReflectAbstractInvocationHandler_INCLUDE_ALL 1
#endif
#undef ComGoogleCommonReflectAbstractInvocationHandler_RESTRICT
#if !defined (_ComGoogleCommonReflectAbstractInvocationHandler_) && (ComGoogleCommonReflectAbstractInvocationHandler_INCLUDE_ALL || ComGoogleCommonReflectAbstractInvocationHandler_INCLUDE)
#define _ComGoogleCommonReflectAbstractInvocationHandler_

@class IOSObjectArray;
@class JavaLangReflectMethod;

#define JavaLangReflectInvocationHandler_RESTRICT 1
#define JavaLangReflectInvocationHandler_INCLUDE 1
#include "java/lang/reflect/InvocationHandler.h"


@interface ComGoogleCommonReflectAbstractInvocationHandler : NSObject < JavaLangReflectInvocationHandler > {
}

- (id)invokeWithId:(id)proxy
withJavaLangReflectMethod:(JavaLangReflectMethod *)method
 withNSObjectArray:(IOSObjectArray *)args;

- (id)handleInvocationWithId:(id)proxy
   withJavaLangReflectMethod:(JavaLangReflectMethod *)method
           withNSObjectArray:(IOSObjectArray *)args;

- (jboolean)isEqual:(id)obj;

- (NSUInteger)hash;

- (NSString *)description;

- (instancetype)init;

@end

FOUNDATION_EXPORT BOOL ComGoogleCommonReflectAbstractInvocationHandler_initialized;
J2OBJC_STATIC_INIT(ComGoogleCommonReflectAbstractInvocationHandler)

CF_EXTERN_C_BEGIN

FOUNDATION_EXPORT IOSObjectArray *ComGoogleCommonReflectAbstractInvocationHandler_NO_ARGS_;
J2OBJC_STATIC_FIELD_GETTER(ComGoogleCommonReflectAbstractInvocationHandler, NO_ARGS_, IOSObjectArray *)
CF_EXTERN_C_END
#endif

J2OBJC_TYPE_LITERAL_HEADER(ComGoogleCommonReflectAbstractInvocationHandler)
