//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: /Users/krasnocka/Downloads/j2objc-master/guava/sources/com/google/common/reflect/TypeToken.java
//

#include "J2ObjC_header.h"

#if !ComGoogleCommonReflectTypeToken_RESTRICT
#define ComGoogleCommonReflectTypeToken_INCLUDE_ALL 1
#endif
#undef ComGoogleCommonReflectTypeToken_RESTRICT
#if ComGoogleCommonReflectTypeToken_TypeCollector_$3_INCLUDE
#define ComGoogleCommonReflectTypeToken_TypeCollector_ForwardingTypeCollector_INCLUDE 1
#endif
#if ComGoogleCommonReflectTypeToken_TypeCollector_ForwardingTypeCollector_INCLUDE
#define ComGoogleCommonReflectTypeToken_TypeCollector_INCLUDE 1
#endif
#if ComGoogleCommonReflectTypeToken_TypeCollector_$2_INCLUDE
#define ComGoogleCommonReflectTypeToken_TypeCollector_INCLUDE 1
#endif
#if ComGoogleCommonReflectTypeToken_TypeCollector_$1_INCLUDE
#define ComGoogleCommonReflectTypeToken_TypeCollector_INCLUDE 1
#endif
#if ComGoogleCommonReflectTypeToken_SimpleTypeToken_INCLUDE
#define ComGoogleCommonReflectTypeToken_INCLUDE 1
#endif
#if ComGoogleCommonReflectTypeToken_TypeFilterEnum_$2_INCLUDE
#define ComGoogleCommonReflectTypeToken_TypeFilterEnum_INCLUDE 1
#endif
#if ComGoogleCommonReflectTypeToken_TypeFilterEnum_$1_INCLUDE
#define ComGoogleCommonReflectTypeToken_TypeFilterEnum_INCLUDE 1
#endif
#if ComGoogleCommonReflectTypeToken_ClassSet_INCLUDE
#define ComGoogleCommonReflectTypeToken_TypeSet_INCLUDE 1
#endif
#if ComGoogleCommonReflectTypeToken_InterfaceSet_INCLUDE
#define ComGoogleCommonReflectTypeToken_TypeSet_INCLUDE 1
#endif
#if !defined (_ComGoogleCommonReflectTypeToken_TypeSet_) && (ComGoogleCommonReflectTypeToken_INCLUDE_ALL || ComGoogleCommonReflectTypeToken_TypeSet_INCLUDE)
#define _ComGoogleCommonReflectTypeToken_TypeSet_

@class ComGoogleCommonCollectImmutableSet;
@class ComGoogleCommonReflectTypeToken;
@protocol JavaUtilSet;

#define ComGoogleCommonCollectForwardingSet_RESTRICT 1
#define ComGoogleCommonCollectForwardingSet_INCLUDE 1
#include "com/google/common/collect/ForwardingSet.h"

#define JavaIoSerializable_RESTRICT 1
#define JavaIoSerializable_INCLUDE 1
#include "java/io/Serializable.h"


#define ComGoogleCommonReflectTypeToken_TypeSet_serialVersionUID 0LL

@interface ComGoogleCommonReflectTypeToken_TypeSet : ComGoogleCommonCollectForwardingSet < JavaIoSerializable > {
}

- (instancetype)initWithComGoogleCommonReflectTypeToken:(ComGoogleCommonReflectTypeToken *)outer$;

- (ComGoogleCommonReflectTypeToken_TypeSet *)interfaces;

- (ComGoogleCommonReflectTypeToken_TypeSet *)classes;

- (id<JavaUtilSet>)delegate;

- (id<JavaUtilSet>)rawTypes;


@end

J2OBJC_EMPTY_STATIC_INIT(ComGoogleCommonReflectTypeToken_TypeSet)

CF_EXTERN_C_BEGIN

J2OBJC_STATIC_FIELD_GETTER(ComGoogleCommonReflectTypeToken_TypeSet, serialVersionUID, jlong)
CF_EXTERN_C_END
#endif

J2OBJC_TYPE_LITERAL_HEADER(ComGoogleCommonReflectTypeToken_TypeSet)
#if !defined (_ComGoogleCommonReflectTypeToken_InterfaceSet_) && (ComGoogleCommonReflectTypeToken_INCLUDE_ALL || ComGoogleCommonReflectTypeToken_InterfaceSet_INCLUDE)
#define _ComGoogleCommonReflectTypeToken_InterfaceSet_

@class ComGoogleCommonCollectImmutableSet;
@class ComGoogleCommonReflectTypeToken;
@protocol JavaUtilSet;


#define ComGoogleCommonReflectTypeToken_InterfaceSet_serialVersionUID 0LL

@interface ComGoogleCommonReflectTypeToken_InterfaceSet : ComGoogleCommonReflectTypeToken_TypeSet {
}

- (instancetype)initWithComGoogleCommonReflectTypeToken:(ComGoogleCommonReflectTypeToken *)outer$
            withComGoogleCommonReflectTypeToken_TypeSet:(ComGoogleCommonReflectTypeToken_TypeSet *)allTypes;

- (id<JavaUtilSet>)delegate;

- (ComGoogleCommonReflectTypeToken_TypeSet *)interfaces;

- (id<JavaUtilSet>)rawTypes;

- (ComGoogleCommonReflectTypeToken_TypeSet *)classes;


@end

J2OBJC_EMPTY_STATIC_INIT(ComGoogleCommonReflectTypeToken_InterfaceSet)

CF_EXTERN_C_BEGIN

J2OBJC_STATIC_FIELD_GETTER(ComGoogleCommonReflectTypeToken_InterfaceSet, serialVersionUID, jlong)
CF_EXTERN_C_END
#endif

J2OBJC_TYPE_LITERAL_HEADER(ComGoogleCommonReflectTypeToken_InterfaceSet)
#if !defined (_ComGoogleCommonReflectTypeToken_InterfaceSet_$1_) && (ComGoogleCommonReflectTypeToken_INCLUDE_ALL || ComGoogleCommonReflectTypeToken_InterfaceSet_$1_INCLUDE)
#define _ComGoogleCommonReflectTypeToken_InterfaceSet_$1_

@class IOSClass;

#define ComGoogleCommonBasePredicate_RESTRICT 1
#define ComGoogleCommonBasePredicate_INCLUDE 1
#include "com/google/common/base/Predicate.h"


@interface ComGoogleCommonReflectTypeToken_InterfaceSet_$1 : NSObject < ComGoogleCommonBasePredicate > {
}

- (jboolean)applyWithId:(IOSClass *)type;

- (instancetype)init;

@end

J2OBJC_EMPTY_STATIC_INIT(ComGoogleCommonReflectTypeToken_InterfaceSet_$1)

CF_EXTERN_C_BEGIN
CF_EXTERN_C_END
#endif

J2OBJC_TYPE_LITERAL_HEADER(ComGoogleCommonReflectTypeToken_InterfaceSet_$1)
#if !defined (_ComGoogleCommonReflectTypeToken_ClassSet_) && (ComGoogleCommonReflectTypeToken_INCLUDE_ALL || ComGoogleCommonReflectTypeToken_ClassSet_INCLUDE)
#define _ComGoogleCommonReflectTypeToken_ClassSet_

@class ComGoogleCommonCollectImmutableSet;
@class ComGoogleCommonReflectTypeToken;
@protocol JavaUtilSet;


#define ComGoogleCommonReflectTypeToken_ClassSet_serialVersionUID 0LL

@interface ComGoogleCommonReflectTypeToken_ClassSet : ComGoogleCommonReflectTypeToken_TypeSet {
}

- (id<JavaUtilSet>)delegate;

- (ComGoogleCommonReflectTypeToken_TypeSet *)classes;

- (id<JavaUtilSet>)rawTypes;

- (ComGoogleCommonReflectTypeToken_TypeSet *)interfaces;

- (instancetype)initWithComGoogleCommonReflectTypeToken:(ComGoogleCommonReflectTypeToken *)outer$;


@end

J2OBJC_EMPTY_STATIC_INIT(ComGoogleCommonReflectTypeToken_ClassSet)

CF_EXTERN_C_BEGIN

J2OBJC_STATIC_FIELD_GETTER(ComGoogleCommonReflectTypeToken_ClassSet, serialVersionUID, jlong)
CF_EXTERN_C_END
#endif

J2OBJC_TYPE_LITERAL_HEADER(ComGoogleCommonReflectTypeToken_ClassSet)
#if !defined (_ComGoogleCommonReflectTypeToken_TypeFilterEnum_) && (ComGoogleCommonReflectTypeToken_INCLUDE_ALL || ComGoogleCommonReflectTypeToken_TypeFilterEnum_INCLUDE)
#define _ComGoogleCommonReflectTypeToken_TypeFilterEnum_

#define JavaLangEnum_RESTRICT 1
#define JavaLangEnum_INCLUDE 1
#include "java/lang/Enum.h"

#define ComGoogleCommonBasePredicate_RESTRICT 1
#define ComGoogleCommonBasePredicate_INCLUDE 1
#include "com/google/common/base/Predicate.h"


typedef NS_ENUM(NSUInteger, ComGoogleCommonReflectTypeToken_TypeFilter) {
  ComGoogleCommonReflectTypeToken_TypeFilter_IGNORE_TYPE_VARIABLE_OR_WILDCARD = 0,
  ComGoogleCommonReflectTypeToken_TypeFilter_INTERFACE_ONLY = 1,
};

@interface ComGoogleCommonReflectTypeToken_TypeFilterEnum : JavaLangEnum < NSCopying, ComGoogleCommonBasePredicate > {
}

+ (IOSObjectArray *)values;
FOUNDATION_EXPORT IOSObjectArray *ComGoogleCommonReflectTypeToken_TypeFilterEnum_values();

+ (ComGoogleCommonReflectTypeToken_TypeFilterEnum *)valueOfWithNSString:(NSString *)name;

FOUNDATION_EXPORT ComGoogleCommonReflectTypeToken_TypeFilterEnum *ComGoogleCommonReflectTypeToken_TypeFilterEnum_valueOfWithNSString_(NSString *name);
- (id)copyWithZone:(NSZone *)zone;

@end

FOUNDATION_EXPORT BOOL ComGoogleCommonReflectTypeToken_TypeFilterEnum_initialized;
J2OBJC_STATIC_INIT(ComGoogleCommonReflectTypeToken_TypeFilterEnum)

FOUNDATION_EXPORT ComGoogleCommonReflectTypeToken_TypeFilterEnum *ComGoogleCommonReflectTypeToken_TypeFilterEnum_values_[];

#define ComGoogleCommonReflectTypeToken_TypeFilterEnum_IGNORE_TYPE_VARIABLE_OR_WILDCARD ComGoogleCommonReflectTypeToken_TypeFilterEnum_values_[ComGoogleCommonReflectTypeToken_TypeFilter_IGNORE_TYPE_VARIABLE_OR_WILDCARD]
J2OBJC_ENUM_CONSTANT_GETTER(ComGoogleCommonReflectTypeToken_TypeFilterEnum, IGNORE_TYPE_VARIABLE_OR_WILDCARD)

#define ComGoogleCommonReflectTypeToken_TypeFilterEnum_INTERFACE_ONLY ComGoogleCommonReflectTypeToken_TypeFilterEnum_values_[ComGoogleCommonReflectTypeToken_TypeFilter_INTERFACE_ONLY]
J2OBJC_ENUM_CONSTANT_GETTER(ComGoogleCommonReflectTypeToken_TypeFilterEnum, INTERFACE_ONLY)
#endif

J2OBJC_TYPE_LITERAL_HEADER(ComGoogleCommonReflectTypeToken_TypeFilterEnum)
#if !defined (_ComGoogleCommonReflectTypeToken_TypeFilterEnum_$1_) && (ComGoogleCommonReflectTypeToken_INCLUDE_ALL || ComGoogleCommonReflectTypeToken_TypeFilterEnum_$1_INCLUDE)
#define _ComGoogleCommonReflectTypeToken_TypeFilterEnum_$1_

@class ComGoogleCommonReflectTypeToken;


@interface ComGoogleCommonReflectTypeToken_TypeFilterEnum_$1 : ComGoogleCommonReflectTypeToken_TypeFilterEnum {
}

- (jboolean)applyWithId:(ComGoogleCommonReflectTypeToken *)type;

- (instancetype)initWithNSString:(NSString *)__name
                         withInt:(jint)__ordinal;

@end

J2OBJC_EMPTY_STATIC_INIT(ComGoogleCommonReflectTypeToken_TypeFilterEnum_$1)

CF_EXTERN_C_BEGIN
CF_EXTERN_C_END
#endif

J2OBJC_TYPE_LITERAL_HEADER(ComGoogleCommonReflectTypeToken_TypeFilterEnum_$1)
#if !defined (_ComGoogleCommonReflectTypeToken_TypeFilterEnum_$2_) && (ComGoogleCommonReflectTypeToken_INCLUDE_ALL || ComGoogleCommonReflectTypeToken_TypeFilterEnum_$2_INCLUDE)
#define _ComGoogleCommonReflectTypeToken_TypeFilterEnum_$2_

@class ComGoogleCommonReflectTypeToken;


@interface ComGoogleCommonReflectTypeToken_TypeFilterEnum_$2 : ComGoogleCommonReflectTypeToken_TypeFilterEnum {
}

- (jboolean)applyWithId:(ComGoogleCommonReflectTypeToken *)type;

- (instancetype)initWithNSString:(NSString *)__name
                         withInt:(jint)__ordinal;

@end

J2OBJC_EMPTY_STATIC_INIT(ComGoogleCommonReflectTypeToken_TypeFilterEnum_$2)

CF_EXTERN_C_BEGIN
CF_EXTERN_C_END
#endif

J2OBJC_TYPE_LITERAL_HEADER(ComGoogleCommonReflectTypeToken_TypeFilterEnum_$2)
#if !defined (_ComGoogleCommonReflectTypeToken_) && (ComGoogleCommonReflectTypeToken_INCLUDE_ALL || ComGoogleCommonReflectTypeToken_INCLUDE)
#define _ComGoogleCommonReflectTypeToken_

@class ComGoogleCommonCollectImmutableList;
@class ComGoogleCommonCollectImmutableSet;
@class ComGoogleCommonReflectInvokable;
@class ComGoogleCommonReflectTypeParameter;
@class ComGoogleCommonReflectTypeResolver;
@class ComGoogleCommonReflectTypeToken_TypeSet;
@class IOSClass;
@class IOSObjectArray;
@class JavaLangReflectConstructor;
@class JavaLangReflectMethod;
@protocol JavaLangReflectGenericArrayType;
@protocol JavaLangReflectParameterizedType;
@protocol JavaLangReflectType;
@protocol JavaLangReflectWildcardType;

#define ComGoogleCommonReflectTypeCapture_RESTRICT 1
#define ComGoogleCommonReflectTypeCapture_INCLUDE 1
#include "com/google/common/reflect/TypeCapture.h"

#define JavaIoSerializable_RESTRICT 1
#define JavaIoSerializable_INCLUDE 1
#include "java/io/Serializable.h"


@interface ComGoogleCommonReflectTypeToken : ComGoogleCommonReflectTypeCapture < JavaIoSerializable > {
}

- (instancetype)init;

- (instancetype)initWithIOSClass:(IOSClass *)declaringClass;

+ (ComGoogleCommonReflectTypeToken *)ofWithIOSClass:(IOSClass *)type;

+ (ComGoogleCommonReflectTypeToken *)ofWithJavaLangReflectType:(id<JavaLangReflectType>)type;

- (IOSClass *)getRawType;

- (id<JavaLangReflectType>)getType;

- (ComGoogleCommonReflectTypeToken *)whereWithComGoogleCommonReflectTypeParameter:(ComGoogleCommonReflectTypeParameter *)typeParam
                                              withComGoogleCommonReflectTypeToken:(ComGoogleCommonReflectTypeToken *)typeArg;

- (ComGoogleCommonReflectTypeToken *)whereWithComGoogleCommonReflectTypeParameter:(ComGoogleCommonReflectTypeParameter *)typeParam
                                                                     withIOSClass:(IOSClass *)typeArg;

- (ComGoogleCommonReflectTypeToken *)resolveTypeWithJavaLangReflectType:(id<JavaLangReflectType>)type;

- (ComGoogleCommonReflectTypeToken *)getGenericSuperclass;

- (ComGoogleCommonCollectImmutableList *)getGenericInterfaces;

- (ComGoogleCommonReflectTypeToken_TypeSet *)getTypes;

- (ComGoogleCommonReflectTypeToken *)getSupertypeWithIOSClass:(IOSClass *)superclass_;

- (ComGoogleCommonReflectTypeToken *)getSubtypeWithIOSClass:(IOSClass *)subclass;

- (jboolean)isAssignableFromWithComGoogleCommonReflectTypeToken:(ComGoogleCommonReflectTypeToken *)type;

- (jboolean)isAssignableFromWithJavaLangReflectType:(id<JavaLangReflectType>)type;

- (jboolean)isArray;

- (ComGoogleCommonReflectTypeToken *)getComponentType;

- (ComGoogleCommonReflectInvokable *)methodWithJavaLangReflectMethod:(JavaLangReflectMethod *)method;

- (ComGoogleCommonReflectInvokable *)constructorWithJavaLangReflectConstructor:(JavaLangReflectConstructor *)constructor;

- (jboolean)isEqual:(id)o;

- (NSUInteger)hash;

- (NSString *)description;

- (id)writeReplace;

- (ComGoogleCommonReflectTypeToken *)rejectTypeVariables;

+ (IOSClass *)getRawTypeWithJavaLangReflectType:(id<JavaLangReflectType>)type;

+ (ComGoogleCommonCollectImmutableSet *)getRawTypesWithJavaLangReflectType:(id<JavaLangReflectType>)type;

+ (ComGoogleCommonReflectTypeToken *)toGenericTypeWithIOSClass:(IOSClass *)cls;

@end

J2OBJC_EMPTY_STATIC_INIT(ComGoogleCommonReflectTypeToken)

CF_EXTERN_C_BEGIN

FOUNDATION_EXPORT ComGoogleCommonReflectTypeToken *ComGoogleCommonReflectTypeToken_ofWithIOSClass_(IOSClass *type);

FOUNDATION_EXPORT ComGoogleCommonReflectTypeToken *ComGoogleCommonReflectTypeToken_ofWithJavaLangReflectType_(id<JavaLangReflectType> type);

FOUNDATION_EXPORT IOSClass *ComGoogleCommonReflectTypeToken_getRawTypeWithJavaLangReflectType_(id<JavaLangReflectType> type);

FOUNDATION_EXPORT ComGoogleCommonCollectImmutableSet *ComGoogleCommonReflectTypeToken_getRawTypesWithJavaLangReflectType_(id<JavaLangReflectType> type);

FOUNDATION_EXPORT ComGoogleCommonReflectTypeToken *ComGoogleCommonReflectTypeToken_toGenericTypeWithIOSClass_(IOSClass *cls);
CF_EXTERN_C_END
#endif

J2OBJC_TYPE_LITERAL_HEADER(ComGoogleCommonReflectTypeToken)
#if !defined (_ComGoogleCommonReflectTypeToken_SimpleTypeToken_) && (ComGoogleCommonReflectTypeToken_INCLUDE_ALL || ComGoogleCommonReflectTypeToken_SimpleTypeToken_INCLUDE)
#define _ComGoogleCommonReflectTypeToken_SimpleTypeToken_

@protocol JavaLangReflectType;


#define ComGoogleCommonReflectTypeToken_SimpleTypeToken_serialVersionUID 0LL

@interface ComGoogleCommonReflectTypeToken_SimpleTypeToken : ComGoogleCommonReflectTypeToken {
}

- (instancetype)initWithJavaLangReflectType:(id<JavaLangReflectType>)type;

@end

J2OBJC_EMPTY_STATIC_INIT(ComGoogleCommonReflectTypeToken_SimpleTypeToken)

CF_EXTERN_C_BEGIN

J2OBJC_STATIC_FIELD_GETTER(ComGoogleCommonReflectTypeToken_SimpleTypeToken, serialVersionUID, jlong)
CF_EXTERN_C_END
#endif

J2OBJC_TYPE_LITERAL_HEADER(ComGoogleCommonReflectTypeToken_SimpleTypeToken)
#if !defined (_ComGoogleCommonReflectTypeToken_TypeCollector_) && (ComGoogleCommonReflectTypeToken_INCLUDE_ALL || ComGoogleCommonReflectTypeToken_TypeCollector_INCLUDE)
#define _ComGoogleCommonReflectTypeToken_TypeCollector_

@class ComGoogleCommonCollectImmutableList;
@class IOSClass;
@protocol JavaLangIterable;
@protocol JavaUtilComparator;
@protocol JavaUtilMap;


@interface ComGoogleCommonReflectTypeToken_TypeCollector : NSObject {
}

- (ComGoogleCommonReflectTypeToken_TypeCollector *)classesOnly;

- (ComGoogleCommonCollectImmutableList *)collectTypesWithId:(id)type;

- (ComGoogleCommonCollectImmutableList *)collectTypesWithJavaLangIterable:(id<JavaLangIterable>)types;

- (IOSClass *)getRawTypeWithId:(id)type;

- (id<JavaLangIterable>)getInterfacesWithId:(id)type;

- (id)getSuperclassWithId:(id)type;

@end

FOUNDATION_EXPORT BOOL ComGoogleCommonReflectTypeToken_TypeCollector_initialized;
J2OBJC_STATIC_INIT(ComGoogleCommonReflectTypeToken_TypeCollector)

CF_EXTERN_C_BEGIN

FOUNDATION_EXPORT ComGoogleCommonReflectTypeToken_TypeCollector *ComGoogleCommonReflectTypeToken_TypeCollector_FOR_GENERIC_TYPE_;
J2OBJC_STATIC_FIELD_GETTER(ComGoogleCommonReflectTypeToken_TypeCollector, FOR_GENERIC_TYPE_, ComGoogleCommonReflectTypeToken_TypeCollector *)

FOUNDATION_EXPORT ComGoogleCommonReflectTypeToken_TypeCollector *ComGoogleCommonReflectTypeToken_TypeCollector_FOR_RAW_TYPE_;
J2OBJC_STATIC_FIELD_GETTER(ComGoogleCommonReflectTypeToken_TypeCollector, FOR_RAW_TYPE_, ComGoogleCommonReflectTypeToken_TypeCollector *)
CF_EXTERN_C_END
#endif

J2OBJC_TYPE_LITERAL_HEADER(ComGoogleCommonReflectTypeToken_TypeCollector)
#if !defined (_ComGoogleCommonReflectTypeToken_TypeCollector_$1_) && (ComGoogleCommonReflectTypeToken_INCLUDE_ALL || ComGoogleCommonReflectTypeToken_TypeCollector_$1_INCLUDE)
#define _ComGoogleCommonReflectTypeToken_TypeCollector_$1_

@class ComGoogleCommonReflectTypeToken;
@class IOSClass;
@protocol JavaLangIterable;


@interface ComGoogleCommonReflectTypeToken_TypeCollector_$1 : ComGoogleCommonReflectTypeToken_TypeCollector {
}

- (IOSClass *)getRawTypeWithId:(ComGoogleCommonReflectTypeToken *)type;

- (id<JavaLangIterable>)getInterfacesWithId:(ComGoogleCommonReflectTypeToken *)type;

- (ComGoogleCommonReflectTypeToken *)getSuperclassWithId:(ComGoogleCommonReflectTypeToken *)type;

- (instancetype)init;

@end

J2OBJC_EMPTY_STATIC_INIT(ComGoogleCommonReflectTypeToken_TypeCollector_$1)

CF_EXTERN_C_BEGIN
CF_EXTERN_C_END
#endif

J2OBJC_TYPE_LITERAL_HEADER(ComGoogleCommonReflectTypeToken_TypeCollector_$1)
#if !defined (_ComGoogleCommonReflectTypeToken_TypeCollector_$2_) && (ComGoogleCommonReflectTypeToken_INCLUDE_ALL || ComGoogleCommonReflectTypeToken_TypeCollector_$2_INCLUDE)
#define _ComGoogleCommonReflectTypeToken_TypeCollector_$2_

@class IOSClass;
@protocol JavaLangIterable;


@interface ComGoogleCommonReflectTypeToken_TypeCollector_$2 : ComGoogleCommonReflectTypeToken_TypeCollector {
}

- (IOSClass *)getRawTypeWithId:(IOSClass *)type;

- (id<JavaLangIterable>)getInterfacesWithId:(IOSClass *)type;

- (IOSClass *)getSuperclassWithId:(IOSClass *)type;

- (instancetype)init;

@end

J2OBJC_EMPTY_STATIC_INIT(ComGoogleCommonReflectTypeToken_TypeCollector_$2)

CF_EXTERN_C_BEGIN
CF_EXTERN_C_END
#endif

J2OBJC_TYPE_LITERAL_HEADER(ComGoogleCommonReflectTypeToken_TypeCollector_$2)
#if !defined (_ComGoogleCommonReflectTypeToken_TypeCollector_ForwardingTypeCollector_) && (ComGoogleCommonReflectTypeToken_INCLUDE_ALL || ComGoogleCommonReflectTypeToken_TypeCollector_ForwardingTypeCollector_INCLUDE)
#define _ComGoogleCommonReflectTypeToken_TypeCollector_ForwardingTypeCollector_

@class IOSClass;
@protocol JavaLangIterable;


@interface ComGoogleCommonReflectTypeToken_TypeCollector_ForwardingTypeCollector : ComGoogleCommonReflectTypeToken_TypeCollector {
}

- (instancetype)initWithComGoogleCommonReflectTypeToken_TypeCollector:(ComGoogleCommonReflectTypeToken_TypeCollector *)delegate;

- (IOSClass *)getRawTypeWithId:(id)type;

- (id<JavaLangIterable>)getInterfacesWithId:(id)type;

- (id)getSuperclassWithId:(id)type;

@end

J2OBJC_EMPTY_STATIC_INIT(ComGoogleCommonReflectTypeToken_TypeCollector_ForwardingTypeCollector)

CF_EXTERN_C_BEGIN
CF_EXTERN_C_END
#endif

J2OBJC_TYPE_LITERAL_HEADER(ComGoogleCommonReflectTypeToken_TypeCollector_ForwardingTypeCollector)
#if !defined (_ComGoogleCommonReflectTypeToken_TypeCollector_$3_) && (ComGoogleCommonReflectTypeToken_INCLUDE_ALL || ComGoogleCommonReflectTypeToken_TypeCollector_$3_INCLUDE)
#define _ComGoogleCommonReflectTypeToken_TypeCollector_$3_

@class ComGoogleCommonCollectImmutableList;
@class ComGoogleCommonReflectTypeToken_TypeCollector;
@protocol JavaLangIterable;


@interface ComGoogleCommonReflectTypeToken_TypeCollector_$3 : ComGoogleCommonReflectTypeToken_TypeCollector_ForwardingTypeCollector {
}

- (id<JavaLangIterable>)getInterfacesWithId:(id)type;

- (ComGoogleCommonCollectImmutableList *)collectTypesWithJavaLangIterable:(id<JavaLangIterable>)types;

- (instancetype)initWithComGoogleCommonReflectTypeToken_TypeCollector:(ComGoogleCommonReflectTypeToken_TypeCollector *)arg$0;

@end

J2OBJC_EMPTY_STATIC_INIT(ComGoogleCommonReflectTypeToken_TypeCollector_$3)

CF_EXTERN_C_BEGIN
CF_EXTERN_C_END
#endif

J2OBJC_TYPE_LITERAL_HEADER(ComGoogleCommonReflectTypeToken_TypeCollector_$3)
#if !defined (_ComGoogleCommonReflectTypeToken_TypeCollector_$4_) && (ComGoogleCommonReflectTypeToken_INCLUDE_ALL || ComGoogleCommonReflectTypeToken_TypeCollector_$4_INCLUDE)
#define _ComGoogleCommonReflectTypeToken_TypeCollector_$4_

@protocol JavaUtilComparator;
@protocol JavaUtilMap;

#define ComGoogleCommonCollectOrdering_RESTRICT 1
#define ComGoogleCommonCollectOrdering_INCLUDE 1
#include "com/google/common/collect/Ordering.h"


@interface ComGoogleCommonReflectTypeToken_TypeCollector_$4 : ComGoogleCommonCollectOrdering {
}

- (jint)compareWithId:(id)left
               withId:(id)right;

- (instancetype)initWithJavaUtilComparator:(id<JavaUtilComparator>)capture$0
                           withJavaUtilMap:(id<JavaUtilMap>)capture$1;

@end

J2OBJC_EMPTY_STATIC_INIT(ComGoogleCommonReflectTypeToken_TypeCollector_$4)

CF_EXTERN_C_BEGIN
CF_EXTERN_C_END
#endif

J2OBJC_TYPE_LITERAL_HEADER(ComGoogleCommonReflectTypeToken_TypeCollector_$4)
#if !defined (_ComGoogleCommonReflectTypeToken_$1_) && (ComGoogleCommonReflectTypeToken_INCLUDE_ALL || ComGoogleCommonReflectTypeToken_$1_INCLUDE)
#define _ComGoogleCommonReflectTypeToken_$1_

@class ComGoogleCommonReflectTypeToken;
@class IOSObjectArray;
@class JavaLangReflectMethod;
@protocol JavaLangReflectType;

#define ComGoogleCommonReflectInvokable_RESTRICT 1
#define ComGoogleCommonReflectInvokable_MethodInvokable_INCLUDE 1
#include "com/google/common/reflect/Invokable.h"


@interface ComGoogleCommonReflectTypeToken_$1 : ComGoogleCommonReflectInvokable_MethodInvokable {
}

- (id<JavaLangReflectType>)getGenericReturnType;

- (IOSObjectArray *)getGenericParameterTypes;

- (IOSObjectArray *)getGenericExceptionTypes;

- (ComGoogleCommonReflectTypeToken *)getOwnerType;

- (instancetype)initWithComGoogleCommonReflectTypeToken:(ComGoogleCommonReflectTypeToken *)outer$
                              withJavaLangReflectMethod:(JavaLangReflectMethod *)arg$0;

@end

J2OBJC_EMPTY_STATIC_INIT(ComGoogleCommonReflectTypeToken_$1)

CF_EXTERN_C_BEGIN
CF_EXTERN_C_END
#endif

J2OBJC_TYPE_LITERAL_HEADER(ComGoogleCommonReflectTypeToken_$1)
#if !defined (_ComGoogleCommonReflectTypeToken_$2_) && (ComGoogleCommonReflectTypeToken_INCLUDE_ALL || ComGoogleCommonReflectTypeToken_$2_INCLUDE)
#define _ComGoogleCommonReflectTypeToken_$2_

@class ComGoogleCommonReflectTypeToken;
@class IOSObjectArray;
@class JavaLangReflectConstructor;
@protocol JavaLangReflectType;

#define ComGoogleCommonReflectInvokable_RESTRICT 1
#define ComGoogleCommonReflectInvokable_ConstructorInvokable_INCLUDE 1
#include "com/google/common/reflect/Invokable.h"


@interface ComGoogleCommonReflectTypeToken_$2 : ComGoogleCommonReflectInvokable_ConstructorInvokable {
}

- (id<JavaLangReflectType>)getGenericReturnType;

- (IOSObjectArray *)getGenericParameterTypes;

- (IOSObjectArray *)getGenericExceptionTypes;

- (ComGoogleCommonReflectTypeToken *)getOwnerType;

- (instancetype)initWithComGoogleCommonReflectTypeToken:(ComGoogleCommonReflectTypeToken *)outer$
                         withJavaLangReflectConstructor:(JavaLangReflectConstructor *)arg$0;

@end

J2OBJC_EMPTY_STATIC_INIT(ComGoogleCommonReflectTypeToken_$2)

CF_EXTERN_C_BEGIN
CF_EXTERN_C_END
#endif

J2OBJC_TYPE_LITERAL_HEADER(ComGoogleCommonReflectTypeToken_$2)
