//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: /Users/krasnocka/Downloads/j2objc-master/guava/sources/com/google/common/reflect/Types.java
//

#include "J2ObjC_header.h"

#if !ComGoogleCommonReflectTypes_RESTRICT
#define ComGoogleCommonReflectTypes_INCLUDE_ALL 1
#endif
#undef ComGoogleCommonReflectTypes_RESTRICT
#if ComGoogleCommonReflectTypes_JavaVersionEnum_$2_INCLUDE
#define ComGoogleCommonReflectTypes_JavaVersionEnum_INCLUDE 1
#endif
#if ComGoogleCommonReflectTypes_JavaVersionEnum_$1_INCLUDE
#define ComGoogleCommonReflectTypes_JavaVersionEnum_INCLUDE 1
#endif
#if ComGoogleCommonReflectTypes_ClassOwnershipEnum_$3_INCLUDE
#define ComGoogleCommonReflectTypes_ClassOwnershipEnum_detectJvmBehavior_LocalClass_INCLUDE 1
#endif
#if ComGoogleCommonReflectTypes_ClassOwnershipEnum_$2_INCLUDE
#define ComGoogleCommonReflectTypes_ClassOwnershipEnum_INCLUDE 1
#endif
#if ComGoogleCommonReflectTypes_ClassOwnershipEnum_$1_INCLUDE
#define ComGoogleCommonReflectTypes_ClassOwnershipEnum_INCLUDE 1
#endif
#if !defined (_ComGoogleCommonReflectTypes_) && (ComGoogleCommonReflectTypes_INCLUDE_ALL || ComGoogleCommonReflectTypes_INCLUDE)
#define _ComGoogleCommonReflectTypes_

@class ComGoogleCommonBaseJoiner;
@class IOSClass;
@class IOSObjectArray;
@protocol ComGoogleCommonBaseFunction;
@protocol JavaLangIterable;
@protocol JavaLangReflectGenericDeclaration;
@protocol JavaLangReflectParameterizedType;
@protocol JavaLangReflectType;
@protocol JavaLangReflectTypeVariable;
@protocol JavaLangReflectWildcardType;
@protocol JavaUtilCollection;


@interface ComGoogleCommonReflectTypes : NSObject {
}

+ (id<JavaLangReflectType>)newArrayTypeWithJavaLangReflectType:(id<JavaLangReflectType>)componentType OBJC_METHOD_FAMILY_NONE;

+ (id<JavaLangReflectParameterizedType>)newParameterizedTypeWithOwnerWithJavaLangReflectType:(id<JavaLangReflectType>)ownerType
                                                                                withIOSClass:(IOSClass *)rawType
                                                                withJavaLangReflectTypeArray:(IOSObjectArray *)arguments OBJC_METHOD_FAMILY_NONE;

+ (id<JavaLangReflectParameterizedType>)newParameterizedTypeWithIOSClass:(IOSClass *)rawType
                                            withJavaLangReflectTypeArray:(IOSObjectArray *)arguments OBJC_METHOD_FAMILY_NONE;

+ (id<JavaLangReflectTypeVariable>)newTypeVariableWithJavaLangReflectGenericDeclaration:(id<JavaLangReflectGenericDeclaration>)declaration
                                                                           withNSString:(NSString *)name
                                                           withJavaLangReflectTypeArray:(IOSObjectArray *)bounds OBJC_METHOD_FAMILY_NONE;

+ (id<JavaLangReflectWildcardType>)subtypeOfWithJavaLangReflectType:(id<JavaLangReflectType>)upperBound;

+ (id<JavaLangReflectWildcardType>)supertypeOfWithJavaLangReflectType:(id<JavaLangReflectType>)lowerBound;

+ (NSString *)toStringWithJavaLangReflectType:(id<JavaLangReflectType>)type;

+ (id<JavaLangReflectType>)getComponentTypeWithJavaLangReflectType:(id<JavaLangReflectType>)type;

+ (jboolean)containsTypeVariableWithJavaLangReflectType:(id<JavaLangReflectType>)type;

+ (IOSClass *)getArrayClassWithIOSClass:(IOSClass *)componentType;

@end

FOUNDATION_EXPORT BOOL ComGoogleCommonReflectTypes_initialized;
J2OBJC_STATIC_INIT(ComGoogleCommonReflectTypes)

CF_EXTERN_C_BEGIN

FOUNDATION_EXPORT id<JavaLangReflectType> ComGoogleCommonReflectTypes_newArrayTypeWithJavaLangReflectType_(id<JavaLangReflectType> componentType);

FOUNDATION_EXPORT id<JavaLangReflectParameterizedType> ComGoogleCommonReflectTypes_newParameterizedTypeWithOwnerWithJavaLangReflectType_withIOSClass_withJavaLangReflectTypeArray_(id<JavaLangReflectType> ownerType, IOSClass *rawType, IOSObjectArray *arguments);

FOUNDATION_EXPORT id<JavaLangReflectParameterizedType> ComGoogleCommonReflectTypes_newParameterizedTypeWithIOSClass_withJavaLangReflectTypeArray_(IOSClass *rawType, IOSObjectArray *arguments);

FOUNDATION_EXPORT id<JavaLangReflectTypeVariable> ComGoogleCommonReflectTypes_newTypeVariableWithJavaLangReflectGenericDeclaration_withNSString_withJavaLangReflectTypeArray_(id<JavaLangReflectGenericDeclaration> declaration, NSString *name, IOSObjectArray *bounds);

FOUNDATION_EXPORT id<JavaLangReflectWildcardType> ComGoogleCommonReflectTypes_subtypeOfWithJavaLangReflectType_(id<JavaLangReflectType> upperBound);

FOUNDATION_EXPORT id<JavaLangReflectWildcardType> ComGoogleCommonReflectTypes_supertypeOfWithJavaLangReflectType_(id<JavaLangReflectType> lowerBound);

FOUNDATION_EXPORT NSString *ComGoogleCommonReflectTypes_toStringWithJavaLangReflectType_(id<JavaLangReflectType> type);

FOUNDATION_EXPORT id<JavaLangReflectType> ComGoogleCommonReflectTypes_getComponentTypeWithJavaLangReflectType_(id<JavaLangReflectType> type);

FOUNDATION_EXPORT jboolean ComGoogleCommonReflectTypes_containsTypeVariableWithJavaLangReflectType_(id<JavaLangReflectType> type);

FOUNDATION_EXPORT IOSClass *ComGoogleCommonReflectTypes_getArrayClassWithIOSClass_(IOSClass *componentType);

FOUNDATION_EXPORT id<ComGoogleCommonBaseFunction> ComGoogleCommonReflectTypes_TYPE_TO_STRING_;
J2OBJC_STATIC_FIELD_GETTER(ComGoogleCommonReflectTypes, TYPE_TO_STRING_, id<ComGoogleCommonBaseFunction>)

FOUNDATION_EXPORT ComGoogleCommonBaseJoiner *ComGoogleCommonReflectTypes_COMMA_JOINER_;
J2OBJC_STATIC_FIELD_GETTER(ComGoogleCommonReflectTypes, COMMA_JOINER_, ComGoogleCommonBaseJoiner *)
CF_EXTERN_C_END
#endif

J2OBJC_TYPE_LITERAL_HEADER(ComGoogleCommonReflectTypes)
#if !defined (_ComGoogleCommonReflectTypes_ClassOwnershipEnum_) && (ComGoogleCommonReflectTypes_INCLUDE_ALL || ComGoogleCommonReflectTypes_ClassOwnershipEnum_INCLUDE)
#define _ComGoogleCommonReflectTypes_ClassOwnershipEnum_

@class IOSClass;

#define JavaLangEnum_RESTRICT 1
#define JavaLangEnum_INCLUDE 1
#include "java/lang/Enum.h"


typedef NS_ENUM(NSUInteger, ComGoogleCommonReflectTypes_ClassOwnership) {
  ComGoogleCommonReflectTypes_ClassOwnership_OWNED_BY_ENCLOSING_CLASS = 0,
  ComGoogleCommonReflectTypes_ClassOwnership_LOCAL_CLASS_HAS_NO_OWNER = 1,
};

@interface ComGoogleCommonReflectTypes_ClassOwnershipEnum : JavaLangEnum < NSCopying > {
}

- (IOSClass *)getOwnerTypeWithIOSClass:(IOSClass *)rawType;

+ (IOSObjectArray *)values;
FOUNDATION_EXPORT IOSObjectArray *ComGoogleCommonReflectTypes_ClassOwnershipEnum_values();

+ (ComGoogleCommonReflectTypes_ClassOwnershipEnum *)valueOfWithNSString:(NSString *)name;

FOUNDATION_EXPORT ComGoogleCommonReflectTypes_ClassOwnershipEnum *ComGoogleCommonReflectTypes_ClassOwnershipEnum_valueOfWithNSString_(NSString *name);
- (id)copyWithZone:(NSZone *)zone;

@end

FOUNDATION_EXPORT BOOL ComGoogleCommonReflectTypes_ClassOwnershipEnum_initialized;
J2OBJC_STATIC_INIT(ComGoogleCommonReflectTypes_ClassOwnershipEnum)

FOUNDATION_EXPORT ComGoogleCommonReflectTypes_ClassOwnershipEnum *ComGoogleCommonReflectTypes_ClassOwnershipEnum_values_[];

#define ComGoogleCommonReflectTypes_ClassOwnershipEnum_OWNED_BY_ENCLOSING_CLASS ComGoogleCommonReflectTypes_ClassOwnershipEnum_values_[ComGoogleCommonReflectTypes_ClassOwnership_OWNED_BY_ENCLOSING_CLASS]
J2OBJC_ENUM_CONSTANT_GETTER(ComGoogleCommonReflectTypes_ClassOwnershipEnum, OWNED_BY_ENCLOSING_CLASS)

#define ComGoogleCommonReflectTypes_ClassOwnershipEnum_LOCAL_CLASS_HAS_NO_OWNER ComGoogleCommonReflectTypes_ClassOwnershipEnum_values_[ComGoogleCommonReflectTypes_ClassOwnership_LOCAL_CLASS_HAS_NO_OWNER]
J2OBJC_ENUM_CONSTANT_GETTER(ComGoogleCommonReflectTypes_ClassOwnershipEnum, LOCAL_CLASS_HAS_NO_OWNER)

FOUNDATION_EXPORT ComGoogleCommonReflectTypes_ClassOwnershipEnum *ComGoogleCommonReflectTypes_ClassOwnershipEnum_JVM_BEHAVIOR_;
J2OBJC_STATIC_FIELD_GETTER(ComGoogleCommonReflectTypes_ClassOwnershipEnum, JVM_BEHAVIOR_, ComGoogleCommonReflectTypes_ClassOwnershipEnum *)
#endif

J2OBJC_TYPE_LITERAL_HEADER(ComGoogleCommonReflectTypes_ClassOwnershipEnum)
#if !defined (_ComGoogleCommonReflectTypes_ClassOwnershipEnum_$1_) && (ComGoogleCommonReflectTypes_INCLUDE_ALL || ComGoogleCommonReflectTypes_ClassOwnershipEnum_$1_INCLUDE)
#define _ComGoogleCommonReflectTypes_ClassOwnershipEnum_$1_

@class IOSClass;


@interface ComGoogleCommonReflectTypes_ClassOwnershipEnum_$1 : ComGoogleCommonReflectTypes_ClassOwnershipEnum {
}

- (IOSClass *)getOwnerTypeWithIOSClass:(IOSClass *)rawType;

- (instancetype)initWithNSString:(NSString *)__name
                         withInt:(jint)__ordinal;

@end

J2OBJC_EMPTY_STATIC_INIT(ComGoogleCommonReflectTypes_ClassOwnershipEnum_$1)

CF_EXTERN_C_BEGIN
CF_EXTERN_C_END
#endif

J2OBJC_TYPE_LITERAL_HEADER(ComGoogleCommonReflectTypes_ClassOwnershipEnum_$1)
#if !defined (_ComGoogleCommonReflectTypes_ClassOwnershipEnum_$2_) && (ComGoogleCommonReflectTypes_INCLUDE_ALL || ComGoogleCommonReflectTypes_ClassOwnershipEnum_$2_INCLUDE)
#define _ComGoogleCommonReflectTypes_ClassOwnershipEnum_$2_

@class IOSClass;


@interface ComGoogleCommonReflectTypes_ClassOwnershipEnum_$2 : ComGoogleCommonReflectTypes_ClassOwnershipEnum {
}

- (IOSClass *)getOwnerTypeWithIOSClass:(IOSClass *)rawType;

- (instancetype)initWithNSString:(NSString *)__name
                         withInt:(jint)__ordinal;

@end

J2OBJC_EMPTY_STATIC_INIT(ComGoogleCommonReflectTypes_ClassOwnershipEnum_$2)

CF_EXTERN_C_BEGIN
CF_EXTERN_C_END
#endif

J2OBJC_TYPE_LITERAL_HEADER(ComGoogleCommonReflectTypes_ClassOwnershipEnum_$2)
#if !defined (_ComGoogleCommonReflectTypes_ClassOwnershipEnum_detectJvmBehavior_LocalClass_) && (ComGoogleCommonReflectTypes_INCLUDE_ALL || ComGoogleCommonReflectTypes_ClassOwnershipEnum_detectJvmBehavior_LocalClass_INCLUDE)
#define _ComGoogleCommonReflectTypes_ClassOwnershipEnum_detectJvmBehavior_LocalClass_


@interface ComGoogleCommonReflectTypes_ClassOwnershipEnum_detectJvmBehavior_LocalClass : NSObject {
}

- (instancetype)init;

@end

J2OBJC_EMPTY_STATIC_INIT(ComGoogleCommonReflectTypes_ClassOwnershipEnum_detectJvmBehavior_LocalClass)

CF_EXTERN_C_BEGIN
CF_EXTERN_C_END
#endif

J2OBJC_TYPE_LITERAL_HEADER(ComGoogleCommonReflectTypes_ClassOwnershipEnum_detectJvmBehavior_LocalClass)
#if !defined (_ComGoogleCommonReflectTypes_ClassOwnershipEnum_$3_) && (ComGoogleCommonReflectTypes_INCLUDE_ALL || ComGoogleCommonReflectTypes_ClassOwnershipEnum_$3_INCLUDE)
#define _ComGoogleCommonReflectTypes_ClassOwnershipEnum_$3_


@interface ComGoogleCommonReflectTypes_ClassOwnershipEnum_$3 : ComGoogleCommonReflectTypes_ClassOwnershipEnum_detectJvmBehavior_LocalClass {
}

- (instancetype)init;

@end

J2OBJC_EMPTY_STATIC_INIT(ComGoogleCommonReflectTypes_ClassOwnershipEnum_$3)

CF_EXTERN_C_BEGIN
CF_EXTERN_C_END
#endif

J2OBJC_TYPE_LITERAL_HEADER(ComGoogleCommonReflectTypes_ClassOwnershipEnum_$3)
#if !defined (_ComGoogleCommonReflectTypes_GenericArrayTypeImpl_) && (ComGoogleCommonReflectTypes_INCLUDE_ALL || ComGoogleCommonReflectTypes_GenericArrayTypeImpl_INCLUDE)
#define _ComGoogleCommonReflectTypes_GenericArrayTypeImpl_

@protocol JavaLangReflectType;

#define JavaLangReflectGenericArrayType_RESTRICT 1
#define JavaLangReflectGenericArrayType_INCLUDE 1
#include "java/lang/reflect/GenericArrayType.h"

#define JavaIoSerializable_RESTRICT 1
#define JavaIoSerializable_INCLUDE 1
#include "java/io/Serializable.h"


#define ComGoogleCommonReflectTypes_GenericArrayTypeImpl_serialVersionUID 0LL

@interface ComGoogleCommonReflectTypes_GenericArrayTypeImpl : NSObject < JavaLangReflectGenericArrayType, JavaIoSerializable > {
}

- (instancetype)initWithJavaLangReflectType:(id<JavaLangReflectType>)componentType;

- (id<JavaLangReflectType>)getGenericComponentType;

- (NSString *)description;

- (NSUInteger)hash;

- (jboolean)isEqual:(id)obj;

@end

J2OBJC_EMPTY_STATIC_INIT(ComGoogleCommonReflectTypes_GenericArrayTypeImpl)

CF_EXTERN_C_BEGIN

J2OBJC_STATIC_FIELD_GETTER(ComGoogleCommonReflectTypes_GenericArrayTypeImpl, serialVersionUID, jlong)
CF_EXTERN_C_END
#endif

J2OBJC_TYPE_LITERAL_HEADER(ComGoogleCommonReflectTypes_GenericArrayTypeImpl)
#if !defined (_ComGoogleCommonReflectTypes_ParameterizedTypeImpl_) && (ComGoogleCommonReflectTypes_INCLUDE_ALL || ComGoogleCommonReflectTypes_ParameterizedTypeImpl_INCLUDE)
#define _ComGoogleCommonReflectTypes_ParameterizedTypeImpl_

@class ComGoogleCommonCollectImmutableList;
@class IOSClass;
@class IOSObjectArray;
@protocol JavaLangReflectType;

#define JavaLangReflectParameterizedType_RESTRICT 1
#define JavaLangReflectParameterizedType_INCLUDE 1
#include "java/lang/reflect/ParameterizedType.h"

#define JavaIoSerializable_RESTRICT 1
#define JavaIoSerializable_INCLUDE 1
#include "java/io/Serializable.h"


#define ComGoogleCommonReflectTypes_ParameterizedTypeImpl_serialVersionUID 0LL

@interface ComGoogleCommonReflectTypes_ParameterizedTypeImpl : NSObject < JavaLangReflectParameterizedType, JavaIoSerializable > {
}

- (instancetype)initWithJavaLangReflectType:(id<JavaLangReflectType>)ownerType
                               withIOSClass:(IOSClass *)rawType
               withJavaLangReflectTypeArray:(IOSObjectArray *)typeArguments;

- (IOSObjectArray *)getActualTypeArguments;

- (id<JavaLangReflectType>)getRawType;

- (id<JavaLangReflectType>)getOwnerType;

- (NSString *)description;

- (NSUInteger)hash;

- (jboolean)isEqual:(id)other;

@end

J2OBJC_EMPTY_STATIC_INIT(ComGoogleCommonReflectTypes_ParameterizedTypeImpl)

CF_EXTERN_C_BEGIN

J2OBJC_STATIC_FIELD_GETTER(ComGoogleCommonReflectTypes_ParameterizedTypeImpl, serialVersionUID, jlong)
CF_EXTERN_C_END
#endif

J2OBJC_TYPE_LITERAL_HEADER(ComGoogleCommonReflectTypes_ParameterizedTypeImpl)
#if !defined (_ComGoogleCommonReflectTypes_TypeVariableImpl_) && (ComGoogleCommonReflectTypes_INCLUDE_ALL || ComGoogleCommonReflectTypes_TypeVariableImpl_INCLUDE)
#define _ComGoogleCommonReflectTypes_TypeVariableImpl_

@class ComGoogleCommonCollectImmutableList;
@class IOSObjectArray;
@protocol JavaLangReflectGenericDeclaration;

#define JavaLangReflectTypeVariable_RESTRICT 1
#define JavaLangReflectTypeVariable_INCLUDE 1
#include "java/lang/reflect/TypeVariable.h"


@interface ComGoogleCommonReflectTypes_TypeVariableImpl : NSObject < JavaLangReflectTypeVariable > {
}

- (instancetype)initWithJavaLangReflectGenericDeclaration:(id<JavaLangReflectGenericDeclaration>)genericDeclaration
                                             withNSString:(NSString *)name
                             withJavaLangReflectTypeArray:(IOSObjectArray *)bounds;

- (IOSObjectArray *)getBounds;

- (id)getGenericDeclaration;

- (NSString *)getName;

- (NSString *)description;

- (NSUInteger)hash;

- (jboolean)isEqual:(id)obj;

@end

J2OBJC_EMPTY_STATIC_INIT(ComGoogleCommonReflectTypes_TypeVariableImpl)

CF_EXTERN_C_BEGIN
CF_EXTERN_C_END
#endif

J2OBJC_TYPE_LITERAL_HEADER(ComGoogleCommonReflectTypes_TypeVariableImpl)
#if !defined (_ComGoogleCommonReflectTypes_WildcardTypeImpl_) && (ComGoogleCommonReflectTypes_INCLUDE_ALL || ComGoogleCommonReflectTypes_WildcardTypeImpl_INCLUDE)
#define _ComGoogleCommonReflectTypes_WildcardTypeImpl_

@class ComGoogleCommonCollectImmutableList;
@class IOSObjectArray;

#define JavaLangReflectWildcardType_RESTRICT 1
#define JavaLangReflectWildcardType_INCLUDE 1
#include "java/lang/reflect/WildcardType.h"

#define JavaIoSerializable_RESTRICT 1
#define JavaIoSerializable_INCLUDE 1
#include "java/io/Serializable.h"


#define ComGoogleCommonReflectTypes_WildcardTypeImpl_serialVersionUID 0LL

@interface ComGoogleCommonReflectTypes_WildcardTypeImpl : NSObject < JavaLangReflectWildcardType, JavaIoSerializable > {
}

- (instancetype)initWithJavaLangReflectTypeArray:(IOSObjectArray *)lowerBounds
                    withJavaLangReflectTypeArray:(IOSObjectArray *)upperBounds;

- (IOSObjectArray *)getLowerBounds;

- (IOSObjectArray *)getUpperBounds;

- (jboolean)isEqual:(id)obj;

- (NSUInteger)hash;

- (NSString *)description;

@end

J2OBJC_EMPTY_STATIC_INIT(ComGoogleCommonReflectTypes_WildcardTypeImpl)

CF_EXTERN_C_BEGIN

J2OBJC_STATIC_FIELD_GETTER(ComGoogleCommonReflectTypes_WildcardTypeImpl, serialVersionUID, jlong)
CF_EXTERN_C_END
#endif

J2OBJC_TYPE_LITERAL_HEADER(ComGoogleCommonReflectTypes_WildcardTypeImpl)
#if !defined (_ComGoogleCommonReflectTypes_JavaVersionEnum_) && (ComGoogleCommonReflectTypes_INCLUDE_ALL || ComGoogleCommonReflectTypes_JavaVersionEnum_INCLUDE)
#define _ComGoogleCommonReflectTypes_JavaVersionEnum_

@class ComGoogleCommonCollectImmutableList;
@class IOSObjectArray;
@protocol JavaLangReflectType;

#define JavaLangEnum_RESTRICT 1
#define JavaLangEnum_INCLUDE 1
#include "java/lang/Enum.h"


typedef NS_ENUM(NSUInteger, ComGoogleCommonReflectTypes_JavaVersion) {
  ComGoogleCommonReflectTypes_JavaVersion_JAVA6 = 0,
  ComGoogleCommonReflectTypes_JavaVersion_JAVA7 = 1,
};

@interface ComGoogleCommonReflectTypes_JavaVersionEnum : JavaLangEnum < NSCopying > {
}

- (id<JavaLangReflectType>)newArrayTypeWithJavaLangReflectType:(id<JavaLangReflectType>)componentType OBJC_METHOD_FAMILY_NONE;

- (id<JavaLangReflectType>)usedInGenericTypeWithJavaLangReflectType:(id<JavaLangReflectType>)type;

- (ComGoogleCommonCollectImmutableList *)usedInGenericTypeWithJavaLangReflectTypeArray:(IOSObjectArray *)types;

- (instancetype)initWithNSString:(NSString *)__name
                         withInt:(jint)__ordinal;

+ (IOSObjectArray *)values;
FOUNDATION_EXPORT IOSObjectArray *ComGoogleCommonReflectTypes_JavaVersionEnum_values();

+ (ComGoogleCommonReflectTypes_JavaVersionEnum *)valueOfWithNSString:(NSString *)name;

FOUNDATION_EXPORT ComGoogleCommonReflectTypes_JavaVersionEnum *ComGoogleCommonReflectTypes_JavaVersionEnum_valueOfWithNSString_(NSString *name);
- (id)copyWithZone:(NSZone *)zone;

@end

FOUNDATION_EXPORT BOOL ComGoogleCommonReflectTypes_JavaVersionEnum_initialized;
J2OBJC_STATIC_INIT(ComGoogleCommonReflectTypes_JavaVersionEnum)

FOUNDATION_EXPORT ComGoogleCommonReflectTypes_JavaVersionEnum *ComGoogleCommonReflectTypes_JavaVersionEnum_values_[];

#define ComGoogleCommonReflectTypes_JavaVersionEnum_JAVA6 ComGoogleCommonReflectTypes_JavaVersionEnum_values_[ComGoogleCommonReflectTypes_JavaVersion_JAVA6]
J2OBJC_ENUM_CONSTANT_GETTER(ComGoogleCommonReflectTypes_JavaVersionEnum, JAVA6)

#define ComGoogleCommonReflectTypes_JavaVersionEnum_JAVA7 ComGoogleCommonReflectTypes_JavaVersionEnum_values_[ComGoogleCommonReflectTypes_JavaVersion_JAVA7]
J2OBJC_ENUM_CONSTANT_GETTER(ComGoogleCommonReflectTypes_JavaVersionEnum, JAVA7)

FOUNDATION_EXPORT ComGoogleCommonReflectTypes_JavaVersionEnum *ComGoogleCommonReflectTypes_JavaVersionEnum_CURRENT_;
J2OBJC_STATIC_FIELD_GETTER(ComGoogleCommonReflectTypes_JavaVersionEnum, CURRENT_, ComGoogleCommonReflectTypes_JavaVersionEnum *)
#endif

J2OBJC_TYPE_LITERAL_HEADER(ComGoogleCommonReflectTypes_JavaVersionEnum)
#if !defined (_ComGoogleCommonReflectTypes_JavaVersionEnum_$1_) && (ComGoogleCommonReflectTypes_INCLUDE_ALL || ComGoogleCommonReflectTypes_JavaVersionEnum_$1_INCLUDE)
#define _ComGoogleCommonReflectTypes_JavaVersionEnum_$1_

@protocol JavaLangReflectGenericArrayType;
@protocol JavaLangReflectType;


@interface ComGoogleCommonReflectTypes_JavaVersionEnum_$1 : ComGoogleCommonReflectTypes_JavaVersionEnum {
}

- (id<JavaLangReflectGenericArrayType>)newArrayTypeWithJavaLangReflectType:(id<JavaLangReflectType>)componentType OBJC_METHOD_FAMILY_NONE;

- (id<JavaLangReflectType>)usedInGenericTypeWithJavaLangReflectType:(id<JavaLangReflectType>)type;

- (instancetype)initWithNSString:(NSString *)__name
                         withInt:(jint)__ordinal;

@end

J2OBJC_EMPTY_STATIC_INIT(ComGoogleCommonReflectTypes_JavaVersionEnum_$1)

CF_EXTERN_C_BEGIN
CF_EXTERN_C_END
#endif

J2OBJC_TYPE_LITERAL_HEADER(ComGoogleCommonReflectTypes_JavaVersionEnum_$1)
#if !defined (_ComGoogleCommonReflectTypes_JavaVersionEnum_$2_) && (ComGoogleCommonReflectTypes_INCLUDE_ALL || ComGoogleCommonReflectTypes_JavaVersionEnum_$2_INCLUDE)
#define _ComGoogleCommonReflectTypes_JavaVersionEnum_$2_

@protocol JavaLangReflectType;


@interface ComGoogleCommonReflectTypes_JavaVersionEnum_$2 : ComGoogleCommonReflectTypes_JavaVersionEnum {
}

- (id<JavaLangReflectType>)newArrayTypeWithJavaLangReflectType:(id<JavaLangReflectType>)componentType OBJC_METHOD_FAMILY_NONE;

- (id<JavaLangReflectType>)usedInGenericTypeWithJavaLangReflectType:(id<JavaLangReflectType>)type;

- (instancetype)initWithNSString:(NSString *)__name
                         withInt:(jint)__ordinal;

@end

J2OBJC_EMPTY_STATIC_INIT(ComGoogleCommonReflectTypes_JavaVersionEnum_$2)

CF_EXTERN_C_BEGIN
CF_EXTERN_C_END
#endif

J2OBJC_TYPE_LITERAL_HEADER(ComGoogleCommonReflectTypes_JavaVersionEnum_$2)
#if !defined (_ComGoogleCommonReflectTypes_JavaVersionEnum_$3_) && (ComGoogleCommonReflectTypes_INCLUDE_ALL || ComGoogleCommonReflectTypes_JavaVersionEnum_$3_INCLUDE)
#define _ComGoogleCommonReflectTypes_JavaVersionEnum_$3_

#define ComGoogleCommonReflectTypeCapture_RESTRICT 1
#define ComGoogleCommonReflectTypeCapture_INCLUDE 1
#include "com/google/common/reflect/TypeCapture.h"


@interface ComGoogleCommonReflectTypes_JavaVersionEnum_$3 : ComGoogleCommonReflectTypeCapture {
}

- (instancetype)init;

@end

J2OBJC_EMPTY_STATIC_INIT(ComGoogleCommonReflectTypes_JavaVersionEnum_$3)

CF_EXTERN_C_BEGIN
CF_EXTERN_C_END
#endif

J2OBJC_TYPE_LITERAL_HEADER(ComGoogleCommonReflectTypes_JavaVersionEnum_$3)
#if !defined (_ComGoogleCommonReflectTypes_$1_) && (ComGoogleCommonReflectTypes_INCLUDE_ALL || ComGoogleCommonReflectTypes_$1_INCLUDE)
#define _ComGoogleCommonReflectTypes_$1_

@protocol JavaLangReflectType;

#define ComGoogleCommonBaseFunction_RESTRICT 1
#define ComGoogleCommonBaseFunction_INCLUDE 1
#include "com/google/common/base/Function.h"


@interface ComGoogleCommonReflectTypes_$1 : NSObject < ComGoogleCommonBaseFunction > {
}

- (NSString *)applyWithId:(id<JavaLangReflectType>)from;

- (instancetype)init;

@end

J2OBJC_EMPTY_STATIC_INIT(ComGoogleCommonReflectTypes_$1)

CF_EXTERN_C_BEGIN
CF_EXTERN_C_END
#endif

J2OBJC_TYPE_LITERAL_HEADER(ComGoogleCommonReflectTypes_$1)
