//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: android/libcore/luni/src/main/java/javax/security/cert/CertificateEncodingException.java
//

#ifndef _JavaxSecurityCertCertificateEncodingException_H_
#define _JavaxSecurityCertCertificateEncodingException_H_

#include "J2ObjC_header.h"
#include "javax/security/cert/CertificateException.h"

#define JavaxSecurityCertCertificateEncodingException_serialVersionUID -8187642723048403470LL

@interface JavaxSecurityCertCertificateEncodingException : JavaxSecurityCertCertificateException {
}

- (instancetype)initWithNSString:(NSString *)msg;

- (instancetype)init;

@end

J2OBJC_EMPTY_STATIC_INIT(JavaxSecurityCertCertificateEncodingException)

CF_EXTERN_C_BEGIN

J2OBJC_STATIC_FIELD_GETTER(JavaxSecurityCertCertificateEncodingException, serialVersionUID, jlong)
CF_EXTERN_C_END

J2OBJC_TYPE_LITERAL_HEADER(JavaxSecurityCertCertificateEncodingException)

#endif // _JavaxSecurityCertCertificateEncodingException_H_
