//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: android/libcore/luni/src/main/java/javax/security/cert/CertificateNotYetValidException.java
//

#ifndef _JavaxSecurityCertCertificateNotYetValidException_H_
#define _JavaxSecurityCertCertificateNotYetValidException_H_

#include "J2ObjC_header.h"
#include "javax/security/cert/CertificateException.h"

#define JavaxSecurityCertCertificateNotYetValidException_serialVersionUID -8976172474266822818LL

@interface JavaxSecurityCertCertificateNotYetValidException : JavaxSecurityCertCertificateException {
}

- (instancetype)initWithNSString:(NSString *)msg;

- (instancetype)init;

@end

J2OBJC_EMPTY_STATIC_INIT(JavaxSecurityCertCertificateNotYetValidException)

CF_EXTERN_C_BEGIN

J2OBJC_STATIC_FIELD_GETTER(JavaxSecurityCertCertificateNotYetValidException, serialVersionUID, jlong)
CF_EXTERN_C_END

J2OBJC_TYPE_LITERAL_HEADER(JavaxSecurityCertCertificateNotYetValidException)

#endif // _JavaxSecurityCertCertificateNotYetValidException_H_
