//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: android/libcore/luni/src/main/java/java/security/interfaces/ECKey.java
//

#ifndef _JavaSecurityInterfacesECKey_H_
#define _JavaSecurityInterfacesECKey_H_

@class JavaSecuritySpecECParameterSpec;

#include "J2ObjC_header.h"

@protocol JavaSecurityInterfacesECKey < NSObject, JavaObject >

- (JavaSecuritySpecECParameterSpec *)getParams;

@end

J2OBJC_EMPTY_STATIC_INIT(JavaSecurityInterfacesECKey)

J2OBJC_TYPE_LITERAL_HEADER(JavaSecurityInterfacesECKey)

#endif // _JavaSecurityInterfacesECKey_H_
