//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: /Users/krasnocka/Downloads/j2objc-master/testing/mockito/build_result/java/org/mockito/internal/progress/HandyReturnValues.java
//

#ifndef _OrgMockitoInternalProgressHandyReturnValues_H_
#define _OrgMockitoInternalProgressHandyReturnValues_H_

@class IOSClass;
@protocol JavaUtilList;
@protocol JavaUtilMap;
@protocol JavaUtilSet;

#include "J2ObjC_header.h"

@interface OrgMockitoInternalProgressHandyReturnValues : NSObject {
}

- (jbyte)returnZero;

- (jchar)returnChar;

- (id)returnNull;

- (jboolean)returnFalse;

- (NSString *)returnString;

- (id)returnForWithIOSClass:(IOSClass *)clazz;

- (id<JavaUtilMap>)returnMap;

- (id<JavaUtilList>)returnList;

- (id<JavaUtilSet>)returnSet;

- (id)returnForWithId:(id)instance;

- (instancetype)init;

@end

J2OBJC_EMPTY_STATIC_INIT(OrgMockitoInternalProgressHandyReturnValues)

CF_EXTERN_C_BEGIN
CF_EXTERN_C_END

J2OBJC_TYPE_LITERAL_HEADER(OrgMockitoInternalProgressHandyReturnValues)

#endif // _OrgMockitoInternalProgressHandyReturnValues_H_
