//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: /Users/krasnocka/Downloads/j2objc-master/testing/mockito/build_result/java/org/mockito/internal/progress/MockingProgressImpl.java
//

#ifndef _OrgMockitoInternalProgressMockingProgressImpl_H_
#define _OrgMockitoInternalProgressMockingProgressImpl_H_

@class IOSClass;
@class OrgMockitoExceptionsReporter;
@class OrgMockitoInternalDebuggingLocalized;
@protocol OrgMockitoInternalListenersMockingProgressListener;
@protocol OrgMockitoInternalProgressArgumentMatcherStorage;
@protocol OrgMockitoInternalProgressIOngoingStubbing;
@protocol OrgMockitoInvocationInvocation;
@protocol OrgMockitoInvocationLocation;
@protocol OrgMockitoVerificationVerificationMode;

#include "J2ObjC_header.h"
#include "org/mockito/internal/progress/MockingProgress.h"

@interface OrgMockitoInternalProgressMockingProgressImpl : NSObject < OrgMockitoInternalProgressMockingProgress > {
 @public
  id<OrgMockitoInternalProgressIOngoingStubbing> iOngoingStubbing_;
}

- (void)reportOngoingStubbingWithOrgMockitoInternalProgressIOngoingStubbing:(id<OrgMockitoInternalProgressIOngoingStubbing>)iOngoingStubbing;

- (id<OrgMockitoInternalProgressIOngoingStubbing>)pullOngoingStubbing;

- (void)verificationStartedWithOrgMockitoVerificationVerificationMode:(id<OrgMockitoVerificationVerificationMode>)verify;

- (void)resetOngoingStubbing;

- (id<OrgMockitoVerificationVerificationMode>)pullVerificationMode;

- (void)stubbingStarted;

- (void)validateState;

- (void)stubbingCompletedWithOrgMockitoInvocationInvocation:(id<OrgMockitoInvocationInvocation>)invocation;

- (NSString *)description;

- (void)reset;

- (id<OrgMockitoInternalProgressArgumentMatcherStorage>)getArgumentMatcherStorage;

- (void)mockingStartedWithId:(id)mock
                withIOSClass:(IOSClass *)classToMock;

- (void)setListenerWithOrgMockitoInternalListenersMockingProgressListener:(id<OrgMockitoInternalListenersMockingProgressListener>)listener;

- (instancetype)init;

@end

J2OBJC_EMPTY_STATIC_INIT(OrgMockitoInternalProgressMockingProgressImpl)

J2OBJC_FIELD_SETTER(OrgMockitoInternalProgressMockingProgressImpl, iOngoingStubbing_, id<OrgMockitoInternalProgressIOngoingStubbing>)

CF_EXTERN_C_BEGIN
CF_EXTERN_C_END

J2OBJC_TYPE_LITERAL_HEADER(OrgMockitoInternalProgressMockingProgressImpl)

#endif // _OrgMockitoInternalProgressMockingProgressImpl_H_
