//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: android/libcore/luni/src/main/java/javax/xml/transform/TransformerFactoryConfigurationError.java
//

#ifndef _JavaxXmlTransformTransformerFactoryConfigurationError_H_
#define _JavaxXmlTransformTransformerFactoryConfigurationError_H_

@class JavaLangException;

#include "J2ObjC_header.h"
#include "java/lang/Error.h"

@interface JavaxXmlTransformTransformerFactoryConfigurationError : JavaLangError {
}

- (instancetype)init;

- (instancetype)initWithNSString:(NSString *)msg;

- (instancetype)initWithJavaLangException:(JavaLangException *)e;

- (instancetype)initWithJavaLangException:(JavaLangException *)e
                             withNSString:(NSString *)msg;

- (NSString *)getMessage;

- (JavaLangException *)getException;

@end

J2OBJC_EMPTY_STATIC_INIT(JavaxXmlTransformTransformerFactoryConfigurationError)

CF_EXTERN_C_BEGIN
CF_EXTERN_C_END

J2OBJC_TYPE_LITERAL_HEADER(JavaxXmlTransformTransformerFactoryConfigurationError)

#endif // _JavaxXmlTransformTransformerFactoryConfigurationError_H_
