//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: /Users/krasnocka/Downloads/j2objc-master/testing/mockito/build_result/java/org/mockito/internal/util/MockitoSpy.java
//

#ifndef _OrgMockitoInternalUtilMockitoSpy_H_
#define _OrgMockitoInternalUtilMockitoSpy_H_

#include "J2ObjC_header.h"

@protocol OrgMockitoInternalUtilMockitoSpy < NSObject, JavaObject >

@end

J2OBJC_EMPTY_STATIC_INIT(OrgMockitoInternalUtilMockitoSpy)

J2OBJC_TYPE_LITERAL_HEADER(OrgMockitoInternalUtilMockitoSpy)

#endif // _OrgMockitoInternalUtilMockitoSpy_H_
