//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: /Users/krasnocka/Downloads/j2objc-master/testing/mockito/build_result/java/org/mockito/internal/util/StringJoiner.java
//

#ifndef _OrgMockitoInternalUtilStringJoiner_H_
#define _OrgMockitoInternalUtilStringJoiner_H_

@class IOSObjectArray;
@class JavaLangStringBuilder;

#include "J2ObjC_header.h"

@interface OrgMockitoInternalUtilStringJoiner : NSObject {
}

+ (NSString *)joinWithNSObjectArray:(IOSObjectArray *)linesToBreak;

- (instancetype)init;

@end

J2OBJC_EMPTY_STATIC_INIT(OrgMockitoInternalUtilStringJoiner)

CF_EXTERN_C_BEGIN

FOUNDATION_EXPORT NSString *OrgMockitoInternalUtilStringJoiner_joinWithNSObjectArray_(IOSObjectArray *linesToBreak);
CF_EXTERN_C_END

J2OBJC_TYPE_LITERAL_HEADER(OrgMockitoInternalUtilStringJoiner)

#endif // _OrgMockitoInternalUtilStringJoiner_H_
