//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: android/frameworks/base/core/java/android/util/Printer.java
//

#ifndef _AndroidUtilPrinter_H_
#define _AndroidUtilPrinter_H_

#include "J2ObjC_header.h"

@protocol AndroidUtilPrinter < NSObject, JavaObject >

- (void)printlnWithNSString:(NSString *)x;

@end

J2OBJC_EMPTY_STATIC_INIT(AndroidUtilPrinter)

J2OBJC_TYPE_LITERAL_HEADER(AndroidUtilPrinter)

#endif // _AndroidUtilPrinter_H_
