//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: android/libcore/luni/src/main/java/java/nio/Buffer.java
//

#ifndef _JavaNioBuffer_H_
#define _JavaNioBuffer_H_

#include "J2ObjC_header.h"

#define JavaNioBuffer_UNSET_MARK -1

@interface JavaNioBuffer : NSObject {
 @public
  jint capacity__;
  jint limit__;
  jint mark__;
  jint position__;
  jint _elementSizeShift_;
  jlong effectiveDirectAddress_;
}

- (instancetype)initWithInt:(jint)elementSizeShift
                    withInt:(jint)capacity
                   withLong:(jlong)effectiveDirectAddress;

- (id)array;

- (jint)arrayOffset;

- (jint)capacity;

- (void)checkIndexWithInt:(jint)index;

- (void)checkIndexWithInt:(jint)index
                  withInt:(jint)sizeOfType;

- (jint)checkGetBoundsWithInt:(jint)bytesPerElement
                      withInt:(jint)length
                      withInt:(jint)offset
                      withInt:(jint)count;

- (jint)checkPutBoundsWithInt:(jint)bytesPerElement
                      withInt:(jint)length
                      withInt:(jint)offset
                      withInt:(jint)count;

- (void)checkStartEndRemainingWithInt:(jint)start
                              withInt:(jint)end;

- (JavaNioBuffer *)clear;

- (JavaNioBuffer *)flip;

- (jboolean)hasArray;

- (jboolean)hasRemaining;

- (jboolean)isDirect;

- (jboolean)isReadOnly;

- (void)checkWritable;

- (jint)limit;

- (JavaNioBuffer *)limitWithInt:(jint)newLimit;

- (JavaNioBuffer *)mark;

- (jint)position;

- (JavaNioBuffer *)positionWithInt:(jint)newPosition;

- (void)positionImplWithInt:(jint)newPosition;

- (jint)remaining;

- (JavaNioBuffer *)reset;

- (JavaNioBuffer *)rewind;

- (NSString *)description;

- (jint)getElementSizeShift;

@end

J2OBJC_EMPTY_STATIC_INIT(JavaNioBuffer)

CF_EXTERN_C_BEGIN

J2OBJC_STATIC_FIELD_GETTER(JavaNioBuffer, UNSET_MARK, jint)
CF_EXTERN_C_END

J2OBJC_TYPE_LITERAL_HEADER(JavaNioBuffer)

#endif // _JavaNioBuffer_H_
