//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: android/libcore/luni/src/main/java/java/nio/CharArrayBuffer.java
//

#ifndef _JavaNioCharArrayBuffer_H_
#define _JavaNioCharArrayBuffer_H_

@class IOSCharArray;
@class JavaNioByteOrder;

#include "J2ObjC_header.h"
#include "java/nio/CharBuffer.h"

@interface JavaNioCharArrayBuffer : JavaNioCharBuffer {
}

- (instancetype)initWithCharArray:(IOSCharArray *)array;

- (JavaNioCharBuffer *)asReadOnlyBuffer;

- (JavaNioCharBuffer *)compact;

- (JavaNioCharBuffer *)duplicate;

- (JavaNioCharBuffer *)slice;

- (jboolean)isReadOnly;

- (IOSCharArray *)protectedArray;

- (jint)protectedArrayOffset;

- (jboolean)protectedHasArray;

- (jchar)get;

- (jchar)getWithInt:(jint)index;

- (JavaNioCharBuffer *)getWithCharArray:(IOSCharArray *)dst
                                withInt:(jint)srcOffset
                                withInt:(jint)charCount;

- (jboolean)isDirect;

- (JavaNioByteOrder *)order;

- (JavaNioCharBuffer *)subSequenceFrom:(int)start to:(int)end;

- (JavaNioCharBuffer *)putWithChar:(jchar)c;

- (JavaNioCharBuffer *)putWithInt:(jint)index
                         withChar:(jchar)c;

- (JavaNioCharBuffer *)putWithCharArray:(IOSCharArray *)src
                                withInt:(jint)srcOffset
                                withInt:(jint)charCount;

- (NSString *)description;

@end

J2OBJC_EMPTY_STATIC_INIT(JavaNioCharArrayBuffer)

CF_EXTERN_C_BEGIN
CF_EXTERN_C_END

J2OBJC_TYPE_LITERAL_HEADER(JavaNioCharArrayBuffer)

#endif // _JavaNioCharArrayBuffer_H_
