//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: apache_harmony/classlib/modules/nio/src/main/java/common/java/nio/ReadWriteHeapByteBuffer.java
//
//  Created by tball on 7/15/13.
//

#ifndef _JavaNioReadWriteHeapByteBuffer_H_
#define _JavaNioReadWriteHeapByteBuffer_H_

@class IOSByteArray;
@class JavaNioByteBuffer;

#import "JreEmulation.h"
#include "java/nio/HeapByteBuffer.h"

@interface JavaNioReadWriteHeapByteBuffer : JavaNioHeapByteBuffer {
}

+ (JavaNioReadWriteHeapByteBuffer *)copy__WithJavaNioHeapByteBuffer:(JavaNioHeapByteBuffer *)other
                                                            withInt:(int)markOfOther OBJC_METHOD_FAMILY_NONE;
- (id)initWithByteArray:(IOSByteArray *)backingArray;
- (id)initWithInt:(int)capacity;
- (id)initWithByteArray:(IOSByteArray *)backingArray
                withInt:(int)capacity
                withInt:(int)arrayOffset;
- (JavaNioByteBuffer *)asReadOnlyBuffer;
- (JavaNioByteBuffer *)compact;
- (JavaNioByteBuffer *)duplicate;
- (BOOL)isReadOnly;
- (IOSByteArray *)protectedArray;
- (int)protectedArrayOffset;
- (BOOL)protectedHasArray;
- (JavaNioByteBuffer *)putWithChar:(char)b;
- (JavaNioByteBuffer *)putWithInt:(int)index
                         withChar:(char)b;
- (JavaNioByteBuffer *)putWithByteArray:(IOSByteArray *)src
                                withInt:(int)off
                                withInt:(int)len;
- (JavaNioByteBuffer *)putDoubleWithDouble:(double)value;
- (JavaNioByteBuffer *)putDoubleWithInt:(int)index
                             withDouble:(double)value;
- (JavaNioByteBuffer *)putFloatWithFloat:(float)value;
- (JavaNioByteBuffer *)putFloatWithInt:(int)index
                             withFloat:(float)value;
- (JavaNioByteBuffer *)putIntWithInt:(int)value;
- (JavaNioByteBuffer *)putIntWithInt:(int)index
                             withInt:(int)value;
- (JavaNioByteBuffer *)putLongWithInt:(int)index
                          withLongInt:(long long int)value;
- (JavaNioByteBuffer *)putLongWithLongInt:(long long int)value;
- (JavaNioByteBuffer *)putShortWithInt:(int)index
                          withShortInt:(short int)value;
- (JavaNioByteBuffer *)putShortWithShortInt:(short int)value;
- (JavaNioByteBuffer *)slice;
@end

#endif // _JavaNioReadWriteHeapByteBuffer_H_
