//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: android/libcore/luni/src/main/java/java/text/AttributedCharacterIterator.java
//

#ifndef _JavaTextAttributedCharacterIterator_H_
#define _JavaTextAttributedCharacterIterator_H_

@class JavaTextAttributedCharacterIterator_Attribute;
@protocol JavaUtilMap;
@protocol JavaUtilSet;

#include "J2ObjC_header.h"
#include "java/io/Serializable.h"
#include "java/text/CharacterIterator.h"

@protocol JavaTextAttributedCharacterIterator < JavaTextCharacterIterator, NSObject, JavaObject >
- (id<JavaUtilSet>)getAllAttributeKeys;

- (id)getAttributeWithJavaTextAttributedCharacterIterator_Attribute:(JavaTextAttributedCharacterIterator_Attribute *)attribute;

- (id<JavaUtilMap>)getAttributes;

- (jint)getRunLimit;

- (jint)getRunLimitWithJavaTextAttributedCharacterIterator_Attribute:(JavaTextAttributedCharacterIterator_Attribute *)attribute;

- (jint)getRunLimitWithJavaUtilSet:(id<JavaUtilSet>)attributes;

- (jint)getRunStart;

- (jint)getRunStartWithJavaTextAttributedCharacterIterator_Attribute:(JavaTextAttributedCharacterIterator_Attribute *)attribute;

- (jint)getRunStartWithJavaUtilSet:(id<JavaUtilSet>)attributes;

@end

J2OBJC_EMPTY_STATIC_INIT(JavaTextAttributedCharacterIterator)

J2OBJC_TYPE_LITERAL_HEADER(JavaTextAttributedCharacterIterator)

#define JavaTextAttributedCharacterIterator_Attribute_serialVersionUID -9142742483513960612LL

@interface JavaTextAttributedCharacterIterator_Attribute : NSObject < JavaIoSerializable > {
}

- (instancetype)initWithNSString:(NSString *)name;

- (jboolean)isEqual:(id)object;

- (NSString *)getName;

- (NSUInteger)hash;

- (id)readResolve;

- (NSString *)description;

@end

FOUNDATION_EXPORT BOOL JavaTextAttributedCharacterIterator_Attribute_initialized;
J2OBJC_STATIC_INIT(JavaTextAttributedCharacterIterator_Attribute)

CF_EXTERN_C_BEGIN

J2OBJC_STATIC_FIELD_GETTER(JavaTextAttributedCharacterIterator_Attribute, serialVersionUID, jlong)

FOUNDATION_EXPORT JavaTextAttributedCharacterIterator_Attribute *JavaTextAttributedCharacterIterator_Attribute_INPUT_METHOD_SEGMENT_;
J2OBJC_STATIC_FIELD_GETTER(JavaTextAttributedCharacterIterator_Attribute, INPUT_METHOD_SEGMENT_, JavaTextAttributedCharacterIterator_Attribute *)

FOUNDATION_EXPORT JavaTextAttributedCharacterIterator_Attribute *JavaTextAttributedCharacterIterator_Attribute_LANGUAGE_;
J2OBJC_STATIC_FIELD_GETTER(JavaTextAttributedCharacterIterator_Attribute, LANGUAGE_, JavaTextAttributedCharacterIterator_Attribute *)

FOUNDATION_EXPORT JavaTextAttributedCharacterIterator_Attribute *JavaTextAttributedCharacterIterator_Attribute_READING_;
J2OBJC_STATIC_FIELD_GETTER(JavaTextAttributedCharacterIterator_Attribute, READING_, JavaTextAttributedCharacterIterator_Attribute *)
CF_EXTERN_C_END

J2OBJC_TYPE_LITERAL_HEADER(JavaTextAttributedCharacterIterator_Attribute)

#endif // _JavaTextAttributedCharacterIterator_H_
