//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: android/libcore/luni/src/main/java/java/text/DecimalFormat.java
//

#ifndef _JavaTextDecimalFormat_H_
#define _JavaTextDecimalFormat_H_

@class JavaLangDouble;
@class JavaLangStringBuffer;
@class JavaMathRoundingModeEnum;
@class JavaTextDecimalFormatSymbols;
@class JavaTextFieldPosition;
@class JavaTextParsePosition;
@class JavaUtilCurrency;
@class JavaUtilLocale;
@class LibcoreIcuNativeDecimalFormat;
@protocol JavaTextAttributedCharacterIterator;

#include "J2ObjC_header.h"
#include "java/text/NumberFormat.h"

#define JavaTextDecimalFormat_serialVersionUID 864413376551465018LL

@interface JavaTextDecimalFormat : JavaTextNumberFormat {
}

- (instancetype)init;

- (instancetype)initWithNSString:(NSString *)pattern;

- (instancetype)initWithNSString:(NSString *)pattern
withJavaTextDecimalFormatSymbols:(JavaTextDecimalFormatSymbols *)value;

- (instancetype)initWithNSString:(NSString *)pattern
              withJavaUtilLocale:(JavaUtilLocale *)locale;

- (void)applyLocalizedPatternWithNSString:(NSString *)pattern;

- (void)applyPatternWithNSString:(NSString *)pattern;

- (id)clone;

- (jboolean)isEqual:(id)object;

- (id<JavaTextAttributedCharacterIterator>)formatToCharacterIteratorWithId:(id)object;

- (JavaLangStringBuffer *)formatWithDouble:(jdouble)value
                  withJavaLangStringBuffer:(JavaLangStringBuffer *)buffer
                 withJavaTextFieldPosition:(JavaTextFieldPosition *)position;

- (JavaLangStringBuffer *)formatWithLong:(jlong)value
                withJavaLangStringBuffer:(JavaLangStringBuffer *)buffer
               withJavaTextFieldPosition:(JavaTextFieldPosition *)position;

- (JavaLangStringBuffer *)formatWithId:(id)number
              withJavaLangStringBuffer:(JavaLangStringBuffer *)buffer
             withJavaTextFieldPosition:(JavaTextFieldPosition *)position;

- (JavaTextDecimalFormatSymbols *)getDecimalFormatSymbols;

- (JavaUtilCurrency *)getCurrency;

- (jint)getGroupingSize;

- (jint)getMultiplier;

- (NSString *)getNegativePrefix;

- (NSString *)getNegativeSuffix;

- (NSString *)getPositivePrefix;

- (NSString *)getPositiveSuffix;

- (NSUInteger)hash;

- (jboolean)isDecimalSeparatorAlwaysShown;

- (jboolean)isParseBigDecimal;

- (void)setParseIntegerOnlyWithBoolean:(jboolean)value;

- (jboolean)isParseIntegerOnly;

- (NSNumber *)parseWithNSString:(NSString *)string
      withJavaTextParsePosition:(JavaTextParsePosition *)position;

- (void)setDecimalFormatSymbolsWithJavaTextDecimalFormatSymbols:(JavaTextDecimalFormatSymbols *)value;

- (void)setCurrencyWithJavaUtilCurrency:(JavaUtilCurrency *)currency;

- (void)setDecimalSeparatorAlwaysShownWithBoolean:(jboolean)value;

- (void)setGroupingSizeWithInt:(jint)value;

- (void)setGroupingUsedWithBoolean:(jboolean)value;

- (jboolean)isGroupingUsed;

- (void)setMaximumFractionDigitsWithInt:(jint)value;

- (void)setMaximumIntegerDigitsWithInt:(jint)value;

- (void)setMinimumFractionDigitsWithInt:(jint)value;

- (void)setMinimumIntegerDigitsWithInt:(jint)value;

- (void)setMultiplierWithInt:(jint)value;

- (void)setNegativePrefixWithNSString:(NSString *)value;

- (void)setNegativeSuffixWithNSString:(NSString *)value;

- (void)setPositivePrefixWithNSString:(NSString *)value;

- (void)setPositiveSuffixWithNSString:(NSString *)value;

- (void)setParseBigDecimalWithBoolean:(jboolean)newValue;

- (NSString *)toLocalizedPattern;

- (NSString *)toPattern;

- (JavaMathRoundingModeEnum *)getRoundingMode;

- (void)setRoundingModeWithJavaMathRoundingModeEnum:(JavaMathRoundingModeEnum *)roundingMode;

@end

FOUNDATION_EXPORT BOOL JavaTextDecimalFormat_initialized;
J2OBJC_STATIC_INIT(JavaTextDecimalFormat)

CF_EXTERN_C_BEGIN

J2OBJC_STATIC_FIELD_GETTER(JavaTextDecimalFormat, serialVersionUID, jlong)

FOUNDATION_EXPORT JavaLangDouble *JavaTextDecimalFormat_NEGATIVE_ZERO_DOUBLE_;
J2OBJC_STATIC_FIELD_GETTER(JavaTextDecimalFormat, NEGATIVE_ZERO_DOUBLE_, JavaLangDouble *)
CF_EXTERN_C_END

J2OBJC_TYPE_LITERAL_HEADER(JavaTextDecimalFormat)

#endif // _JavaTextDecimalFormat_H_
