//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: Classes/java/text/IOSCollator.java
//

#ifndef _JavaTextIOSCollator_H_
#define _JavaTextIOSCollator_H_

@class IOSByteArray;
@class JavaUtilLocale;

#include "J2ObjC_header.h"
#include "java/text/CollationKey.h"
#include "java/text/Collator.h"

@interface JavaTextIOSCollator : JavaTextCollator {
}

- (instancetype)initWithJavaUtilLocale:(JavaUtilLocale *)locale;

- (jint)compareWithNSString:(NSString *)string1
               withNSString:(NSString *)string2;

- (jint)getDecomposition;

- (jint)getStrength;

- (void)setDecompositionWithInt:(jint)value;

- (void)setStrengthWithInt:(jint)value;

- (NSUInteger)hash;

- (jboolean)isEqual:(id)obj;

- (JavaTextCollationKey *)getCollationKeyWithNSString:(NSString *)string;

@end

J2OBJC_EMPTY_STATIC_INIT(JavaTextIOSCollator)

CF_EXTERN_C_BEGIN
CF_EXTERN_C_END

J2OBJC_TYPE_LITERAL_HEADER(JavaTextIOSCollator)

@interface JavaTextIOSCollator_IOSCollationKey : JavaTextCollationKey {
}

- (instancetype)initWithNSString:(NSString *)source;

- (jint)compareToWithId:(JavaTextCollationKey *)value;

- (IOSByteArray *)toByteArray;

@end

J2OBJC_EMPTY_STATIC_INIT(JavaTextIOSCollator_IOSCollationKey)

CF_EXTERN_C_BEGIN
CF_EXTERN_C_END

J2OBJC_TYPE_LITERAL_HEADER(JavaTextIOSCollator_IOSCollationKey)

#endif // _JavaTextIOSCollator_H_
