//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: /Users/krasnocka/Downloads/j2objc-master/guava/sources/com/google/common/annotations/Beta.java
//

#include "J2ObjC_header.h"

#if !ComGoogleCommonAnnotationsBeta_RESTRICT
#define ComGoogleCommonAnnotationsBeta_INCLUDE_ALL 1
#endif
#undef ComGoogleCommonAnnotationsBeta_RESTRICT
#if !defined (_ComGoogleCommonAnnotationsBeta_) && (ComGoogleCommonAnnotationsBeta_INCLUDE_ALL || ComGoogleCommonAnnotationsBeta_INCLUDE)
#define _ComGoogleCommonAnnotationsBeta_

#define JavaLangAnnotationAnnotation_RESTRICT 1
#define JavaLangAnnotationAnnotation_INCLUDE 1
#include "java/lang/annotation/Annotation.h"


@protocol ComGoogleCommonAnnotationsBeta < JavaLangAnnotationAnnotation >

@end

J2OBJC_EMPTY_STATIC_INIT(ComGoogleCommonAnnotationsBeta)
#endif

J2OBJC_TYPE_LITERAL_HEADER(ComGoogleCommonAnnotationsBeta)
