//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: /Users/krasnocka/Downloads/j2objc-master/guava/sources/com/google/common/annotations/GwtIncompatible.java
//

#include "J2ObjC_header.h"

#if !ComGoogleCommonAnnotationsGwtIncompatible_RESTRICT
#define ComGoogleCommonAnnotationsGwtIncompatible_INCLUDE_ALL 1
#endif
#undef ComGoogleCommonAnnotationsGwtIncompatible_RESTRICT
#if !defined (_ComGoogleCommonAnnotationsGwtIncompatible_) && (ComGoogleCommonAnnotationsGwtIncompatible_INCLUDE_ALL || ComGoogleCommonAnnotationsGwtIncompatible_INCLUDE)
#define _ComGoogleCommonAnnotationsGwtIncompatible_

#define JavaLangAnnotationAnnotation_RESTRICT 1
#define JavaLangAnnotationAnnotation_INCLUDE 1
#include "java/lang/annotation/Annotation.h"


@protocol ComGoogleCommonAnnotationsGwtIncompatible < JavaLangAnnotationAnnotation >

@end

J2OBJC_EMPTY_STATIC_INIT(ComGoogleCommonAnnotationsGwtIncompatible)
#endif

J2OBJC_TYPE_LITERAL_HEADER(ComGoogleCommonAnnotationsGwtIncompatible)
