//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: /Users/krasnocka/Downloads/j2objc-master/guava/sources/com/google/common/annotations/VisibleForTesting.java
//

#include "J2ObjC_header.h"

#if !ComGoogleCommonAnnotationsVisibleForTesting_RESTRICT
#define ComGoogleCommonAnnotationsVisibleForTesting_INCLUDE_ALL 1
#endif
#undef ComGoogleCommonAnnotationsVisibleForTesting_RESTRICT
#if !defined (_ComGoogleCommonAnnotationsVisibleForTesting_) && (ComGoogleCommonAnnotationsVisibleForTesting_INCLUDE_ALL || ComGoogleCommonAnnotationsVisibleForTesting_INCLUDE)
#define _ComGoogleCommonAnnotationsVisibleForTesting_

#define JavaLangAnnotationAnnotation_RESTRICT 1
#define JavaLangAnnotationAnnotation_INCLUDE 1
#include "java/lang/annotation/Annotation.h"


@protocol ComGoogleCommonAnnotationsVisibleForTesting < JavaLangAnnotationAnnotation >

@end

J2OBJC_EMPTY_STATIC_INIT(ComGoogleCommonAnnotationsVisibleForTesting)
#endif

J2OBJC_TYPE_LITERAL_HEADER(ComGoogleCommonAnnotationsVisibleForTesting)
