//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: android/frameworks/base/core/java/android/text/SpanSet.java
//

#ifndef _AndroidTextSpanSet_H_
#define _AndroidTextSpanSet_H_

@class IOSClass;
@class IOSIntArray;
@class IOSObjectArray;
@protocol AndroidTextSpanned;

#include "J2ObjC_header.h"

@interface AndroidTextSpanSet : NSObject {
 @public
  jint numberOfSpans_;
  IOSObjectArray *spans_;
  IOSIntArray *spanStarts_;
  IOSIntArray *spanEnds_;
  IOSIntArray *spanFlags_;
}

- (instancetype)initWithIOSClass:(IOSClass *)type;

- (void)init__WithAndroidTextSpanned:(id<AndroidTextSpanned>)spanned
                             withInt:(jint)start
                             withInt:(jint)limit OBJC_METHOD_FAMILY_NONE;

- (jboolean)hasSpansIntersectingWithInt:(jint)start
                                withInt:(jint)end;

- (jint)getNextTransitionWithInt:(jint)start
                         withInt:(jint)limit;

- (void)recycle;

@end

J2OBJC_EMPTY_STATIC_INIT(AndroidTextSpanSet)

J2OBJC_FIELD_SETTER(AndroidTextSpanSet, spans_, IOSObjectArray *)
J2OBJC_FIELD_SETTER(AndroidTextSpanSet, spanStarts_, IOSIntArray *)
J2OBJC_FIELD_SETTER(AndroidTextSpanSet, spanEnds_, IOSIntArray *)
J2OBJC_FIELD_SETTER(AndroidTextSpanSet, spanFlags_, IOSIntArray *)

CF_EXTERN_C_BEGIN
CF_EXTERN_C_END

J2OBJC_TYPE_LITERAL_HEADER(AndroidTextSpanSet)

#endif // _AndroidTextSpanSet_H_
