//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: android/libcore/luni/src/main/java/org/apache/harmony/xml/dom/EntityImpl.java
//

#ifndef _OrgApacheHarmonyXmlDomEntityImpl_H_
#define _OrgApacheHarmonyXmlDomEntityImpl_H_

@class OrgApacheHarmonyXmlDomDocumentImpl;

#include "J2ObjC_header.h"
#include "org/apache/harmony/xml/dom/NodeImpl.h"
#include "org/w3c/dom/Entity.h"

@interface OrgApacheHarmonyXmlDomEntityImpl : OrgApacheHarmonyXmlDomNodeImpl < OrgW3cDomEntity > {
}

- (instancetype)initWithOrgApacheHarmonyXmlDomDocumentImpl:(OrgApacheHarmonyXmlDomDocumentImpl *)document
                                              withNSString:(NSString *)notationName
                                              withNSString:(NSString *)publicID
                                              withNSString:(NSString *)systemID;

- (NSString *)getNodeName;

- (jshort)getNodeType;

- (NSString *)getNotationName;

- (NSString *)getPublicId;

- (NSString *)getSystemId;

- (NSString *)getInputEncoding;

- (NSString *)getXmlEncoding;

- (NSString *)getXmlVersion;

@end

J2OBJC_EMPTY_STATIC_INIT(OrgApacheHarmonyXmlDomEntityImpl)

CF_EXTERN_C_BEGIN
CF_EXTERN_C_END

J2OBJC_TYPE_LITERAL_HEADER(OrgApacheHarmonyXmlDomEntityImpl)

#endif // _OrgApacheHarmonyXmlDomEntityImpl_H_
