//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: android/libcore/luni/src/main/java/java/lang/Byte.java
//

#ifndef _JavaLangByte_H_
#define _JavaLangByte_H_

@class IOSClass;
@class IOSObjectArray;

#include "J2ObjC_header.h"
#include "java/lang/Comparable.h"

#define JavaLangByte_MAX_VALUE 127
#define JavaLangByte_MIN_VALUE -128
#define JavaLangByte_SIZE 8
#define JavaLangByte_serialVersionUID -7183698231559129828LL

@interface JavaLangByte : NSNumber < JavaLangComparable > {
}

- (instancetype)initWithByte:(jbyte)value;

- (instancetype)initWithNSString:(NSString *)string;

- (jbyte)charValue;

- (jint)compareToWithId:(JavaLangByte *)object;

+ (jint)compareWithByte:(jbyte)lhs
               withByte:(jbyte)rhs;

+ (JavaLangByte *)decodeWithNSString:(NSString *)string;

- (jdouble)doubleValue;

- (jboolean)isEqual:(id)object;

- (jfloat)floatValue;

- (NSUInteger)hash;

- (jint)intValue;

- (jlong)longLongValue;

+ (jbyte)parseByteWithNSString:(NSString *)string;

+ (jbyte)parseByteWithNSString:(NSString *)string
                       withInt:(jint)radix;

- (jshort)shortValue;

- (NSString *)description;

+ (NSString *)toHexStringWithByte:(jbyte)b
                      withBoolean:(jboolean)upperCase;

+ (NSString *)toStringWithByte:(jbyte)value;

+ (JavaLangByte *)valueOfWithNSString:(NSString *)string;

+ (JavaLangByte *)valueOfWithNSString:(NSString *)string
                              withInt:(jint)radix;

+ (JavaLangByte *)valueOfWithByte:(jbyte)b;


@end

FOUNDATION_EXPORT BOOL JavaLangByte_initialized;
J2OBJC_STATIC_INIT(JavaLangByte)

CF_EXTERN_C_BEGIN

FOUNDATION_EXPORT jint JavaLangByte_compareWithByte_withByte_(jbyte lhs, jbyte rhs);

FOUNDATION_EXPORT JavaLangByte *JavaLangByte_decodeWithNSString_(NSString *string);

FOUNDATION_EXPORT jbyte JavaLangByte_parseByteWithNSString_(NSString *string);

FOUNDATION_EXPORT jbyte JavaLangByte_parseByteWithNSString_withInt_(NSString *string, jint radix);

FOUNDATION_EXPORT NSString *JavaLangByte_toHexStringWithByte_withBoolean_(jbyte b, jboolean upperCase);

FOUNDATION_EXPORT NSString *JavaLangByte_toStringWithByte_(jbyte value);

FOUNDATION_EXPORT JavaLangByte *JavaLangByte_valueOfWithNSString_(NSString *string);

FOUNDATION_EXPORT JavaLangByte *JavaLangByte_valueOfWithNSString_withInt_(NSString *string, jint radix);

FOUNDATION_EXPORT JavaLangByte *JavaLangByte_valueOfWithByte_(jbyte b);

J2OBJC_STATIC_FIELD_GETTER(JavaLangByte, serialVersionUID, jlong)

J2OBJC_STATIC_FIELD_GETTER(JavaLangByte, MAX_VALUE, jbyte)

J2OBJC_STATIC_FIELD_GETTER(JavaLangByte, MIN_VALUE, jbyte)

J2OBJC_STATIC_FIELD_GETTER(JavaLangByte, SIZE, jint)

FOUNDATION_EXPORT IOSClass *JavaLangByte_TYPE_;
J2OBJC_STATIC_FIELD_GETTER(JavaLangByte, TYPE_, IOSClass *)

FOUNDATION_EXPORT IOSObjectArray *JavaLangByte_VALUES_;
J2OBJC_STATIC_FIELD_GETTER(JavaLangByte, VALUES_, IOSObjectArray *)
CF_EXTERN_C_END

BOXED_INC_AND_DEC(Byte, charValue, JavaLangByte)

J2OBJC_TYPE_LITERAL_HEADER(JavaLangByte)

#endif // _JavaLangByte_H_
