//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: android/libcore/luni/src/main/java/java/lang/NumberFormatException.java
//

#ifndef _JavaLangNumberFormatException_H_
#define _JavaLangNumberFormatException_H_

#include "J2ObjC_header.h"
#include "java/lang/IllegalArgumentException.h"

#define JavaLangNumberFormatException_serialVersionUID -2848938806368998894LL

@interface JavaLangNumberFormatException : JavaLangIllegalArgumentException {
}

- (instancetype)init;

- (instancetype)initWithNSString:(NSString *)detailMessage;

@end

J2OBJC_EMPTY_STATIC_INIT(JavaLangNumberFormatException)

CF_EXTERN_C_BEGIN

J2OBJC_STATIC_FIELD_GETTER(JavaLangNumberFormatException, serialVersionUID, jlong)
CF_EXTERN_C_END

J2OBJC_TYPE_LITERAL_HEADER(JavaLangNumberFormatException)

#endif // _JavaLangNumberFormatException_H_
