//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: android/libcore/luni/src/main/java/libcore/util/EmptyArray.java
//

#ifndef _LibcoreUtilEmptyArray_H_
#define _LibcoreUtilEmptyArray_H_

@class IOSBooleanArray;
@class IOSByteArray;
@class IOSCharArray;
@class IOSDoubleArray;
@class IOSIntArray;
@class IOSObjectArray;

#include "J2ObjC_header.h"

@interface LibcoreUtilEmptyArray : NSObject {
}

@end

FOUNDATION_EXPORT BOOL LibcoreUtilEmptyArray_initialized;
J2OBJC_STATIC_INIT(LibcoreUtilEmptyArray)

CF_EXTERN_C_BEGIN

FOUNDATION_EXPORT IOSBooleanArray *LibcoreUtilEmptyArray_BOOLEAN_;
J2OBJC_STATIC_FIELD_GETTER(LibcoreUtilEmptyArray, BOOLEAN_, IOSBooleanArray *)

FOUNDATION_EXPORT IOSByteArray *LibcoreUtilEmptyArray_BYTE_;
J2OBJC_STATIC_FIELD_GETTER(LibcoreUtilEmptyArray, BYTE_, IOSByteArray *)

FOUNDATION_EXPORT IOSCharArray *LibcoreUtilEmptyArray_CHAR_;
J2OBJC_STATIC_FIELD_GETTER(LibcoreUtilEmptyArray, CHAR_, IOSCharArray *)

FOUNDATION_EXPORT IOSDoubleArray *LibcoreUtilEmptyArray_DOUBLE_;
J2OBJC_STATIC_FIELD_GETTER(LibcoreUtilEmptyArray, DOUBLE_, IOSDoubleArray *)

FOUNDATION_EXPORT IOSIntArray *LibcoreUtilEmptyArray_INT_;
J2OBJC_STATIC_FIELD_GETTER(LibcoreUtilEmptyArray, INT_, IOSIntArray *)

FOUNDATION_EXPORT IOSObjectArray *LibcoreUtilEmptyArray_CLASS_;
J2OBJC_STATIC_FIELD_GETTER(LibcoreUtilEmptyArray, CLASS_, IOSObjectArray *)

FOUNDATION_EXPORT IOSObjectArray *LibcoreUtilEmptyArray_OBJECT_;
J2OBJC_STATIC_FIELD_GETTER(LibcoreUtilEmptyArray, OBJECT_, IOSObjectArray *)

FOUNDATION_EXPORT IOSObjectArray *LibcoreUtilEmptyArray_STRING_;
J2OBJC_STATIC_FIELD_GETTER(LibcoreUtilEmptyArray, STRING_, IOSObjectArray *)

FOUNDATION_EXPORT IOSObjectArray *LibcoreUtilEmptyArray_THROWABLE_;
J2OBJC_STATIC_FIELD_GETTER(LibcoreUtilEmptyArray, THROWABLE_, IOSObjectArray *)

FOUNDATION_EXPORT IOSObjectArray *LibcoreUtilEmptyArray_STACK_TRACE_ELEMENT_;
J2OBJC_STATIC_FIELD_GETTER(LibcoreUtilEmptyArray, STACK_TRACE_ELEMENT_, IOSObjectArray *)

FOUNDATION_EXPORT IOSObjectArray *LibcoreUtilEmptyArray_TYPE_;
J2OBJC_STATIC_FIELD_GETTER(LibcoreUtilEmptyArray, TYPE_, IOSObjectArray *)

FOUNDATION_EXPORT IOSObjectArray *LibcoreUtilEmptyArray_TYPE_VARIABLE_;
J2OBJC_STATIC_FIELD_GETTER(LibcoreUtilEmptyArray, TYPE_VARIABLE_, IOSObjectArray *)
CF_EXTERN_C_END

J2OBJC_TYPE_LITERAL_HEADER(LibcoreUtilEmptyArray)

#endif // _LibcoreUtilEmptyArray_H_
