//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: android/libcore/luni/src/main/java/java/util/logging/SimpleFormatter.java
//

#ifndef _JavaUtilLoggingSimpleFormatter_H_
#define _JavaUtilLoggingSimpleFormatter_H_

@class JavaUtilLoggingLogRecord;

#include "J2ObjC_header.h"
#include "java/util/logging/Formatter.h"

@interface JavaUtilLoggingSimpleFormatter : JavaUtilLoggingFormatter {
}

- (instancetype)init;

- (NSString *)formatWithJavaUtilLoggingLogRecord:(JavaUtilLoggingLogRecord *)r;

@end

J2OBJC_EMPTY_STATIC_INIT(JavaUtilLoggingSimpleFormatter)

CF_EXTERN_C_BEGIN
CF_EXTERN_C_END

J2OBJC_TYPE_LITERAL_HEADER(JavaUtilLoggingSimpleFormatter)

#endif // _JavaUtilLoggingSimpleFormatter_H_
