//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: /Users/krasnocka/Downloads/j2objc-master/testing/mockito/build_result/java/org/mockito/internal/runners/RunnerFactory.java
//

#ifndef _OrgMockitoInternalRunnersRunnerFactory_H_
#define _OrgMockitoInternalRunnersRunnerFactory_H_

@class IOSClass;
@class OrgMockitoInternalRunnersUtilRunnerProvider;
@protocol OrgMockitoInternalRunnersRunnerImpl;

#include "J2ObjC_header.h"

@interface OrgMockitoInternalRunnersRunnerFactory : NSObject {
}

- (instancetype)initWithOrgMockitoInternalRunnersUtilRunnerProvider:(OrgMockitoInternalRunnersUtilRunnerProvider *)runnerProvider;

- (instancetype)init;

- (id<OrgMockitoInternalRunnersRunnerImpl>)createWithIOSClass:(IOSClass *)klass;

@end

J2OBJC_EMPTY_STATIC_INIT(OrgMockitoInternalRunnersRunnerFactory)

CF_EXTERN_C_BEGIN
CF_EXTERN_C_END

J2OBJC_TYPE_LITERAL_HEADER(OrgMockitoInternalRunnersRunnerFactory)

#endif // _OrgMockitoInternalRunnersRunnerFactory_H_
